### ISSUE TITLE
problem in compiling process.

### ISSUE THREAD

**Issue by crazyofapple** [baidu/AnyQ#1]
[  4%] Built target extern_leveldb
[  9%] Built target extern_jsoncpp
[ 13%] Built target extern_gtest
[ 18%] Built target extern_xgboost
[ 22%] Built target extern_eigen
[ 23%] Performing build step for 'extern_paddle'
[  1%] Built target extern_snappy
[  2%] Built target extern_lib_any
[  3%] Built target extern_eigen3
[  4%] Built target extern_warpctc
[  4%] Built target extern_mklml
[  4%] Built target extern_gflags
[  5%] Built target framework_py_proto_init
[  5%] Built target extern_boost
[  5%] Built target extern_zlib
[  5%] Built target profiler_py_proto_init
[  6%] Performing configure step for 'swig'
[  7%] Built target extern_threadpool
+ test -d Tools/config
+ aclocal -I Tools/config
./autogen.sh: 11: ./autogen.sh: aclocal: not found
CMakeFiles/swig.dir/build.make:106: recipe for target 'third_party/swig/src/swig-stamp/swig-configure' failed
make[5]: *** [third_party/swig/src/swig-stamp/swig-configure] Error 127
CMakeFiles/Makefile2:370: recipe for target 'CMakeFiles/swig.dir/all' failed
make[4]: *** [CMakeFiles/swig.dir/all] Error 2
make[4]: *** Waiting for unfinished jobs....
[  7%] Built target extern_snappystream
[  8%] Built target extern_glog
[  9%] Built target extern_protobuf
Makefile:105: recipe for target 'all' failed
make[3]: *** [all] Error 2
CMakeFiles/extern_paddle.dir/build.make:111: recipe for target 'third_party/paddle/src/extern_paddle-stamp/extern_paddle-build' failed
make[2]: *** [third_party/paddle/src/extern_paddle-stamp/extern_paddle-build] Error 2
CMakeFiles/Makefile2:511: recipe for target 'CMakeFiles/extern_paddle.dir/all' failed
make[1]: *** [CMakeFiles/extern_paddle.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by yinweichong** [comment]
```
./autogen.sh: 11: ./autogen.sh: aclocal: not found
```

automake&autoconf is needed to compile swig using autogen.sh
you can install it and try again.
```
# how to install automake
# on Ubuntu
sudo apt-get install automake
```
I'm sorry these dependencies are not mentioned in README.md.

**Comment by crazyofapple** [comment]
Thank you! And I have run demo successfully.
