### ISSUE TITLE
请求下如何利用SimNet训练自己的数据？

### ISSUE THREAD

**Issue by pengyulong** [baidu/AnyQ#101]
最近想用自己搜集到的语义匹配数据，利用SimNet来训练，看了官方的训练文档，发现对立面的pointwise和Pairwise的数据，一直没太明白，训练的example也没看懂，想知道立面的QueryID 具体是指什么？能否结合实际例子，说明一下？
![image](https://user-images.githubusercontent.com/9189026/51072336-edfb7d80-1699-11e9-941a-8230066d51fa.png)

**Comment by zhangyanbo2007** [comment]
关于anyQ源码细节研读，请加我微信15821444815，一起研究研究！
