### ISSUE TITLE
启动server后想要让他返回多个候选答案应该怎么操作？

### ISSUE THREAD

**Issue by zide05** [baidu/AnyQ#102]
在向server提出question的时候，如果想让server返回多个候选的答案而不是只有一个答案，应当如何修改？

**Comment by zhangyanbo2007** [comment]
同问，本人也遇到同样的问题

**Comment by zhangyanbo2007** [comment]
请问多个候选答案的问题您已经解决了吗？

**Comment by zengsentry** [comment]
> 在向server提出question的时候，如果想让server返回多个候选的答案而不是只有一个答案，应当如何修改？

**Comment by xiaoyichao** [comment]
这个问题解决了吗？我也有同样的疑问
