### ISSUE TITLE
请问AnyQ如何适配Solrcloud？

### ISSUE THREAD

**Issue by iis-MarkKuang** [baidu/AnyQ#103]
我用zookeeper3.4.13管理solrcloud集群，如何能够使AnyQ适配solrcloud集群，像solrj那样通过提供一个zookeeper的链接来访问solrcloud集群下所有运行的solr实例？

**Comment by yinweichong** [comment]
1. solr灌库
AnyQ提供的示例solr及创建collection和灌库的脚本，是针对单机的；
solrcloud 集群的部署、创建collection 和灌库，可自行搜索相关信息进行扩展；
2. online retrieval (AnyQ中的solr倒排检索插件）
solrcloud集群的访问方式 和 单机solr的访问方式一致，都是host:port/solr/collection/select?...，因此该插件不需要修改；
