### ISSUE TITLE
为什么最开始给的example中的simnet/model中没有cos_sim的文件，在rank.conf中设定score_fetch_name: "cos_sim_0.tmp"可以运行

### ISSUE THREAD

**Issue by zide05** [baidu/AnyQ#104]
1.为什么最开始给的example中的simnet/model中没有cos_sim的文件，在rank.conf中设定score_fetch_name: "cos_sim_0.tmp"可以运行？
2.为什么在自己训练好paddle版本的simnet把模型放到build/example/conf/simnet下之后显示出错，把rank.conf中设定的score_fetch_name改成 "cos_sim.tmp"就可以运行了，但是请求结果测试结果非常差？

**Comment by zhangyanbo2007** [comment]
关于anyQ源码细节研读，请加我微信15821444815，一起研究研究！

**Comment by YoungHu** [comment]
问题关闭了，答案是什么？
