### ISSUE TITLE
调用solr报错。demo跑不起来

### ISSUE THREAD

**Issue by dulcan1988** [baidu/AnyQ#107]
![image](https://user-images.githubusercontent.com/17426274/52107125-2276af80-2630-11e9-807c-b82eb3cca8b5.png)

**Comment by oyjxer** [comment]
检查：tools/solr_script/faq/schema_format中是否有question字段，
重新运行https://github.com/baidu/AnyQ中Demo中构建索引、配置部分脚本

**Comment by ljch2018** [comment]
@oyjxer 麻烦详细说说，具体怎么操作？多谢啊

**Comment by dulcan1988** [comment]
> 检查：tools/solr_script/faq/schema_format中是否有question字段，
> 重新运行[https://github.com/baidu/AnyQ中Demo中构建索引、配置部分脚本](https://github.com/baidu/AnyQ%E4%B8%ADDemo%E4%B8%AD%E6%9E%84%E5%BB%BA%E7%B4%A2%E5%BC%95%E3%80%81%E9%85%8D%E7%BD%AE%E9%83%A8%E5%88%86%E8%84%9A%E6%9C%AC)
-------------
执行时候报错

/AnyQ/build$ cp ../tools/anyq_deps.sh .
/AnyQ/build$ sh anyq_deps.sh
/AnyQ/build$ cp ../tools/solr -rp solr_script
/AnyQ/build$ sh solr_script/anyq_solr.sh solr_script/sample_docs
faq-file trans done
nohup: appending output to 'nohup.out'
solr[8900] start success!
Traceback (most recent call last):
  File "solr_script/solr_api.py", line 18, in <module>
    import solr_tools
  File "/AnyQ/build/solr_script/solr_tools.py", line 55
    print _make_smart_hint(HINT_TYPE_REQ_ERR, errmsg)
                         ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "solr_script/solr_api.py", line 18, in <module>
    import solr_tools
  File "/AnyQ/build/solr_script/solr_tools.py", line 55
    print _make_smart_hint(HINT_TYPE_REQ_ERR, errmsg)
                         ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "solr_script/solr_api.py", line 18, in <module>
    import solr_tools
  File "/AnyQ/build/solr_script/solr_tools.py", line 55
    print _make_smart_hint(HINT_TYPE_REQ_ERR, errmsg)
                         ^
SyntaxError: invalid syntax
upload file error

**Comment by dulcan1988** [comment]
哦，没问题了，这个是Python3.X和2.X写法的差异
