### ISSUE TITLE
Simnet做多分类，输入数据格式该如何定义？

### ISSUE THREAD

**Issue by janfesir007** [baidu/AnyQ#115]
1 1 1 1 1   1 1 1 1 1   1
1 1 1 1 1   2 2 2 2 2   0
3 3 3 3 3   3 3 3 3 3   1
...
如上，所提供数据示例当中pointwise格式的数据的第3列是label，label取值只有0和1(猜测是做二分类)。

我现在想做多分类，label值取了0,1,2（如下）：
1 1 1 1 1   1 1 1 1 1   1
1 1 1 1 1   2 2 2 2 2   0
3 3 3 3 3   3 3 3 3 3   2
...
但是在转换数据格式(convert_train_pointwise_data)时报错，请问是我使用错误么，还是目前不支持多分类？错误如下：
tf_record_writer.py
label[int(group[2])] = 1   // IndexError: list assignment index out of range

**Comment by janfesir007** [comment]
@nwind @errorrik @kuke  可以帮忙解答下吗，感谢~

**Comment by oyjxer** [comment]
目前仅支持而分类@janfesir007

**Comment by janfesir007** [comment]
谢谢  好的。改了一下源码，实现了多分类 @oyjxer
