### ISSUE TITLE
anyq run_strategy failed!

### ISSUE THREAD

**Issue by zhangyanbo2007** [baidu/AnyQ#119]
I0305 11:11:52.765278  8739 utils.cpp:590] RAW: in json_to_analysis_item, query:"你来自哪里"
I0305 11:11:52.765278  8739 utils.cpp:594] RAW: in json_to_analysis_item, type:(null)
I0305 11:11:52.765278  8739 analysis_strategy.cpp:115] RAW: analysis_analysis size: 1
I0305 11:11:52.765278  8739 analysis_strategy.cpp:130] RAW: before use analysis strategy's analysis_result
I0305 11:11:52.765278  8739 utils.cpp:609] RAW: query:"你来自哪里"
I0305 11:11:52.765278  8739 utils.cpp:611] RAW: tokens_basic size is 0
I0305 11:11:52.765278  8739 analysis_strategy.cpp:148] RAW: method_process method_wordseg start
I0305 11:11:52.765278  8739 analysis_strategy.cpp:154] RAW: method_process method_wordseg sucess
I0305 11:11:52.765278  8739 analysis_strategy.cpp:163] RAW: after use analysis strategy's analysis_result
I0305 11:11:52.765278  8739 utils.cpp:609] RAW: query:"你来自哪里"
I0305 11:11:52.765278  8739 utils.cpp:611] RAW: tokens_basic size is 5
I0305 11:11:52.765278  8739 utils.cpp:614] RAW: tokens_basic    buffer:"        length:1        offset:0        analysis_term_weight:0.200000
I0305 11:11:52.765278  8739 utils.cpp:614] RAW: tokens_basic    buffer:你       length:3        offset:1        analysis_term_weight:0.200000
I0305 11:11:52.765278  8739 utils.cpp:614] RAW: tokens_basic    buffer:来自     length:6        offset:4        analysis_term_weight:0.200000
I0305 11:11:52.765278  8739 utils.cpp:614] RAW: tokens_basic    buffer:哪里     length:6        offset:10       analysis_term_weight:0.200000
I0305 11:11:52.765278  8739 utils.cpp:614] RAW: tokens_basic    buffer:"        length:1        offset:16       analysis_term_weight:0.200000
I0305 11:11:52.765278  8739 equal_solr_q_builder.cpp:48] RAW: equal solr_fetch_q=question:\"你来自哪里"
I0305 11:11:52.765278  8739 term_retrieval.cpp:109] RAW: solr_fetch_q=question:\"你来自哪里"
I0305 11:11:52.765278  8739 term_retrieval.cpp:119] RAW: url = http://127.0.0.1:8902/solr/collection1/select
I0305 11:11:52.765278  8739 http_client.cpp:84] RAW: para_url: fl=id,question,answer&q=question%3A%5C%22%E4%BD%A0%E6%9D%A5%E8%87%AA%E5%93%AA%E9%87%8C%22&rows=15&wt=json
W0305 11:11:52.765278  8739 http_client.cpp:94] RAW: curl_easy_perform Failed[Couldn't connect to server];
W0305 11:11:52.765278  8739 term_retrieval.cpp:205] RAW: solr_request failed.
E0305 11:11:52.765278  8739 retrieval_strategy.cpp:122] RAW: plugin term_recall_1 retrieval error
E0305 11:11:52.765278  8739 anyq_strategy.cpp:69] RAW: retrieval module process error
E0305 11:11:52.765278  8739 http_service_impl.cpp:133] RAW: anyq run_strategy failed!

**Comment by zhangyanbo2007** [comment]
![image](https://user-images.githubusercontent.com/9403745/53778449-c1484180-3f37-11e9-9546-b7834e75364d.png)

**Comment by zhangyanbo2007** [comment]
![image](https://user-images.githubusercontent.com/9403745/53778498-e9d03b80-3f37-11e9-81e1-e9465e1afb9f.png)

**Comment by zhangyanbo2007** [comment]
我的solr也正常，不知道这是什么问题？

**Comment by oyjxer** [comment]
检查一下solr使用的ip与port与retrieval.conf中的配置是否相同

**Comment by zhangyanbo2007** [comment]
ok,已经解决了。谢谢。

**Comment by smile901122** [comment]
> I0305 11:11:52.765278 8739 utils.cpp:590] RAW: in json_to_analysis_item, query:"你来自哪里"
> I0305 11:11:52.765278 8739 utils.cpp:594] RAW: in json_to_analysis_item, type:(null)
> I0305 11:11:52.765278 8739 analysis_strategy.cpp:115] RAW: analysis_analysis size: 1
> I0305 11:11:52.765278 8739 analysis_strategy.cpp:130] RAW: before use analysis strategy's analysis_result
> I0305 11:11:52.765278 8739 utils.cpp:609] RAW: query:"你来自哪里"
> I0305 11:11:52.765278 8739 utils.cpp:611] RAW: tokens_basic size is 0
> I0305 11:11:52.765278 8739 analysis_strategy.cpp:148] RAW: method_process method_wordseg start
> I0305 11:11:52.765278 8739 analysis_strategy.cpp:154] RAW: method_process method_wordseg sucess
> I0305 11:11:52.765278 8739 analysis_strategy.cpp:163] RAW: after use analysis strategy's analysis_result
> I0305 11:11:52.765278 8739 utils.cpp:609] RAW: query:"你来自哪里"
> I0305 11:11:52.765278 8739 utils.cpp:611] RAW: tokens_basic size is 5
> I0305 11:11:52.765278 8739 utils.cpp:614] RAW: tokens_basic buffer:" length:1 offset:0 analysis_term_weight:0.200000
> I0305 11:11:52.765278 8739 utils.cpp:614] RAW: tokens_basic buffer:你 length:3 offset:1 analysis_term_weight:0.200000
> I0305 11:11:52.765278 8739 utils.cpp:614] RAW: tokens_basic buffer:来自 length:6 offset:4 analysis_term_weight:0.200000
> I0305 11:11:52.765278 8739 utils.cpp:614] RAW: tokens_basic buffer:哪里 length:6 offset:10 analysis_term_weight:0.200000
> I0305 11:11:52.765278 8739 utils.cpp:614] RAW: tokens_basic buffer:" length:1 offset:16 analysis_term_weight:0.200000
> I0305 11:11:52.765278 8739 equal_solr_q_builder.cpp:48] RAW: equal solr_fetch_q=question:"你来自哪里"
> I0305 11:11:52.765278 8739 term_retrieval.cpp:109] RAW: solr_fetch_q=question:"你来自哪里"
> I0305 11:11:52.765278 8739 term_retrieval.cpp:119] RAW: url = http://127.0.0.1:8902/solr/collection1/select
> I0305 11:11:52.765278 8739 http_client.cpp:84] RAW: para_url: fl=id,question,answer&q=question%3A%5C%22%E4%BD%A0%E6%9D%A5%E8%87%AA%E5%93%AA%E9%87%8C%22&rows=15&wt=json
> W0305 11:11:52.765278 8739 http_client.cpp:94] RAW: curl_easy_perform Failed[Couldn't connect to server];
> W0305 11:11:52.765278 8739 term_retrieval.cpp:205] RAW: solr_request failed.
> E0305 11:11:52.765278 8739 retrieval_strategy.cpp:122] RAW: plugin term_recall_1 retrieval error
> E0305 11:11:52.765278 8739 anyq_strategy.cpp:69] RAW: retrieval module process error
> E0305 11:11:52.765278 8739 http_service_impl.cpp:133] RAW: anyq run_strategy failed!

请问是怎么解决的？
