### ISSUE TITLE
在一台机器上如何启动多个anyQ实例

### ISSUE THREAD

**Issue by jeffreywk** [baidu/AnyQ#120]
现在anyQ是通过run_server启动的，默认加载example里面的conf。我现在需要在一台机器上启动多个实例以保证性能。应该如何传入conf的配置路径？

**Comment by zpc1995** [comment]
你需要修改run_server的源代码。
demo/run_server.cpp 24行可以看到这边是写死的一个相对路径。
`  
if (argc > 2) {  
    anyq_brpc_conf = argv[1];  
}  
`  
可以在24行后加些料，然后重新编译下。

**Comment by zhangyanbo2007** [comment]
一起讨论下anyQ,15821444815加我微信吧！
