### ISSUE TITLE
如何远程访问web服务？

### ISSUE THREAD

**Issue by zhengxusheng** [baidu/AnyQ#121]

**Comment by zhengxusheng** [comment]
AnyQ系统是在远处的服务器上架设的，请问本地如何远程访问web服务，连接到8999端口处的后台界面？求大神解答。

**Comment by AoZhang** [comment]
使用支持http的客户端（比如web浏览器、curl）访问如下接口：
# 请求示例：
http://${host}:${port}/anyq?question=XXX
host 是你的远端服务器ip
port 是你配置AnyQ端口
XXX 为你期望的测试问题

**Comment by zhengxusheng** [comment]
好的，非常感谢！


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: ZHANG Ao <notifications@github.com>
发送时间: 2019年4月18日 17:36
收件人: baidu/AnyQ <AnyQ@noreply.github.com>
抄送: zhengxusheng <1842714112@qq.com>, Author <author@noreply.github.com>
主题: 回复：[baidu/AnyQ] 如何远程访问web服务？ (#121)




使用支持http的客户端（比如web浏览器、curl）访问如下接口：
 
请求示例：
 
http://${host}:${port}/anyq?question=XXX
 host 是你的远端服务器ip
 port 是你配置AnyQ端口
 XXX 为你期望的测试问题

**Comment by zhangyanbo2007** [comment]
一起讨论下anyQ,15821444815加我微信吧！
