### ISSUE TITLE
执行make时报错

### ISSUE THREAD

**Issue by ZhangZoffy** [baidu/AnyQ#124]
[  9%] Generating ../paddle/python/paddle/proto/DataConfig_pb2.py
[  9%] Generating ../paddle/python/paddle/proto/OptimizerConfig_pb2.py
[  9%] Generating ../paddle/python/paddle/proto/TrainerConfig_pb2.py
[  9%] Generating ../paddle/python/paddle/proto/ParameterServerConfig_pb2.py
[  9%] Built target framework_py_proto
[  9%] Built target profiler_py_proto
[  9%] Built target gen_proto_py
Makefile:105: recipe for target 'all' failed
make[3]: *** [all] Error 2
CMakeFiles/extern_paddle.dir/build.make:111: recipe for target 'third_party/paddle/src/extern_paddle-stamp/extern_paddle-build' failed
make[2]: *** [third_party/paddle/src/extern_paddle-stamp/extern_paddle-build] Error 2
CMakeFiles/Makefile2:511: recipe for target 'CMakeFiles/extern_paddle.dir/all' failed
make[1]: *** [CMakeFiles/extern_paddle.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by SLOCAT** [comment]
同问

**Comment by kuangzhenxi** [comment]
我也是

**Comment by kimjuny** [comment]
macos 10.14.3, docker engine 18.09.0,
使用paddle:latest-dev镜像不管尝试几次都是出现同样的错误

**Comment by kimjuny** [comment]
发现是paddle:latest-dev镜像中cmake版本问题，貌似最新版在编译paddle的时候总是会出问题，替换成指定版本`https://github.com/Kitware/CMake/releases/download/v3.2.2/cmake-3.2.2-Linux-x86_64.tar.gz`的cmake后这个问题就解决了

**Comment by xxllp** [comment]
为啥编译老是有问题呢，是因为有些依赖库的cmake 有问题吗
