### ISSUE TITLE
docker环境编译报错

### ISSUE THREAD

**Issue by dlongq** [baidu/AnyQ#127]
/AnyQ/src/server/http_service_impl.cpp: At global scope:
/AnyQ/src/server/http_service_impl.cpp:104:35: warning: unused parameter ‘request’ [-Wunused-parameter]
                const HttpRequest* request,
                                   ^
/AnyQ/src/server/http_service_impl.cpp:149:35: warning: unused parameter ‘request’ [-Wunused-parameter]
                const HttpRequest* request,
                                   ^
/AnyQ/src/server/http_service_impl.cpp:184:35: warning: unused parameter ‘request’ [-Wunused-parameter]
                const HttpRequest* request,
                                   ^
/AnyQ/src/server/http_service_impl.cpp:220:35: warning: unused parameter ‘request’ [-Wunused-parameter]
                const HttpRequest* request,
                                   ^
/AnyQ/src/server/http_service_impl.cpp:255:35: warning: unused parameter ‘request’ [-Wunused-parameter]
                const HttpRequest* request,
                                   ^
In file included from /AnyQ/build/third_party/include/paddle/fluid/framework/lod_tensor.h:28:0,
                 from /AnyQ/include/dict/dict_adapter.h:30,
                 from /AnyQ/include/analysis/method_interface.h:23,
                 from /AnyQ/include/analysis/analysis_strategy.h:18,
                 from /AnyQ/include/strategy/anyq_strategy.h:19,
                 from /AnyQ/include/server/session_data_factory.h:20,
                 from /AnyQ/src/server/http_service_impl.cpp:17:
/AnyQ/build/third_party/include/paddle/fluid/framework/mixed_vector.h: In instantiation of ‘void paddle::framework::Vector<T>::InitByIter(size_t, Iter, Iter) [with Iter = const long unsigned int*; T = long unsigned int; size_t = long unsigned int]’:
/AnyQ/build/third_party/include/paddle/fluid/framework/mixed_vector.h:76:7:   required from ‘paddle::framework::Vector<T>& paddle::framework::Vector<T>::operator=(const paddle::framework::Vector<T>&) [with T = long unsigned int]’
/usr/include/c++/5/bits/stl_algobase.h:340:18:   required from ‘static _OI std::__copy_move<false, false, std::random_access_iterator_tag>::__copy_m(_II, _II, _OI) [with _II = const paddle::framework::Vector<long unsigned int>*; _OI = paddle::framework::Vector<long unsigned int>*]’
/usr/include/c++/5/bits/stl_algobase.h:402:44:   required from ‘_OI std::__copy_move_a(_II, _II, _OI) [with bool _IsMove = false; _II = const paddle::framework::Vector<long unsigned int>*; _OI = paddle::framework::Vector<long unsigned int>*]’
/usr/include/c++/5/bits/stl_algobase.h:438:45:   required from ‘_OI std::__copy_move_a2(_II, _II, _OI) [with bool _IsMove = false; _II = __gnu_cxx::__normal_iterator<const paddle::framework::Vector<long unsigned int>*, std::vector<paddle::framework::Vector<long unsigned int> > >; _OI = __gnu_cxx::__normal_iterator<paddle::framework::Vector<long unsigned int>*, std::vector<paddle::framework::Vector<long unsigned int> > >]’
/usr/include/c++/5/bits/stl_algobase.h:471:8:   required from ‘_OI std::copy(_II, _II, _OI) [with _II = __gnu_cxx::__normal_iterator<const paddle::framework::Vector<long unsigned int>*, std::vector<paddle::framework::Vector<long unsigned int> > >; _OI = __gnu_cxx::__normal_iterator<paddle::framework::Vector<long unsigned int>*, std::vector<paddle::framework::Vector<long unsigned int> > >]’
/usr/include/c++/5/bits/vector.tcc:206:31:   required from ‘std::vector<_Tp, _Alloc>& std::vector<_Tp, _Alloc>::operator=(const std::vector<_Tp, _Alloc>&) [with _Tp = paddle::framework::Vector<long unsigned int>; _Alloc = std::allocator<paddle::framework::Vector<long unsigned int> >]’
/AnyQ/build/third_party/include/paddle/fluid/framework/lod_tensor.h:119:39:   required from here
/AnyQ/build/third_party/include/paddle/fluid/framework/mixed_vector.h:275:49: warning: unused parameter ‘end’ [-Wunused-parameter]
   void InitByIter(size_t size, Iter begin, Iter end) {
                                                 ^
CMakeFiles/anyq.dir/build.make:146: recipe for target 'CMakeFiles/anyq.dir/src/server/http_service_impl.cpp.o' failed
make[2]: *** [CMakeFiles/anyq.dir/src/server/http_service_impl.cpp.o] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/anyq.dir/all' failed
make[1]: *** [CMakeFiles/anyq.dir/all] Error 2
Makefile:75: recipe for target 'all' failed
make: *** [all] Error 2

按照之前的issue，已经把cmake/external/ 下的所有.cmake的线程数都改成了单线程编译，还是报错。。。。

cmake 3.2.2      g++ 5.4.0    bison 3.0.4

nvidia-docker run --name AnyQ815 -it --restart always  paddlepaddle/paddle:latest-dev bash
docker update -m 40960m --memory-swap=71680m --cpus 8 AnyQ815
应该不是内存问题吧。。。

**Comment by nerffei** [comment]
我也是相似的问题，好像是CMakeFiles/anyq.dir/src/server 这个目录下没用东西

**Comment by nerffei** [comment]
我碰到了类似的情况，仔细过程中有一个error, 后来发现是这个 #116  不清楚你是不是，你可以参考下

**Comment by dlongq** [comment]
> 我碰到了类似的情况，仔细看过程中有一个error, 后来发现是这个 #116 不清楚你是不是，你可以参考下

成功了，谢谢大佬
