### ISSUE TITLE
执行make时报错

### ISSUE THREAD

**Issue by SLOCAT** [baidu/AnyQ#129]
![U N2`WS9UEOMP77_3W4QF(9](https://user-images.githubusercontent.com/38071484/55122383-bef19580-5139-11e9-8b01-b8abe2185c10.png)

**Comment by hitzhs** [comment]
[https://github.com/baidu/AnyQ/pull/116](url)

按照这位提交的commit可以完成编译

**Comment by jiyikong** [comment]
使用 make -i

**Comment by jiyikong** [comment]
首先安装paddlepaddle   参考：http://paddlepaddle.org/documentation/docs/zh/1.1/beginners_guide/install/install_Ubuntu.html

**Comment by jiyikong** [comment]
坚持不断的执行cmake .. &  make ，会出现新的文件下载,最后编译成功
原因:多进程的情况下有部分文件下载异常或来不及下载导致的编译异常
