### ISSUE TITLE
图中的语义索引指的是什么？

### ISSUE THREAD

**Issue by IgorWang** [baidu/AnyQ#13]
SimNet看起来把文本映射了向量语义空间，那么这个语义索引指的什么？是能够帮助快速的进行语义匹配吗？输入一个查询，语义表示把查询映射成向量，语义索引利用这个向量快速查询出相关的doc？这个索引的形式是？

**Comment by yinweichong** [comment]
1. SimNet是文本语义匹配框架，计算两个文本语义相似度；
2. 语义索引
* 使用doc向量构建索引(离线)，使用question向量检索向量(在线)，AnyQ里使用了[ANNOY](https://github.com/spotify/annoy)
* SimNet中Representation-based的模型结构，可以将文本映射为向量(取语义表示的结果)
* AnyQ中如何使用语义索引参考[AnyQ使用语义索引](https://github.com/baidu/AnyQ/blob/master/docs/semantic_retrieval_tutorial.md)

**Comment by guotong1988** [comment]
Same question, thank you。

**Comment by zhangyanbo2007** [comment]
关于anyQ源码细节研读，请加我微信15821444815，一起研究研究！
