### ISSUE TITLE
cenos7.5总是出错？linux直接编译和docker编译都报错？？线程也改到单线程了。。求帮助

### ISSUE THREAD

**Issue by kuangzhenxi** [baidu/AnyQ#131]
You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at 6d193d4... add word_emb file
[ 70%] No patch step for 'extern_lac'
[ 70%] No update step for 'extern_lac'
[ 70%] No configure step for 'extern_lac'
[ 71%] Performing build step for 'extern_lac'
-- The CXX compiler identification is GNU 4.8.5
-- The C compiler identification is GNU 4.8.5
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- CXX compiler: /usr/bin/c++, version: GNU 4.8.5
-- C compiler: /usr/bin/cc, version: GNU 4.8.5
-- $PADDLE_ROOT is set to '/kzx/AnyQ/build/third_party/install/paddle/fluid_install_dir'
-- MKLDNN lib not found.
-- MKLML lib found.
-- Configuring done
-- Generating done
-- Build files have been written to: /kzx/AnyQ/build/third_party/lac/src/lac
[ 72%] Performing install step for 'extern_lac'
Scanning dependencies of target lac
[ 16%] [ 33%] Building CXX object CMakeFiles/lac.dir/src/main_tagger.cpp.o
Building CXX object CMakeFiles/lac.dir/src/ilac.cpp.o
[ 50%] Building CXX object CMakeFiles/lac.dir/src/customization_tagger.cpp.o
[ 66%] Building CXX object CMakeFiles/lac.dir/src/lac_util.cpp.o
[ 83%] Building CXX object CMakeFiles/lac.dir/src/lac.cpp.o
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://bugzilla.redhat.com/bugzilla> for instructions.
make[5]: *** [CMakeFiles/lac.dir/src/lac.cpp.o] Error 4
make[5]: *** Waiting for unfinished jobs....
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://bugzilla.redhat.com/bugzilla> for instructions.
make[5]: *** [CMakeFiles/lac.dir/src/main_tagger.cpp.o] Error 4
make[4]: *** [CMakeFiles/lac.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [third_party/lac/src/extern_lac-stamp/extern_lac-install] Error 2
make[1]: *** [CMakeFiles/extern_lac.dir/all] Error 2
make: *** [all] Error 2

这是centos7.5直接make的？我用docker也报错。。。。

**Comment by kuangzhenxi** [comment]
编译了5天了，还没编成功。。求大佬帮忙看看~~~多谢多谢

**Comment by yinweichong** [comment]
参考 https://github.com/baidu/AnyQ/issues/61 https://github.com/baidu/AnyQ/issues/79

**Comment by kuangzhenxi** [comment]
> 参考 #61 #79

ng dependencies of target edit_distance_op
[ 28%] Building CXX object paddle/fluid/operators/CMakeFiles/edit_distance_op.dir/edit_distance_op.cc.o
Linking CXX static library libedit_distance_op.a
[ 28%] Built target edit_distance_op
Scanning dependencies of target elementwise_add_op
[ 28%] Building CXX object paddle/fluid/operators/CMakeFiles/elementwise_add_op.dir/elementwise_add_op.cc.o
Linking CXX static library libelementwise_add_op.a
[ 28%] Built target elementwise_add_op
Scanning dependencies of target elementwise_div_op
[ 28%] Building CXX object paddle/fluid/operators/CMakeFiles/elementwise_div_op.dir/elementwise_div_op.cc.o
Linking CXX static library libelementwise_div_op.a
[ 28%] Built target elementwise_div_op
Scanning dependencies of target elementwise_max_op
[ 28%] Building CXX object paddle/fluid/operators/CMakeFiles/elementwise_max_op.dir/elementwise_max_op.cc.o
Linking CXX static library libelementwise_max_op.a
[ 28%] Built target elementwise_max_op
Scanning dependencies of target elementwise_min_op
[ 28%] Building CXX object paddle/fluid/operators/CMakeFiles/elementwise_min_op.dir/elementwise_min_op.cc.o
Linking CXX static library libelementwise_min_op.a
[ 28%] Built target elementwise_min_op
Scanning dependencies of target elementwise_mul_op
[ 28%] Building CXX object paddle/fluid/operators/CMakeFiles/elementwise_mul_op.dir/elementwise_mul_op.cc.o
Linking CXX static library libelementwise_mul_op.a
[ 28%] Built target elementwise_mul_op
Scanning dependencies of target elementwise_pow_op
[ 28%] Building CXX object paddle/fluid/operators/CMakeFiles/elementwise_pow_op.dir/elementwise_pow_op.cc.o
Linking CXX static library libelementwise_pow_op.a
[ 28%] Built target elementwise_pow_op
Scanning dependencies of target elementwise_sub_op
[ 28%] Building CXX object paddle/fluid/operators/CMakeFiles/elementwise_sub_op.dir/elementwise_sub_op.cc.o
Linking CXX static library libelementwise_sub_op.a
[ 28%] Built target elementwise_sub_op
Scanning dependencies of target expand_op
[ 29%] Building CXX object paddle/fluid/operators/CMakeFiles/expand_op.dir/expand_op.cc.o
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://bugzilla.redhat.com/bugzilla> for instructions.
make[5]: *** [paddle/fluid/operators/CMakeFiles/expand_op.dir/expand_op.cc.o] Error 4
make[4]: *** [paddle/fluid/operators/CMakeFiles/expand_op.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [third_party/paddle/src/extern_paddle-stamp/extern_paddle-build] Error 2
make[1]: *** [CMakeFiles/extern_paddle.dir/all] Error 2
make: *** [all] Error 2
==========================
这个我按这位大佬的https://github.com/ljch2018/AnyQ
重新编译，然后都修改成单线程。
xgboost.cmake：
 INSTALL_COMMAND  cd ${XGBOOST_INSTALL_DIR} && make -j1
paddle.cmake
BUILD_COMMAND        cd ${PADDLE_INSTALL_DIR} && make -j1

======
还是出现以上的错误~~~？

**Comment by kuangzhenxi** [comment]
Cloning into 'eigen'...
remote: Enumerating objects: 86515, done.
remote: Total 86515 (delta 0), reused 0 (delta 0), pack-reused 86515
Receiving objects: 100% (86515/86515), 75.93 MiB | 138.00 KiB/s, done.
Resolving deltas: 100% (67955/67955), done.
Checking connectivity... done.
Note: checking out '3.3.4'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at dde02fc... bump to 3.3.4
[ 19%] No patch step for 'extern_eigen'
[ 20%] No update step for 'extern_eigen'
[ 21%] No configure step for 'extern_eigen'
[ 21%] No build step for 'extern_eigen'
[ 22%] No install step for 'extern_eigen'
[ 22%] Completed 'extern_eigen'
[ 22%] Built target extern_eigen
Scanning dependencies of target extern_paddle
[ 22%] Creating directories for 'extern_paddle'
[ 23%] Performing download step (git clone) for 'extern_paddle'
Cloning into 'extern_paddle'...
error: RPC failed; curl 56 GnuTLS recv error (-54): Error in the pull function.
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
Cloning into 'extern_paddle'...
error: RPC failed; curl 56 GnuTLS recv error (-9): A TLS packet with unexpected length was received.
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
Cloning into 'extern_paddle'...
error: RPC failed; curl 56 GnuTLS recv error (-9): A TLS packet with unexpected length was received.
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
-- Had to git clone more than once:
          3 times.
CMake Error at /AnyQ/build/third_party/paddle/tmp/extern_paddle-gitclone.cmake:40 (message):
  Failed to clone repository: 'https://github.com/PaddlePaddle/Paddle.git'


CMakeFiles/extern_paddle.dir/build.make:89: recipe for target 'third_party/paddle/src/extern_paddle-stamp/extern_paddle-download' failed
make[2]: *** [third_party/paddle/src/extern_paddle-stamp/extern_paddle-download] Error 1
CMakeFiles/Makefile2:511: recipe for target 'CMakeFiles/extern_paddle.dir/all' failed
make[1]: *** [CMakeFiles/extern_paddle.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
====================
用docker编译下，好像也有问题~~~？
docker的环境：
cmake 3.2.2
gcc 5.4
bison 3.0.4
上面两个错误的环境：
centos7.5
cmake 3.2.2
gcc 4.8.5
bison 3.0.4

**Comment by kuangzhenxi** [comment]
已解决。
我用的是https://github.com/ljch2018/AnyQ.git，并且将paddle和xgboost.cmake的线程改到1。
之前失败的原因是我估计是阿里云的服务器没有访问外网导致的。
今天我在自己win上装docker，然后配上vpn，就编译成功了。。。。

**Comment by xxllp** [comment]
你也太逗了吧
