### ISSUE TITLE
make时编译extern_paddle-build异常,make -i 成功后会找不到run_server这个文件

### ISSUE THREAD

**Issue by jiyikong** [baidu/AnyQ#132]
Makefile:105: recipe for target 'all' failed
make[3]: *** [all] Error 2
CMakeFiles/extern_paddle.dir/build.make:111: recipe for target 'third_party/paddle/src/extern_paddle-stamp/extern_paddle-build' failed
make[2]: *** [third_party/paddle/src/extern_paddle-stamp/extern_paddle-build] Error 2
CMakeFiles/Makefile2:511: recipe for target 'CMakeFiles/extern_paddle.dir/all' failed
make[1]: *** [CMakeFiles/extern_paddle.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by jiyikong** [comment]
持续的执行cmake .. & make

**Comment by kimjuny** [comment]
请问这个问题你是如何解决的?
