### ISSUE TITLE
关于模型(simnet+cnn/bow+pointwise)的损失函数的疑问

### ISSUE THREAD

**Issue by hongchenwang** [baidu/AnyQ#136]
paddle语义相似度模型（simnet+cnn+pointwise):
本来网络的输出已经做了softmax操作:
concat_fc = relu_layer.ops(concat)
softmax_layer = layers.FCLayer(2, "softmax", "cos_sim")
pred = softmax_layer.ops(concat_fc)
return left_cnn, pred

但是在计算损失函数的时候又在内部进行了一次softmax操作
    "loss": {
        "module_name": "softmax_cross_entropy_loss",
        "class_name": "SoftmaxCrossEntropyLoss"
    }

个人认为连续两次的softmax操作对模型训练并没有什么益处。
请问，能解释下这里为什么这么做么？为什么不在loss计算层直接用cross_entropy_loss呢？是我哪里理解的有问题么？

**Comment by hongchenwang** [comment]
实验证明loss直接用cross_entropy_loss，训练收敛更快，模型表现更好

**Comment by yinweichong** [comment]
是实现的bug，tf版里的实现是正确的，我们会尽快修正。
感谢指出。

**Comment by zhangyanbo2007** [comment]
一起讨论下anyQ,15821444815加我微信吧！
