### ISSUE TITLE
如何使用ManualRetrievalPlugin插件？

### ISSUE THREAD

**Issue by joseph19871111** [baidu/AnyQ#137]
请问人工干预插件ManualRetrievalPlugin如何配置？
使用 String2RetrievalItemAdapter 字典没用任何效果。

**Comment by AoZhang** [comment]
如认真阅读 https://github.com/baidu/AnyQ/blob/master/docs/config_tutorial.md 后仍无法解决问题，请贴出你的配置和只用方法。

**Comment by kuangzhenxi** [comment]
retrieval_plugin {
        name : "ganyu_recall"
        type : "ManualRetrievalPlugin"
        using_dict_name: "ganyu"
        num_result : 10
}
dict_config{
    name: "ganyu"
    type: "String2RetrievalItemAdapter"
    path: "./ganyu/word.dic"
}
word.dic:
question        answer
hdfs    qa2222
=======================
我debug的时候，读取不了word.dic的内容。。。请问是词典内容写错了吗？

**Comment by kuangzhenxi** [comment]
retrieval_plugin {
name : "ganyu_recall"
type : "ManualRetrievalPlugin"
using_dict_name: "ganyu"
num_result : 10
}
dict_config{
name: "ganyu"
type: "String2RetrievalItemAdapter"
path: "./ganyu/word.dic"
}
word.dic:
question answer
hdfs qa2222
我debug的时候，读取不了word.dic的内容。。。请问是词典内容写错了吗？

**Comment by kuangzhenxi** [comment]
大佬们  求帮助呀

**Comment by zhangyanbo2007** [comment]
一起讨论下anyQ,15821444815加我微信吧！

**Comment by yinweichong** [comment]
dict.conf中对应的type为String2StringAdapter
