### ISSUE TITLE
如何更新词库

### ISSUE THREAD

**Issue by PeralHuang** [baidu/AnyQ#139]
当服务已经启动，要更新词库时是要把solr进程kill，再重启solr吗？还是有其他方法

**Comment by ljch2018** [comment]
除了anyq的接口，还有更新词库的接口，详细看看文档或者Server代码。

**Comment by ljch2018** [comment]
`    int ret = _server.AddService(&http_service_impl,
                brpc::SERVER_DOESNT_OWN_SERVICE,
                "/anyq => anyq,"
                "/solr/v1/delete => solr_delete,"
                "/solr/v1/insert => solr_insert,"
                "/solr/v1/update => solr_update,"
                "/solr/v1/clear => solr_clear");`

**Comment by zhangsirf** [comment]
> 当服务已经启动，要更新词库时是要把solr进程kill，再重启solr吗？还是有其他方法

可以留个联系方式么
