### ISSUE TITLE
编译错误-gflags、glog

### ISSUE THREAD

**Issue by zhdrfirst** [baidu/AnyQ#14]
编译时，直接make，gflags会出错，改成sudo make就能通过，不清楚这是什么坑；
sudo make后，glog有问题，错误提示如下：
/data/denniszheng/AnyQ/build/third_party/glog/src/glog-0.3.5/src/googletest.h:93: undefined reference to `google::FlagRegisterer::FlagRegisterer<std::string>(char const*, char cons      t*, char const*, std::string*, std::string*)'                               
83975 /data/denniszheng/AnyQ/build/third_party/glog/src/glog-0.3.5/src/googletest.h:94: undefined reference to `google::FlagRegisterer::FlagRegisterer<std::string>(char const*, char cons      t*, char const*, std::string*, std::string*)'                               
83976 /data/denniszheng/AnyQ/build/third_party/glog/src/glog-0.3.5/src/googletest.h:96: undefined reference to `google::FlagRegisterer::FlagRegisterer<bool>(char const*, char const*, cha      r const*, bool*, bool*)'                                                    
83977 /data/denniszheng/AnyQ/build/third_party/glog/src/glog-0.3.5/src/googletest.h:100: undefined reference to `google::FlagRegisterer::FlagRegisterer<int>(char const*, char const*, cha      r const*, int*, int*)'                                                      
83978 collect2: error: ld returned 1 exit status
83979 make[3]: *** [logging_unittest] 错误 1
83980 make[2]: *** [third_party/glog/src/extern_glog-stamp/extern_glog-install] 错误 2
83981 make[1]: *** [CMakeFiles/extern_glog.dir/all] 错误 2
83982 make: *** [all] 错误 2

**Comment by zhanghan1992** [comment]
1. 能否把编译gflag时报的错误贴一下？
2. glog只有在系统环境变量里找到gflag头文件和lib时才会依赖gflag编译，可能是你系统环境里的gflag和这个版本的glog冲突了，你可以更新或临时删除系统环境里的gflag。

**Comment by zhanghan1992** [comment]
鉴于系统环境中的gflag可以能会跟glog冲突，我们更新了glog的编译选项，不依赖gflag编译。你可以：
1. git pull 更新代码
2. rm -rf third_party/glog
3. cmake ../
4. make

**Comment by zhdrfirst** [comment]
我重新编译下，谢谢

**Comment by zhdrfirst** [comment]
重新编译后，还是遇到了glfag错误
CMake Error at cmake_install.cmake:96 (file):
  file INSTALL cannot copy file
  "/data/denniszheng/AnyQ/build/third_party/install/paddle/third_party/gflags/src/extern_gflags-build/gflags-registry-entry"
  to "/home/app/.cmake/packages/gflags/b0ea82ae015305d73ac1f82c1a90355a".


make[6]: *** [install] 错误 1
make[5]: *** [third_party/gflags/src/extern_gflags-stamp/extern_gflags-install] 错误 2
make[4]: *** [CMakeFiles/extern_gflags.dir/all] 错误 2
make[4]: *** 正在等待未完成的任务....

**Comment by zhdrfirst** [comment]
[app@VM_36_54_centos build]$ make
[  4%] Built target extern_gtest
[  8%] Built target extern_jsoncpp
[ 12%] Built target extern_xgboost
[ 16%] Built target extern_eigen
[ 16%] Performing build step for 'extern_paddle'
[  1%] Built target extern_lib_any
[  1%] Built target extern_mklml
[  1%] Built target extern_zlib
[  1%] Performing install step for 'extern_gflags'
[  3%] Built target extern_warpctc
[  3%] Built target extern_boost
[  4%] Built target extern_eigen3
[  5%] Built target extern_threadpool
[  6%] Built target extern_snappy
[  6%] Built target framework_py_proto_init
[  6%] Built target profiler_py_proto_init
[  7%] Built target extern_protobuf
[  7%] Built target extern_snappystream
Scanning dependencies of target gen_proto_py
Scanning dependencies of target framework_py_proto
Scanning dependencies of target profiler_py_proto
[  7%] Generating ../paddle/python/paddle/proto/TrainerConfig_pb2.py
[  7%] Running Python protocol buffer compiler on framework.proto
[  7%] Running Python protocol buffer compiler on profiler.proto
[  7%] Generating ../paddle/python/paddle/proto/ParameterServerConfig_pb2.py
[  7%] Generating ../paddle/python/paddle/proto/ParameterService_pb2.py
[  7%] Generating ../paddle/python/paddle/proto/ModelConfig_pb2.py
[ 50%] Built target gflags_nothreads_static
[  7%] Generating ../paddle/python/paddle/proto/OptimizerConfig_pb2.py
[  7%] Generating ../paddle/python/paddle/proto/DataConfig_pb2.py
[100%] Built target gflags_static
[  8%] Generating ../paddle/python/paddle/proto/DataFormat_pb2.py
[  8%] Generating ../paddle/python/paddle/proto/ParameterConfig_pb2.py
Copy generated python proto into directory paddle/fluid/proto/profiler.
Install the project...
Copy generated python proto into directory paddle/fluid/proto.
-- Install configuration: "Release"
-- Up-to-date: /data/denniszheng/AnyQ/build/third_party/install/paddle/third_party/install/gflags/lib/libgflags.a
-- Up-to-date: /data/denniszheng/AnyQ/build/third_party/install/paddle/third_party/install/gflags/lib/libgflags_nothreads.a
-- Up-to-date: /data/denniszheng/AnyQ/build/third_party/install/paddle/third_party/install/gflags/include/gflags/gflags.h
-- Up-to-date: /data/denniszheng/AnyQ/build/third_party/install/paddle/third_party/install/gflags/include/gflags/gflags_declare.h
-- Up-to-date: /data/denniszheng/AnyQ/build/third_party/install/paddle/third_party/install/gflags/include/gflags/gflags_completions.h
-- Up-to-date: /data/denniszheng/AnyQ/build/third_party/install/paddle/third_party/install/gflags/include/gflags/gflags_gflags.h
-- Up-to-date: /data/denniszheng/AnyQ/build/third_party/install/paddle/third_party/install/gflags/lib/cmake/gflags/gflags-config.cmake
-- Up-to-date: /data/denniszheng/AnyQ/build/third_party/install/paddle/third_party/install/gflags/lib/cmake/gflags/gflags-config-version.cmake
-- Up-to-date: /data/denniszheng/AnyQ/build/third_party/install/paddle/third_party/install/gflags/lib/cmake/gflags/gflags-targets.cmake
-- Up-to-date: /data/denniszheng/AnyQ/build/third_party/install/paddle/third_party/install/gflags/lib/cmake/gflags/gflags-targets-release.cmake
-- Up-to-date: /data/denniszheng/AnyQ/build/third_party/install/paddle/third_party/install/gflags/bin/gflags_completions.sh
-- Up-to-date: /data/denniszheng/AnyQ/build/third_party/install/paddle/third_party/install/gflags/lib/pkgconfig/gflags.pc
-- Installing: /home/app/.cmake/packages/gflags/b0ea82ae015305d73ac1f82c1a90355a
CMake Error at cmake_install.cmake:96 (file):
  file INSTALL cannot copy file
  "/data/denniszheng/AnyQ/build/third_party/install/paddle/third_party/gflags/src/extern_gflags-build/gflags-registry-entry"
  to "/home/app/.cmake/packages/gflags/b0ea82ae015305d73ac1f82c1a90355a".


make[6]: *** [install] 错误 1
make[5]: *** [third_party/gflags/src/extern_gflags-stamp/extern_gflags-install] 错误 2
make[4]: *** [CMakeFiles/extern_gflags.dir/all] 错误 2
make[4]: *** 正在等待未完成的任务....
[  8%] Built target framework_py_proto
[  8%] Built target profiler_py_proto
[  8%] Built target gen_proto_py
make[3]: *** [all] 错误 2
make[2]: *** [third_party/paddle/src/extern_paddle-stamp/extern_paddle-build] 错误 2
make[1]: *** [CMakeFiles/extern_paddle.dir/all] 错误 2
make: *** [all] 错误 2

**Comment by zhdrfirst** [comment]
warning: Implicitly compiled files were not subject to annotation processing.
ERROR: /data/denniszheng/AnyQ/build/third_party/bazel/src/bazel_build/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/BUILD:30:1: Building src/java_tools/buildjar/java/com/google/devtools/build/buildjar/libjavac.jar (6 source files) and running annotation processors (AutoAnnotationProcessor, AutoValueProcessor) failed: Unexpected IO error.: ???????
ERROR: I/O error while writing action log: ???????
ERROR: /data/denniszheng/AnyQ/build/third_party/bazel/src/bazel_build/src/BUILD:267:2 Building src/java_tools/buildjar/java/com/google/devtools/build/buildjar/libjavac.jar (6 source files) and running annotation processors (AutoAnnotationProcessor, AutoValueProcessor) failed: Unexpected IO error.: ???????
INFO: Elapsed time: 62.529s, Critical Path: 55.12s
FAILED: Build did NOT complete successfully

ERROR: Could not build Bazel
make[2]: *** [third_party/bazel/src/extern_bazel-stamp/extern_bazel-build] 错误 1
make[1]: *** [CMakeFiles/extern_bazel.dir/all] 错误 2
make: *** [all] 错误 2

**Comment by zhdrfirst** [comment]
由出现了新的编译错误

**Comment by zhanghan1992** [comment]
安装bazel要求环境中有zip, 检查下执行指令'zip -v' 是否会报错

**Comment by zhdrfirst** [comment]
对zip版本有要求么，目前环境中已经安装了zip

**Comment by zhanghan1992** [comment]
我们已经给bazel提了issus，可以关注一下 https://github.com/bazelbuild/bazel/issues/5774

**Comment by zhanghan1992** [comment]
https://github.com/bazelbuild/bazel/issues/5774#issuecomment-410684310

It is hard to say from this information :( what hides behind these question marks in the log? Can you capture the output of compile.sh and attach here?

**Comment by zhdrfirst** [comment]
[  4%] Built target extern_gtest
[  8%] Built target extern_xgboost
[ 12%] Built target extern_eigen
[ 16%] Built target extern_jsoncpp
[ 16%] Performing build step for 'extern_paddle'
[  0%] Performing build step for 'swig'
[  0%] Built target extern_mklml
[  0%] Built target extern_gflags
[  0%] Built target extern_zlib
[  1%] Built target extern_lib_any
[  2%] Built target extern_warpctc
[  4%] Built target extern_eigen3
[  4%] Built target extern_boost
[  5%] Built target extern_threadpool
[  6%] Built target extern_snappy
[  6%] Built target profiler_py_proto_init
[  6%] Built target framework_py_proto_init
[  7%] Built target extern_glog
[  8%] Built target extern_protobuf
[  8%] Built target extern_snappystream
Copy generated python proto into directory paddle/fluid/proto/profiler.
Copy generated python proto into directory paddle/fluid/proto.
[  8%] Built target cblas
[  8%] Built target enforce
[  8%] Built target stringpiece
[  8%] Built target memory_block
[  8%] Built target header
make[6]: warning: jobserver unavailable: using -j1.  Add `+' to parent make rule.
[  8%] Built target framework_proto
[  8%] Built target activation_functions
[  8%] Built target profiler_py_proto
[  8%] Built target framework_py_proto
[  8%] Generating ../paddle/python/paddle/proto/TrainerConfig_pb2.py
[  8%] Generating ../paddle/python/paddle/proto/ParameterService_pb2.py
[  8%] Generating ../paddle/python/paddle/proto/ParameterServerConfig_pb2.py
[  8%] Generating ../paddle/python/paddle/proto/ParameterConfig_pb2.py
[  8%] Generating ../paddle/python/paddle/proto/OptimizerConfig_pb2.py
[  8%] Built target cpu_info
[  8%] Built target dynamic_loader
[  8%] Built target chunk
[  9%] Built target threadpool
[  9%] Built target ddim
[  9%] Built target profiler_proto
[  9%] Generating ../paddle/python/paddle/proto/ModelConfig_pb2.py
[  9%] Generating ../paddle/python/paddle/proto/DataFormat_pb2.py
[  9%] Built target prune
[ 10%] Built target paddle_proto
[ 10%] Generating ../paddle/python/paddle/proto/DataConfig_pb2.py
[ 10%] Built target system_allocator
[ 11%] Built target dynload_warpctc
[ 11%] Built target scanner
[ 11%] Built target place
[ 12%] Built target writer
[ 12%] Built target attribute
[ 12%] Built target scope
[ 13%] Built target buddy_allocator
[ 13%] Built target gen_proto_py
[ 14%] Built target recordio
../Tools/config/ylwrap: line 178: yacc: command not found
[ 14%] Built target device_tracer
make[7]: *** [CParse/parser.c] Error 127
make[6]: *** [source] Error 2
make[5]: *** [third_party/swig/src/swig-stamp/swig-build] Error 2
make[4]: *** [CMakeFiles/swig.dir/all] Error 2
make[4]: *** Waiting for unfinished jobs....
[ 14%] Built target var_handle
[ 15%] Built target memcpy
[ 15%] Built target op_info
[ 15%] Built target op_proto_maker
[ 15%] Built target malloc
make[3]: *** [all] Error 2
make[2]: *** [third_party/paddle/src/extern_paddle-stamp/extern_paddle-build] Error 2
make[1]: *** [CMakeFiles/extern_paddle.dir/all] Error 2
make: *** [all] Error 2

**Comment by zhdrfirst** [comment]
我在一个环境中解决了，换了一个机器，出现这种错误

**Comment by zhanghan1992** [comment]
确保你的环境里 bison >=3.0
