### ISSUE TITLE
可以参考 PaddlePaddle models 中专门针对 SimNet 的介绍和使用示例：[PaddleNLP/paddle-nlp/similarity_net](https://github.com/PaddlePaddle/models/tree/paddle-nlp/PaddleNLP/paddle-nlp/similarity_net)

### ISSUE THREAD

**Issue by stormbirds** [baidu/AnyQ#142]
可以参考 PaddlePaddle models 中专门针对 SimNet 的介绍和使用示例：[PaddleNLP/paddle-nlp/similarity_net](https://github.com/PaddlePaddle/models/tree/paddle-nlp/PaddleNLP/paddle-nlp/similarity_net)

_Originally posted by @AoZhang in https://github.com/baidu/AnyQ/issues/138#issuecomment-484426018_

恩多谢，刚好满足需求，话说百度开源项目整理的好乱啊

**Comment by stormbirds** [comment]
回复错地方了

**Comment by zhangyanbo2007** [comment]
关于anyQ源码细节研读，请加我微信15821444815，一起研究研究！

**Comment by NLPNEU** [comment]
我也在这个问题上遇到了问题，可否请教一下怎么将训练好的模型放到框架中且成功使用呢
