### ISSUE TITLE
simnet解决多分类问题

### ISSUE THREAD

**Issue by estarpro** [baidu/AnyQ#143]
如题，simnet如何解决多分类问题而不是二分类问题。

**Comment by yinweichong** [comment]
SimNet是语义匹配框架，一般为计算相似度任务，pointwise训练方式为 2 分类。
如需要多分类，可在SimNet基础上进行修改，具体参考PaddlePaddle或tensorflow教程；

**Comment by jieli4970** [comment]
> SimNet是语义匹配框架，一般为计算相似度任务，pointwise训练方式为 2 分类。
> 如需要多分类，可在SimNet基础上进行修改，具体参考PaddlePaddle或tensorflow教程；

nihao, protobuf版本是不是有问题呀，把use tensorflow设为on。brpc是0.9嫌弃prot太新了  tks
