### ISSUE TITLE
term2id和训练数据是啥关系

### ISSUE THREAD

**Issue by sea99back** [baidu/AnyQ#147]
比如 
-----term2id 是
term  id
学习   1
工作   2
-----训练的句子是
学习学习学习___ 学习学习学习___1
学习学习学习___工作工作工作___0
学习学习工作___工作工作工作___0
学习工作工作___工作工作工作___1
----那么在pointwise的训练数据文件里是
句子1id列表  句子2id列表    结果
1 1 1 ___1 1 1___1
1 1 1	___2 2 2___0
1 1 2___2 2 2 ___1
1 2 2___2 2 2 ___1
------请大佬给点指点
如果是这样，需要自己写程序从term序列转换为id序列吗

**Comment by zhangyanbo2007** [comment]
关于anyQ源码细节研读，请加我微信15821444815，一起研究研究！
