### ISSUE TITLE
ManualRetrievalPlugin手动干预怎么配置？我配置的怎么读取词典没成功？有debug的结果，求大佬们帮忙指点下。。。

### ISSUE THREAD

**Issue by kuangzhenxi** [baidu/AnyQ#149]
dict.conf的配置：
![image](https://user-images.githubusercontent.com/7956352/56861009-57946300-69cf-11e9-9ccc-13f93d4b8a3b.png)
retrieval.conf的配置：
![image](https://user-images.githubusercontent.com/7956352/56861036-a6da9380-69cf-11e9-96bc-d0787e76bb73.png)
word.dic的内容：
![image](https://user-images.githubusercontent.com/7956352/56861051-d4274180-69cf-11e9-9a87-8f0f726387dd.png)
==================
![image](https://user-images.githubusercontent.com/7956352/56861090-5b74b500-69d0-11e9-82f6-e4db3234b361.png)
这个q2a_dict打印结果是：
![image](https://user-images.githubusercontent.com/7956352/56861105-747d6600-69d0-11e9-9c3c-646a05cd1986.png)
不知道这样是否正常？？？

**Comment by zhangyanbo2007** [comment]
一起讨论下anyQ,15821444815加我微信吧！

**Comment by yinweichong** [comment]
配置没问题，word.dic的图挂了，这个文件对应question \t answer；
看下启动过程中的日志，是否有报错。
正常日志如下：
```
I0100 00:00:00.000000 23570 dual_dict_wrapper.cpp:26] RAW: config_name: manual_recall_dict
I0100 00:00:00.000000 23570 dual_dict_wrapper.cpp:27] RAW: config_type: String2StringAdapter
I0100 00:00:00.000000 23570 dual_dict_wrapper.cpp:28] RAW: config_path: ./manual_recall.dict
I0100 00:00:00.000000 23570 dual_dict_wrapper.cpp:50] RAW: dual dict init: manual_recall_dict, reload:true
I0100 00:00:00.000000 23570 dual_dict_wrapper.cpp:64] RAW: load dict file:./example/conf/./manual_recall.dict
I0100 00:00:00.000000 23570 dual_dict_wrapper.cpp:65] RAW: dict file state: Mon Jul  8 11:07:37 2019

I0100 00:00:00.000000 23570 dict_adapter.h:62] RAW: ./example/conf/./manual_recall.dict
I0100 00:00:00.000000 23570 utils.cpp:46] RAW: hash load ./example/conf/./manual_recall.dict done
I0100 00:00:00.000000 23570 dual_dict_wrapper.cpp:77] RAW: load dict ./example/conf/./manual_recall.dict success
I0100 00:00:00.000000 23570 dict_manager.cpp:59] RAW: dict load success: manual_recall_dict
```
