### ISSUE TITLE
http调用结果，中文全是unicode字符

### ISSUE THREAD

**Issue by seeYouFE** [baidu/AnyQ#150]
{"answer":"\u7531\u4e8e\u6b20\u8d39\u505c\u673a\u3001\u5b58\u50a8\u4fe1\u606f\u5df2\u6ee1\u3001\u4fe1\u53f7\u7f51\u7edc\u5ef6\u8fdf\u7b49\u539f\u56e0\u6ca1\u6709\u53ca\u65f6\u6536\u5230\u9a8c\u8bc1\u7801\uff0c\u8fd9\u65f6\u8bf7\u68c0\u67e5\u60a8\u7684\u624b\u673a\u53ca\u8bdd\u8d39\u4f59\u989d\uff0c\u4fdd\u8bc1\u624b\u673a\u53ef\u6b63\u5e38\u63a5\u6536\u77ed\u4fe1\u540e\uff0c\u8bf7\u5c1d\u8bd5\u91cd\u65b0\u83b7\u53d6\u9a8c\u8bc1\u7801\u3002","confidence":0.6832273006439209,"json_info":"{}\n","qa_id":"2","question":"\u6ce8\u518c\u767e\u5ea6\u8d26\u6237\u65f6\u6536\u4e0d\u5230\u9a8c\

**Comment by zhangyanbo2007** [comment]
一起讨论下anyQ,15821444815加我微信吧！

**Comment by AoZhang** [comment]
看着像你load http 返回的方式不太对。详细描述一下你的用法吧。
