### ISSUE TITLE
AnyQ安装总结

### ISSUE THREAD

**Issue by startmyway** [baidu/AnyQ#151]
本文档总结了笔者安装AnyQ开源软件的经验。感谢百度公司开源本软件，并且耐心解答问题。
本文档参考了https://blog.csdn.net/上面nopSled写的博客。
本安装步骤，没有拉docker镜像，直接在centos里面进行了安装。 Centos的版本：
# cat /etc/redhat-release
CentOS Linux release 7.6.1810 (Core)
一.系统下载及环境安装
1、.github地址：https://codeload.github.com/baidu/AnyQ/zip/master 手动下载系统包。
2、cmake3安装
安装gcc/g++的软件依赖（要求大于4.8.2）（centos安装）
#yum install -y gcc gcc-c++ make automake
下载cmake源代码包（推荐3.3.2）,可以去官网查看最新版的下载地址：https://cmake.org/download/
#wget https://cmake.org/files/v3.3/cmake-3.3.2.tar.gz
解压cmake源码包。进入目录，设置，编译，链接
#cd cmake-3.3.2/ 
#./bootstrap 
#gmake 
#gmake install
3、bison 3.0安装
首先输入下面命令，查看是否安装及版本号，如果没有安装，则需要提前安装
#bison -V
二.系统编译
系统及环境下载安装完以后，进入安装包目录，开始进行编译
#cd ./AnyQ
#mkdir build && cd build && cmake .. & make
这个地方要注意，有网络质量不同。执行cmake以后常常报错。笔者在安装的过程中，这个地方遇到了很大的障碍。
下载安装完成以后build目录的文件可能是这样的（以实际安装为准）：
[root@vm-test-1 build]# ll
total 774940
-rw-r--r--.  1 root root     12419 Apr 25 10:12 CMakeCache.txt
drwxr-xr-x. 26 root root      4096 Apr 28 19:39 CMakeFiles
-rw-r--r--.  1 root root     70738 Apr 28 19:36 Makefile
-rwxr-xr-x.  1 root root  24070976 Apr 28 19:38 annoy_index_build_tool
-rw-r--r--.  1 root root       543 Apr 28 20:05 anyq_deps.sh
-rw-r--r--.  1 root root      1351 Apr 25 10:12 cmake_install.cmake
-rwxr-xr-x.  1 root root  25263504 Apr 28 19:38 demo_anyq
-rwxr-xr-x.  1 root root  25264752 Apr 28 19:39 demo_anyq_multi
drwxrwxr-x.  3  500  501        18 Jun 29  2018 example
-rw-r--r--.  1 root root 258922290 Jul  2  2018 example.tar.gz
drwxr-xr-x.  2 root root        43 Apr 28 10:27 faq
-rwxr-xr-x.  1 root root  25248304 Apr 28 19:39 feature_dump_tool
-rw-r--r--.  1 root root  55429854 Apr 28 19:38 libanyq.a
drwxr-xr-x.  2 root root        22 Apr 28 11:42 logs
-rw-------.  1 root root    277161 Apr 30 15:42 nohup.out
drwxr-xr-x.  4 root root        28 Apr 25 10:12 proto_build-prefix
-rwxr-xr-x.  1 root root  91080496 Apr 28 19:39 run_server
drwxrwxr-x.  8  502  504       218 Jun 26  2018 solr-4.10.3-anyq
-rw-r--r--.  1 root root 287856173 Jul  2  2018 solr-4.10.3-anyq.tar.gz
drwxr-xr-x.  3 root root        20 Apr 28 11:42 solr-webapp
drwxr-xr-x.  2 root root       165 Apr 28 11:42 solr_script
drwxr-xr-x.  2 root root       143 Apr 24 15:52 sor_script
drwxr-xr-x. 24 root root      4096 Apr 26 17:49 third_party
如果cmake的过程中，系统报错。需要先删除third_party目录。否则无法执行cmake。
重复多次，一直到cmake成功为止。
然后执行make。由于网络质量，make一般也要重复多次才能成功。不过make的时候，不用删除文件，反复执行就行了。

三、构建索引、配置及Web服务的安装
1、这个步骤在https://github.com/baidu/AnyQ/ 的README.md里面有说明：
这些命令在build目录下执行:
# 获取anyq定制solr，anyq示例配置
#cp ../tools/anyq_deps.sh .
#sh anyq_deps.sh

# 启动solr, 依赖python-json, jdk>=1.8
#cp ../tools/solr -rp solr_script
#sh solr_script/anyq_solr.sh solr_script/sample_docs
在启动solr的过程中，笔者也遇到了问题。Solr启动不成功。最后定位出来java版本不符合。
参考了这篇文档，修复了java的问题：
https://github.com/baidu/AnyQ/issues/19
java的版本建议采用jdk1.8.0_171。版本高了或者低了，都可能出问题。
将原有的java版本卸掉，然后安装jdk1.8.0_171。
可以采用如下步骤：
#get http://anyq.bj.bcebos.com/jdk-8u171-linux-x64.tar.gz
解压
#tar xzvf jdk-8u171-linux-x64.tar.gz
加到系统路径
#export PATH=’pwd’/jdk1.8.0_171/bin:$PATH
Pwd字符上面有两个单引号。
# java -version
java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)

2、运行run_server
./run_server

# 请求示例：
http:${host}:${port}/anyq?question=XXX
在faq_json里面有问答对。XXX代表问题。例如：需要使用什么账号登录；注册百度账户时收不到验证码怎么办。

[root@vm-test-1 faq]# cat faq_json
{"answer": "您需要拥有一个百度账号，用来登录百度云，可以点击此处注册百度账户。如您以前拥有百度推广账户，同样可以登录百度云。", "question": "需要使用什么账号登录?", "id": "1"}
{"answer": "由于欠费停机、存储信息已满、信号网络延迟等原因没有及时收到验证码，这时请检查您的手机及话费余额，保证手机可正常接收短信后，请尝试重新获取验证码。", "question": "注册百度账户时收不到验证码怎么办？", "id": "2"}
{"answer": "支持推广账户使用。", "question": "AI服务支持推广账号使用么？", "id": "3"}
{"answer": "如果您是初次使用百度云，我们需要收集一些您的几个核心信息，用于做开发者认证，这些信息也会作为您使用产品过程中，我们与您取得联系的重要联系方式。如您之前已经是百度云用户、百度开发者中心用户，此步骤将会自动省略。", "question": "为什么登录到百度云还要填写手机号、邮箱等信息？", "id": "4"}
{"answer": "不需要。我们会自动同步您的开发者信息，但是为保证后续使用中可以及时联系到您，可能会提示您重新补充最新的开发者信息（手机号等）。", "question": "我以前是百度开发者中心用户，还需要进行开发者认证么？", "id": "5"}
{"answer": "目前百度语音、文字识别、人脸识别、自然语言处理、图像审核、知识图谱，这六项技术您可以直接在控制台中使用，也可以通过在百度AI开放平台官网，提交商务合作需求。", "question": "目前都开放了哪些服务？", "id": "6"}
{"answer": "目前我们为每个账户下的每项API服务，都设置了固定的免费请求配额，便于您体验服务及应用调试。", "question": "每个服务的请求配额都是免费的么？", "id": "7"}
{"answer": "目前在同一账号下，每个API服务都有免费的请求配额，您可以在对应服务的控制台中查看。付费服务不限请求数量，即用即扣。", "question": "每个服务的请求配额有限制么？", "id": "8"}
{"answer": "每项服务目前可创建最多100个应用，需要注意的是：每项服务下的所有应用，将会共享您该项服务的请求配额。", "question": "我可以创建多少个应用？", "id": "9"}
{"answer": "目前百度AI开放平台的绝大多数的基础技术能力都是免费的（包括语音识别、语音合成、语音唤醒等等），每天都有既定的配额，如果不够可以填写申请。 语音技术方向的申请方法：请登录控制台，点击百度语音，选择应用列表，选择对应应用，查看详情，点击申请提高配额，一般会在2个工作日内完成审核，审核通过后，将可无限调用。 其他方向申请方式：工单免费申请配额和QPS，官方根据您的应用场景和需求审核后评估调整配额的额度。 还有一些技术服务，已经陆续推出付费商用方案（比如文字识别方向等），为您提供更多维度的支持，您可根据自己的需求定制化自由调用，全方位保障您的产品需求。", "question": "目前这些服务免费吗？能够保证QPS吗？", "id": "10"}
{"answer": "目前文字识别、人脸识别、自然语言处理、图像审核、知识图谱在后台都可以使用百度云AK/SK调用，请求限额相同。非常抱歉的是语音服务暂不支持百度云AK/SK调用，我们会尽快完善，给您带来的不便深感抱歉。", "question": "我是百度云的老用户，可以使用百度云的AK/SK么？", "id": "11"}
{"answer": "目前支持各项服务的Java、PHP、Python、C#、Node.js版本服务端SDK，我们会尽快陆续推出更多语言支持，请您持续关注。", "question": "支持哪些语言的服务端SDK？", "id": "12"}
{"answer": "您可以通过以下两种方式与我们联系：", "question": "我有一些定制化需求，如何与你们取得联系?", "id": "13"}
{"answer": "目前百度AI开放平台大部分产品是免费的，如果您合理化接入应用，有一定的合理化应用场景，可以通过【工单】或者官方右侧【合作咨询】，说明您的使用场景和预期的配额量级，进行申请，我们评估后会尽快满足您的需求：给您免费提高配额，让您充分试用我们的产品；或是有专业负责人与您商务对接，为您的调用保驾护航。其他付费服务-如文字识别方向，已经可以自助付费使用，充值付费后，调用量不再受限。", "question": "如果我正在做一个比较大型的落地项目，需要更多配额如何接洽？", "id": "14"}
{"answer": "目前大部分开放服务是免费的，付费技术服务在技术介绍页最下方以及您的控制台中，都会有相应的免费配额、付费计价的介绍。", "question": "目前除了免费部分，是否支持付费，计费价目表是怎样的？", "id": "15"}
{"answer": "我们将统一使用百度云的账户计费，您只需在百度云中充值即可，依据不同付费方案，将会从您的账户余额中扣费。", "question": "除了免费的百度AI技术服务，付费如何充值？", "id": "16"}

Port端口号是8999。启动run_server以后，打印信息有提示：
I0502 15:59:46.351348 27162 server.cpp:975] Server[anyq::HttpServiceImpl] is serving on port=8999.

例如：执行
http:XXX.XXX.XXX.XXX:8999/anyq?question=如何登录帐号
在服务器端显示：
I0502 15:59:46.371698 27176 anyq_strategy.cpp:77] RAW: input_query=如何登录帐号;analysis_time=17.00ms;retrieval_num=5;retrieval_time=29.00ms;anyq_answer=您需要拥有一个百度账号，用来登录百度云，可以点击此处注册百度账户。如您以前拥有百度推广账户，同样可以登录百度云。;rank_item_num=1;rank_time=36.00ms;

这表示run_server执行成功了。

3、防火墙问题：
笔者运行run_server以后，服务器始终接收不到查询报文。在本机执行curl  http:XXX.XXX.XXX.XXX:8999/anyq?question=如何登录帐号，服务器能够正常响应。
最后定位是防火墙配置的问题，关闭防火墙，问题解决。
# systemctl stop firewalld
# systemctl disable firewalld

4、Unicode转换的问题：
笔者在执行“http:XXX.XXX.XXX.XXX:8999/anyq?question=如何登录帐号”的时候遇到Unicode转换的问题，也困惑了笔者较长时间。
浏览器如果不能支持Unicode的转换，在客户端会显示unicode编码，不会显示汉字。
例如：
[{"answer":"\u60a8\u9700\u8981\u62e5\u6709\u4e00\u4e2a\u767e\u5ea6\u8d26\u53f7\uff0c\u7528\u6765\u767b\u5f55\u767e\u5ea6\u4e91\uff0c\u53ef\u4ee5\u70b9\u51fb\u6b64\u5904\u6ce8\u518c\u767e\u5ea6\u8d26\u6237\u3002\u5982\u60a8\u4ee5\u524d\u62e5\u6709\u767e\u5ea6\u63a8\u5e7f\u8d26\u6237\uff0c\u540c\u6837\u53ef\u4ee5\u767b\u5f55\u767e\u5ea6\u4e91\u3002","confidence":0.72346657514572144,"json_info":"{}\n","qa_id":"1","question":"\u9700\u8981\u4f7f\u7528\u4ec0\u4e48\u8d26\u53f7\u767b\u5f55?"}]
但是在服务器端，已经显示服务器正常工作了。

通过讯问相关专家和查资料，解决了这个问题：下载JSON-handle_0.5.6.crx文件。将文件名改为JSON-handle_0.5.6.rar，解压缩。
打开chrome浏览器：更多工具------扩展程序------加载已解压的扩展程序，选择JSON-handle_0.5.6.rar解压缩的文件夹。
再次执行：
http:XXX.XXX.XXX.XXX:8999/anyq?question=如何登录帐号

显示如下：
JSON
•	0
o	answer您需要拥有一个百度账号，用来登录百度云，可以点击此处注册百度账户。如您以前拥有百度推广账户，同样可以登录百度云。
o	confidence0.72346657514572144
o	json_info{}
o	qa_id1
o	question需要使用什么账号登录?

**Comment by startmyway** [comment]
安装总结，希望对大家有帮助。

**Comment by zhangyanbo2007** [comment]
关于anyQ源码细节研读，请加我微信15821444815，一起研究研究！

**Comment by startmyway** [comment]
已经加了。


------------------ 原始邮件 ------------------
发件人: "zhangyanbo2007"<notifications@github.com>;
发送时间: 2019年5月5日(星期天) 下午2:19
收件人: "baidu/AnyQ"<AnyQ@noreply.github.com>;
抄送: "wenswcc"<1458041836@qq.com>; "State change"<state_change@noreply.github.com>; 
主题: Re: [baidu/AnyQ] AnyQ安装总结 (#151)




关于anyQ源码细节研读，请加我微信15821444815，一起研究研究！

**Comment by xxllp** [comment]
这个怎么新增数据呢

**Comment by Dark-Rich** [comment]
如果安装过程中遇到‘libiconv*’未定义的引用”的问题，可参考
[https://blog.csdn.net/plgkm6/article/details/80258744](url)
