### ISSUE TITLE
关于语义树和solr同步问题

### ISSUE THREAD

**Issue by 34127chi** [baidu/AnyQ#152]
如题，目前想做到solr更新问题时，对应的语义树也更新，annoy好像不支持动态增删
假如solr这边删除或者更新后，语义树这边没有对应的修改，检索出来可能出错

期待回复🙏

**Comment by yinweichong** [comment]
当前语义检索还不支持动态更新；
语义检索库的动态更新， 涉及整个annoy树的重建；
自行实现建议：
    简单的方式，可通过定时或者定量，重新建库重启服务；
    也可考虑单独启动线程进行annoy的索引更新；
