### ISSUE TITLE
sample_input_json?

### ISSUE THREAD

**Issue by WelcomeLi** [baidu/AnyQ#159]
Demo中 最后一个说明lib: ./demo_anyq sample_input_json 。sample_input_json 这个文件没有找到相关说明，里面应该是什么格式的数据？

**Comment by yinweichong** [comment]
每行两个field, \t分割，第一field为question，第二field为json串 {"question":"xxyy"}
举例：
```
测试用例    {"question":"测试用例"}
```
可根据src/analysis/analysis_strategy.cpp中的json_parser自行构造

**Comment by xxllp** [comment]
这句话啥意思啊
