### ISSUE TITLE
AnyQ的性能怎么样？

### ISSUE THREAD

**Issue by wsj14847** [baidu/AnyQ#161]
想了解一下AnyQ的性能怎么样？如果想提升的，可以从哪几个角度来着手呢？

**Comment by yinweichong** [comment]
性能主要以下几个方面影响：
1) FAQ库大小、retrieval阶段召回数量
2) 相似度计算模型复杂程度；
3) brpc并发线程数；

ps:机器本身性能也会影响AnyQ性能，如cpu主频，核数等

**Comment by lucky-you** [comment]
> 性能主要以下几个方面影响：
> 
>     1. FAQ库大小、retrieval阶段召回数量
> 
>     2. 相似度计算模型复杂程度；
> 
>     3. brpc并发线程数；
> 
> 
> ps:机器本身性能也会影响AnyQ性能，如cpu主频，核数等

请教一下：如何提高brpc并发线程数？
