### ISSUE TITLE
pointwise数据问题

### ISSUE THREAD

**Issue by jieli4970** [baidu/AnyQ#162]
Pointwise训练及测试数据格式

训练数据格式：训练数据包含三列，依次为Query1的ID序列（ID间使用空格分割），Query2的ID序列（ID间使用空格分割），Label，每列间使用TAB分割，例如；
1 1 1 1 1 2 2 2 2 2 0
1 1 1 1 1 1 1 1 1 1 1
-----------

请问这里的Q1的ID序列和Q2的ID序列必须长度要是一样的吗？这里是直接使用ID序列来作为词向量吗？

**Comment by jieli4970** [comment]
这个地方能使用自己训练的词向量吗？

**Comment by jieli4970** [comment]
改好了

**Comment by MerryLoveDog** [comment]
这里的ID序中的ID是怎么产生的呢？

**Comment by jieli4970** [comment]
ID 就是词ID
 
---原始邮件---
发件人: "MerryLoveDog"<notifications@github.com&gt;
发送时间: 2019年9月10日 16:32:06
收件人: "baidu/AnyQ"<AnyQ@noreply.github.com&gt;;
抄送: "State change"<state_change@noreply.github.com&gt;;"jieli4970"<819124280@qq.com&gt;;
主题: Re: [baidu/AnyQ] pointwise数据问题 (#162)



这里的ID序中的ID是怎么产生的呢？

**Comment by MerryLoveDog** [comment]
好的，谢谢！
