### ISSUE TITLE
源代码编译失败 

### ISSUE THREAD

**Issue by xxllp** [baidu/AnyQ#163]
> third_party/lib/libleveldb.a(table_builder.o): In function `leveldb::TableBuilder::WriteBlock(leveldb::BlockBuilder*, leveldb::BlockHandle*)':
table_builder.cc:(.text+0x93f): undefined reference to `snappy::MaxCompressedLength(unsigned long)'
table_builder.cc:(.text+0x97d): undefined reference to `snappy::RawCompress(char const*, unsigned long, char*, unsigned long*)'
third_party/lib/libleveldb.a(format.o): In function `leveldb::ReadBlock(leveldb::RandomAccessFile*, leveldb::ReadOptions const&, leveldb::BlockHandle const&, leveldb::BlockContents*)':
format.cc:(.text+0x4d9): undefined reference to `snappy::GetUncompressedLength(char const*, unsigned long, unsigned long*)'
format.cc:(.text+0x5ae): undefined reference to `snappy::RawUncompress(char const*, unsigned long, char*)'
collect2: error: ld returned 1 exit status
make[2]: *** [run_server] Error 1
make[1]: *** [CMakeFiles/run_server.dir/all] Error 2
make: *** [all] Error 2

从这错误也无法定位问题哈

**Comment by yinweichong** [comment]
可否提供更详细的报错信息。
ps: 依赖的库对系统环境有一定要求，推荐使用docker方式安装。

**Comment by qq932546734** [comment]
这个问题我解决了，先安装snappy，然后在编译leveldb的时候，加上参数-lsnappy，具体如下

1. 安装snappy

```bash
git clone https://github.com/google/snappy.git
make build && cd build && cmake ../ && sudo make 
```
2. 修改AnyQ/cmake/external/leveldb.cmake第18行，即INSTALL_COMMAND的最后面，将`make`改成`make -lsnappy`
