### ISSUE TITLE
基于提供的模型增量训练

### ISSUE THREAD

**Issue by ganguagua** [baidu/AnyQ#165]
可以提供persistables的模型吗

**Comment by ganguagua** [comment]
配置文件中的模型对应的是tools里面的哪个模型，怎么都对应不上

**Comment by vnlp** [comment]
和你遇到了同样的问题，就算用自己的数据训出了模型，也没有导入的方式的说明

**Comment by ganguagua** [comment]
> 和你遇到了同样的问题，就算用自己的数据训出了模型，也没有导入的方式的说明

自己训练的效果不好，要么就是准确度不好，要么就是太慢

**Comment by ami66** [comment]
自己的数据训出了模型，怎么导入进AnyQ？你知道吗

**Comment by vnlp** [comment]
@ganguagua     能请教一下您怎么导入自己的模型么

**Comment by ganguagua** [comment]
tf的需要自己改一点代码，paddle你可以用bow的pairwise，应该是不用改代码，别的其实你就配一下conf文件的输入op的名称就好了


 
---原始邮件---
发件人: "fangcheng"<notifications@github.com>
发送时间: 2019年7月1日(星期一) 晚上6:05
收件人: "baidu/AnyQ"<AnyQ@noreply.github.com>;
抄送: "Mention"<mention@noreply.github.com>;"ganguagua"<1308058625@qq.com>;
主题: Re: [baidu/AnyQ] 基于提供的模型增量训练 (#165)



@ganguagua     能请教一下您怎么导入自己的模型么

**Comment by vnlp** [comment]
@ganguagua   我试过直接将对应的文件取代example中的simnet中model部分，但是会报错，能加个微信问下细节么？谢谢啦，我微信是13840339515

**Comment by yinweichong** [comment]
SimNet-paddle训出的模型，可直接替换example/conf/simnet/model。
如果使用了语义索引，注意修改example/conf/analysis.conf中的embedding_fetch_name
