### ISSUE TITLE
怎么将在/AnyQ/tools训练好的paddle的simnet模型导入进去，让模型用于后面的相似度计算

### ISSUE THREAD

**Issue by vnlp** [baidu/AnyQ#166]
如题，尝试过直接将tools训练出来的模型直接copy到example中的simnet中的model文件夹下面，但是copy进去之后并不能运行通，在生成语意索引库的时候会报错！

**Comment by yinweichong** [comment]
SimNet-paddle训出的模型，可直接替换example/conf/simnet/model。
如果使用了语义索引，注意修改example/conf/analysis.conf中的embedding_fetch_name

**Comment by vivianzy1985** [comment]
> SimNet-paddle训出的模型，可直接替换example/conf/simnet/model。
> 如果使用了语义索引，注意修改example/conf/analysis.conf中的embedding_fetch_name

请问 是将训练好好的哪种model  放入example/conf/simnet/model下。是checkpoint和cnn.epoch1.data-00000-of-00001 这种吗？ 还是用freeze函数之后生成的xxxxx.protxt" (freeze任务结果文件)
