### ISSUE TITLE
没人回答，如何导入训练好的模型

### ISSUE THREAD

**Issue by ami66** [baidu/AnyQ#167]
怎么将在/AnyQ/tools训练好的paddle的simnet模型导入进去，让模型用于后面的相似度计算

**Comment by ak47-1234** [comment]
可参考matching插件配置方式
https://github.com/baidu/AnyQ/blob/master/docs/config_tutorial.md#matching

**Comment by ami66** [comment]
> 可参考matching插件配置方式
> https://github.com/baidu/AnyQ/blob/master/docs/config_tutorial.md#matching

这么配置方式里面就没提到模型导入

**Comment by luluyouyue** [comment]
你好啊，我是用docker环境来编译代码的，请问我怎么make的时候会出现很多错误啊

**Comment by yinweichong** [comment]
SimNet-paddle训出的模型，可直接替换example/conf/simnet/model。
如果使用了语义索引，注意修改example/conf/analysis.conf中的embedding_fetch_name
