### ISSUE TITLE
怎么make的时候会出错啊，是不是一些资源太久远了？

### ISSUE THREAD

**Issue by luluyouyue** [baidu/AnyQ#169]

**Comment by luluyouyue** [comment]
按照这个 操作：https://zhuanlan.zhihu.com/p/55403810

**Comment by yinweichong** [comment]
依赖的库对系统环境有一定要求，推荐使用docker方式安装。
同时，编译时会从github拉相关依赖，对网络也有一定要求，如果是网络问题，建议失败后重新make，会继续编译
