### ISSUE TITLE
运行run_train.sh报段错误

### ISSUE THREAD

**Issue by k0k0xili** [baidu/AnyQ#17]
昨天安装好了AnyQ，在`AnyQ/tools/simnet/train/tf/`目录下运行`sh run_train.sh`脚本，报段错误（吐核），我断点试了下，是在`utils/controler.py:94(c, _= sess.run([loss, optimizer]))`报的。是我操作有问题还是TensorFlow版本问题？

```
Python版本：Python 2.7.13
TensorFlow版本：TensorFlow-CPU 1.8.0
```

**Comment by oyjxer** [comment]
AnyQ中Simnet使用Tensorflow-CPU 1.20开发，您的Tensorflow版本不符

**Comment by k0k0xili** [comment]
确实是TensorFlow版本问题，把版本降到1.2.0后就ok了
