### ISSUE TITLE
生成语义索引库时候，会报错，没有生成semantic.annoy ,语言是英语

### ISSUE THREAD

**Issue by zengsentry** [baidu/AnyQ#170]
生成语义索引库时候，会报错，没有生成semantic.annoy ,语言是英语
AnyQ/build$ ./annoy_index_build_tool example/conf/ example/conf/analysis.conf faq/faq_json.index 128 10 semantic.annoy 1>std 2>err
-----------------------------------------
Segmentation fault (core dumped)

_Originally posted by @dulcan1988 in https://github.com/baidu/AnyQ/issues/111#issuecomment-463936277_

**Comment by yinweichong** [comment]
语义索引需要通用的语义表示模型将文本表示成向量。
当前，anyq开源的是SimNet中文模型，用于表示和相似度计算；
也考虑后续开源英文模型，不过当前还没有具体时间表；
