### ISSUE TITLE
数字大小写的识别问题

### ISSUE THREAD

**Issue by wsj14847** [baidu/AnyQ#173]
如果问答库里是大写数字的描述，但是用户输入或者语音识别结果是小写的数字，两者之间匹配不上。这种问题应该怎么处理比较好？
哪个方案比较好？
1）是由我自己的程序通过命名实体/正则识别出数字，然后转换为大写后再提问；
2）通过改写anyQ实现，具体怎么实现，能提供思路吗？

**Comment by yinweichong** [comment]
1）如果满足应用需求的话（调用方式需要在AnyQ上封装一层），是一种不错的方案；
2）可以实现，需要对AnyQ进行二次开发，在AnyQ中开发问题分析插件，对输入问题进行改写，可参考src/analysis/method_query_intervene.cpp中的AnalysisQueryIntervene；

**Comment by wsj14847** [comment]
十分感谢！
