### ISSUE TITLE
xgboost编译错误求助

### ISSUE THREAD

**Issue by Rbinnnn** [baidu/AnyQ#175]
fatal: 引用不是一个树：e1c8056f6a0ee1c42fd00430b74176e67db66a9f
无法在子模组路径 'rabit' 中检出 'e1c8056f6a0ee1c42fd00430b74176e67db66a9f'
make[2]: *** [third_party/xgboost/src/extern_xgboost-stamp/extern_xgboost-download] 错误 1
make[1]: *** [CMakeFiles/extern_xgboost.dir/all] 错误 2
make: *** [all] 错误 2

**Comment by marsoyang1** [comment]
照着这个修改cmake文件：https://github.com/baidu/AnyQ/pull/116/commits/4c225a0e4309b9a6908ea9afe0ed3f443d5c8166
把*变成rabit

**Comment by Rbinnnn** [comment]
> 照着这个修改cmake文件：[4c225a0](https://github.com/baidu/AnyQ/commit/4c225a0e4309b9a6908ea9afe0ed3f443d5c8166)
> 把*变成rabit

感谢您的恢复，但是这样修改还是报出了同样的错误，我不知道是不是我的操作出了问题。

**Comment by HanwGeek** [comment]
这个是git的问题，请更新git到最新版本。

**Comment by zqqqqq1** [comment]
请问你的问题怎么解决的呢？
