### ISSUE TITLE
编译过程报的xgboost错误， 请问如何解决

### ISSUE THREAD

**Issue by Whitessky** [baidu/AnyQ#178]
![image](https://user-images.githubusercontent.com/21341104/61762141-9df93280-ae03-11e9-807e-0ee7fe640d1b.png)

**Comment by marsoyang1** [comment]
我也遇到这个问题， g++和gcc 4.8.5版本不行，升级到5版本，编译就过了

**Comment by sleavgg** [comment]
可以指定xgboost的版本到0.81 或者 gcc 升级到 4.9.2 ，编译通过
