### ISSUE TITLE
在训练模型时，是否使用了预训练的词嵌入？

### ISSUE THREAD

**Issue by iceman1212** [baidu/AnyQ#18]
如题

**Comment by k0k0xili** [comment]
看了一下layer代码，EmbeddingLayer/EmbeddingWithVSumLayer是重新训练的，但是EmbeddingEnhancedLayer好像可以导入预训练词向量，不知道是否准确

**Comment by oyjxer** [comment]
现阶段Simnet未支持加载预训练词向量的功能

**Comment by k0k0xili** [comment]
EmbeddingEnhancedLayer使用tf.get_variable获取embedding变量，我还以为可以在外部先导入一个name为“embedding”的词向量，然后在EmbeddingEnhancedLayer使用
