### ISSUE TITLE
demo启动solr的命令运行失败

### ISSUE THREAD

**Issue by ljch2018** [baidu/AnyQ#19]
```
sh solr_script/anyq_solr.sh solr_script/sample_docs
```
测试solr启动没有成功，命令为：
```
 curl http://localhost:8900/solr/collection1/schema/fields
```

输出为：
```
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1"/>
<title>Error 404 Not Found</title>
</head>
<body><h2>HTTP ERROR 404</h2>
<p>Problem accessing /solr/collection1/schema/fields. Reason:
<pre>    Not Found</pre></p><hr /><i><small>Powered by Jetty://</small></i><br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                

</body>
</html>
```

**Comment by yinweichong** [comment]
执行以下命令时是否有报错信息，贴下报错信息
```
sh solr_script/anyq_solr.sh solr_script/sample_docs
```
jdk版本要求1.8以上

**Comment by luosmart** [comment]
我的JDK是1.8，以下是起solr服务的日志，好像说JSP类找不到。
```
0    [main] INFO  org.eclipse.jetty.server.Server  – jetty-8.1.10.v20130312
19   [main] INFO  org.eclipse.jetty.deploy.providers.ScanningAppProvider  – Deployment monitor /home/work/jchluo/AnyQ/build/solr-4.10.3-anyq/example/contexts at interval 0
24   [main] INFO  org.eclipse.jetty.deploy.DeploymentManager  – Deployable added: /home/work/jchluo/AnyQ/build/solr-4.10.3-anyq/example/contexts/solr-jetty-context.xml
1115 [main] INFO  org.eclipse.jetty.webapp.StandardDescriptorProcessor  – NO JSP Support for /solr, did not find org.apache.jasper.servlet.JspServlet
1162 [main] INFO  org.apache.solr.servlet.SolrDispatchFilter  – SolrDispatchFilter.init()
1174 [main] INFO  org.apache.solr.core.SolrResourceLoader  – JNDI not configured for solr (NoInitialContextEx)
1174 [main] INFO  org.apache.solr.core.SolrResourceLoader  – solr home defaulted to 'solr/' (could not find system property or JNDI)
1175 [main] INFO  org.apache.solr.core.SolrResourceLoader  – new SolrResourceLoader for directory: 'solr/'
1283 [main] INFO  org.apache.solr.core.ConfigSolr  – Loading container configuration from /home/work/jchluo/AnyQ/build/solr-4.10.3-anyq/example/solr/solr.xml
1346 [main] INFO  org.apache.solr.core.CoresLocator  – Config-defined core root directory: /home/work/jchluo/AnyQ/build/solr-4.10.3-anyq/example/solr
```

**Comment by luosmart** [comment]
@yinweichong  
```
NO JSP Support for /solr, did not find org.apache.jasper.servlet.JspServlet
```

**Comment by zhanghan1992** [comment]
可以重新从官网下载jdk, http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html。
或者从我们暂存的地址下载：
wget http://anyq.bj.bcebos.com/jdk-8u171-linux-x64.tar.gz
解压
tar xzvf jdk-8u171-linux-x64.tar.gz
加到系统路径
export PATH=`pwd`/jdk1.8.0_171/bin:$PATH

**Comment by luosmart** [comment]
@zhanghan1992 我使用了以下的命令：
```
wget http://anyq.bj.bcebos.com/jdk-8u171-linux-x64.tar.gz
解压
tar xzvf jdk-8u171-linux-x64.tar.gz
加到系统路径
export PATH=pwd/jdk1.8.0_171/bin:$PATH
```
但是还是出来一样的问题，仍然NO JSP Support.

**Comment by yinweichong** [comment]
看了下，正常solr启动也会有NO JSP Support，确认下是不是你的目录权限问题
正常启动日志如下
```
0    [main] INFO  org.eclipse.jetty.server.Server  – jetty-8.1.10.v20130312
51   [main] INFO  org.eclipse.jetty.deploy.providers.ScanningAppProvider  – Deployment monitor /AnyQ/build/solr-4.10.3-anyq/example/contexts at interval 0
61   [main] INFO  org.eclipse.jetty.deploy.DeploymentManager  – Deployable added: /AnyQ/build/solr-4.10.3-anyq/example/contexts/solr-jetty-context.xml
1604 [main] INFO  org.eclipse.jetty.webapp.StandardDescriptorProcessor  – NO JSP Support for /solr, did not find org.apache.jasper.servlet.JspServlet
1715 [main] INFO  org.apache.solr.servlet.SolrDispatchFilter  – SolrDispatchFilter.init()
1741 [main] INFO  org.apache.solr.core.SolrResourceLoader  – JNDI not configured for solr (NoInitialContextEx)
1742 [main] INFO  org.apache.solr.core.SolrResourceLoader  – using system property solr.solr.home: ./solr-4.10.3-anyq/example/solr/
1743 [main] INFO  org.apache.solr.core.SolrResourceLoader  – new SolrResourceLoader for directory: './solr-4.10.3-anyq/example/solr/'
1974 [main] INFO  org.apache.solr.core.ConfigSolr  – Loading container configuration from /AnyQ/build/./solr-4.10.3-anyq/example/solr/solr.xml
2096 [main] INFO  org.apache.solr.core.CoresLocator  – Config-defined core root directory: /AnyQ/build/./solr-4.10.3-anyq/example/solr
2108 [main] INFO  org.apache.solr.core.CoreContainer  – New CoreContainer 375457936
2109 [main] INFO  org.apache.solr.core.CoreContainer  – Loading cores into CoreContainer [instanceDir=./solr-4.10.3-anyq/example/solr/]
```

**Comment by SefaZeng** [comment]
你好 我在执行sh solr_script/anyq_solr.sh solr_script/sample_docs的时候报错ValueError: No JSON object could be decoded 请问是什么原因呢 看了一下faq目录下面是有json文件的

**Comment by SefaZeng** [comment]
看了一下好像是读取httperror的时候 报了错

**Comment by yinweichong** [comment]
贴一下详细的报错信息；
anyq-solr依赖jdk1.8+, 可以从官网或者我们暂存的[地址](http://anyq.bj.bcebos.com/jdk-8u171-linux-x64.tar.gz)下载；
anyq-solr的数据操纵依赖python2.7；

**Comment by SefaZeng** [comment]
原始报错信息
`  File "solr_script/solr_api.py", line 24, in <module>
    solr_tools.set_engine_schema(sys.argv[2], sys.argv[3], sys.argv[4], sys.argv[5])
  File "/home/zengxianfeng/AnyQ/tools/solr_script/solr_tools.py", line 117, in set_engine_schema
    _get_error_message(err.read())
  File "/home/zengxianfeng/AnyQ/tools/solr_script/solr_tools.py", line 53, in _get_error_message
    respond_dict = json.loads(respond_str.strip())
  File "/usr/local/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Traceback (most recent call last):
  File "solr_script/solr_api.py", line 30, in <module>
    solr_tools.clear_documents(sys.argv[2], sys.argv[3], sys.argv[4])
  File "/home/zengxianfeng/AnyQ/tools/solr_script/solr_tools.py", line 219, in clear_documents
    _get_error_message(err.read())
  File "/home/zengxianfeng/AnyQ/tools/solr_script/solr_tools.py", line 53, in _get_error_message
    respond_dict = json.loads(respond_str.strip())
  File "/usr/local/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/zengxianfeng/AnyQ/tools/solr_script/solr_tools.py", line 140, in thread_upload
    _get_error_message(err.read())
  File "/home/zengxianfeng/AnyQ/tools/solr_script/solr_tools.py", line 53, in _get_error_message
    respond_dict = json.loads(respond_str.strip())
  File "/usr/local/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
`
把对应代码的json.load的那个err直接打印出来和上面那个@luosmart一样 HTTP ERROR 404
`<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1"/>
<title>Error 404 Not Found</title>
</head>
<body><h2>HTTP ERROR 404</h2>
<p>Problem accessing /solr/collection1/schema/fields. Reason:
<pre>    Not Found</pre></p><hr /><i><small>Powered by Jetty://</small></i><br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
</body>
</html>
`

**Comment by SefaZeng** [comment]
原始报错信息

>   File "solr_script/solr_api.py", line 24, in <module>
    solr_tools.set_engine_schema(sys.argv[2], sys.argv[3], sys.argv[4], sys.argv[5])
  File "/home/zengxianfeng/AnyQ/tools/solr_script/solr_tools.py", line 117, in set_engine_schema
    _get_error_message(err.read())
  File "/home/zengxianfeng/AnyQ/tools/solr_script/solr_tools.py", line 53, in _get_error_message
    respond_dict = json.loads(respond_str.strip())
  File "/usr/local/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Traceback (most recent call last):
  File "solr_script/solr_api.py", line 30, in <module>
    solr_tools.clear_documents(sys.argv[2], sys.argv[3], sys.argv[4])
  File "/home/zengxianfeng/AnyQ/tools/solr_script/solr_tools.py", line 219, in clear_documents
    _get_error_message(err.read())
  File "/home/zengxianfeng/AnyQ/tools/solr_script/solr_tools.py", line 53, in _get_error_message
    respond_dict = json.loads(respond_str.strip())
  File "/usr/local/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/zengxianfeng/AnyQ/tools/solr_script/solr_tools.py", line 140, in thread_upload
    _get_error_message(err.read())
  File "/home/zengxianfeng/AnyQ/tools/solr_script/solr_tools.py", line 53, in _get_error_message
    respond_dict = json.loads(respond_str.strip())
  File "/usr/local/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by SefaZeng** [comment]
把对应代码处的err打印出来和上面的@luosmart一样是HTTP ERROR 404

**Comment by yinweichong** [comment]
看日志是，set_schema失败，是solr启动失败；
ps f -ef | grep solr查看solr是否有进程；
请确认使用的jdk版本1.8+；

**Comment by SefaZeng** [comment]
输入命令显示的内容
> 12303 pts/2    S+     0:00  |           \_ grep solr
 3757 pts/2    Sl     0:10 java -DSTOP.PORT=8901 -DSTOP.KEY=secret_key -Djetty.port=8900 -Dsolr.solr.home=./solr-4.10.3-anyq/example/solr/ -Djetty.home=./solr-4.10.3-anyq/example/ -jar ./solr-4.10.3-anyq/example/start.jar

输入java -version显示的是

> java version "1.8.0_11"
Java(TM) SE Runtime Environment (build 1.8.0_11-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.11-b03, mixed mode)

**Comment by SefaZeng** [comment]
按照上面的步骤做了还是报同样的错 ERROR 404

**Comment by yinweichong** [comment]
看下solr启动过程中是否有ERROR或者WARN之类的日志，在nohup.out里；

ps: 
    如果条件允许的话，可以通过docker使用anyq；

**Comment by SefaZeng** [comment]
或者我可以直接将example里的模型导入然后进行测试吗 我看train里面没有导入模型 只有保存模型

**Comment by yinweichong** [comment]
是想使用anyq提供的语义匹配模型？
example里的模型可以放到simnet里预测，但输入是id，从中文文本需要切词才能转成id，开源的切词可以参考anyq里面的调用方式，或者参考[lac](https://github.com/baidu/lac)的教程

**Comment by SefaZeng** [comment]
导入example李的模型需要自己修改simnet的paddle代码是吗？

**Comment by lullaby-afa** [comment]
> 或者我可以直接将example里的模型导入然后进行测试吗 我看train里面没有导入模型 只有保存模型
请问你的问题解决了吗 我也遇到了同样的问题
