### ISSUE TITLE
cp: cannot stat '/home/AnyQ/build/third_party/lac/src//lac/output/include/*': No such file or directory

### ISSUE THREAD

**Issue by MacXing** [baidu/AnyQ#190]
λ b9af0f159e02 /home/AnyQ/build {master} cmake .. && make
-- Configuring done
-- Generating done
-- Build files have been written to: /home/AnyQ/build
[  4%] Built target extern_leveldb
[  9%] Built target extern_jsoncpp
[ 13%] Built target extern_gtest
[ 18%] Built target extern_xgboost
[ 22%] Built target extern_eigen
[ 26%] Built target extern_paddle
[ 31%] Built target extern_curl
cp: cannot stat '/home/AnyQ/build/third_party/lac/src//lac/output/include/*': No such file or directory
CMakeFiles/extern_lac.dir/build.make:125: recipe for target 'extern_lac' failed
make[2]: *** [extern_lac] Error 1
CMakeFiles/Makefile2:585: recipe for target 'CMakeFiles/extern_lac.dir/all' failed
make[1]: *** [CMakeFiles/extern_lac.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by 385628424** [comment]
解决了吗请问

**Comment by wh211212** [comment]
同求 

同款报错
