### ISSUE TITLE
相似问题及多个候选答案的支持

### ISSUE THREAD

**Issue by wzpan** [baidu/AnyQ#197]
关于 FAQ 的录入，如何针对一个 QA 对，提供同个问题的多种不同用法以及可选的不同答案（随机出）？

例如，问名字的时候可以有多种问法：

* 你叫什么名字
* 你是谁

而回答也可以多样：

* 我是孙悟空！
* 我是花果山水帘洞美猴王齐天大圣孙悟空！

**Comment by wzpan** [comment]
已解决。改下 schema 支持 multiValued 就可以了。

**Comment by shuaiyy** [comment]
> 已解决。改下 schema 支持 multiValued 就可以了。

大佬，在哪里改呀，求指导。
