### ISSUE TITLE
运行demo不成功

### ISSUE THREAD

**Issue by beibeili** [baidu/AnyQ#20]
重新在docker上试了一下，编译通过了，./run_server后是：
I0100 00:00:00.000000    36 dual_dict_wrapper.cpp:26] RAW: config_name: rank_weights
I0100 00:00:00.000000    36 dual_dict_wrapper.cpp:27] RAW: config_type: String2FloatAdapter
I0100 00:00:00.000000    36 dual_dict_wrapper.cpp:28] RAW: config_path: ./rank_weights
I0100 00:00:00.000000    36 dual_dict_wrapper.cpp:50] RAW: dual dict init: rank_weights, reload:false
I0100 00:00:00.000000    36 dual_dict_wrapper.cpp:64] RAW: load dict file:./example/conf/./rank_weights
I0100 00:00:00.000000    36 dual_dict_wrapper.cpp:65] RAW: dict file state: Mon Jul  2 08:40:03 2018

I0100 00:00:00.000000    36 dict_adapter.h:62] RAW: ./example/conf/./rank_weights
I0100 00:00:00.000000    36 utils.cpp:67] RAW: hash load ./example/conf/./rank_weights done
I0100 00:00:00.000000    36 dual_dict_wrapper.cpp:77] RAW: load dict ./example/conf/./rank_weights success
I0100 00:00:00.000000    36 dict_manager.cpp:59] RAW: dict load success: rank_weights
I0100 00:00:00.000000    36 dual_dict_wrapper.cpp:26] RAW: config_name: lac
I0100 00:00:00.000000    36 dual_dict_wrapper.cpp:27] RAW: config_type: WordsegAdapter
I0100 00:00:00.000000    36 dual_dict_wrapper.cpp:28] RAW: config_path: ./wordseg_utf8
I0100 00:00:00.000000    36 dual_dict_wrapper.cpp:50] RAW: dual dict init: lac, reload:false
I0100 00:00:00.000000    36 dual_dict_wrapper.cpp:64] RAW: load dict file:./example/conf/./wordseg_utf8
I0100 00:00:00.000000    36 dual_dict_wrapper.cpp:65] RAW: dict file state: Mon Jul  2 07:25:18 2018

Loaded q2b dic -- num = 172
Loaded strong punc -- num = 5
Loaded word dic -- num(with oov) = 20940
Loaded tag dic -- num = 57
WARNING: Logging before InitGoogleLogging() is written to STDERR
W0805 05:12:33.740880    36 init.cc:85] 'CUDA' is not supported, Please re-compile with WITH_GPU option
W0805 05:12:33.740921    36 init.cc:101] 'CUDA' is not supported, Please re-compile with WITH_GPU option
Loaded customization dic -- num = 0
I0100 00:00:00.000000    36 wordseg_adapter.cpp:36] RAW: wordseg dict load success.
I0100 00:00:00.000000    36 dual_dict_wrapper.cpp:77] RAW: load dict ./example/conf/./wordseg_utf8 success
I0100 00:00:00.000000    36 dict_manager.cpp:59] RAW: dict load success: lac
I0100 00:00:00.000000    36 dual_dict_wrapper.cpp:26] RAW: config_name: fluid_simnet
I0100 00:00:00.000000    36 dual_dict_wrapper.cpp:27] RAW: config_type: PaddleSimAdapter
I0100 00:00:00.000000    36 dual_dict_wrapper.cpp:28] RAW: config_path: ./simnet
I0100 00:00:00.000000    36 dual_dict_wrapper.cpp:50] RAW: dual dict init: fluid_simnet, reload:false
I0100 00:00:00.000000    36 dual_dict_wrapper.cpp:64] RAW: load dict file:./example/conf/./simnet
I0100 00:00:00.000000    36 dual_dict_wrapper.cpp:65] RAW: dict file state: Mon Jul  2 12:32:00 2018

I0100 00:00:00.000000    36 utils.cpp:88] RAW: hash load ./example/conf/./simnet/term2id.dict done
W0805 05:12:34.275743    36 init.cc:85] 'CUDA' is not supported, Please re-compile with WITH_GPU option
W0805 05:12:34.275768    36 init.cc:101] 'CUDA' is not supported, Please re-compile with WITH_GPU option
W0805 05:12:34.275797    36 init.cc:85] 'CUDA' is not supported, Please re-compile with WITH_GPU option
W0805 05:12:34.275807    36 init.cc:101] 'CUDA' is not supported, Please re-compile with WITH_GPU option
I0100 00:00:00.000000    36 paddle_sim_adapter.cpp:66] RAW: paddle model fluid_simnet load success
I0100 00:00:00.000000    36 dual_dict_wrapper.cpp:77] RAW: load dict ./example/conf/./simnet success
I0100 00:00:00.000000    36 dict_manager.cpp:59] RAW: dict load success: fluid_simnet
I0100 00:00:00.000000    36 http_service_impl.cpp:49] RAW: create req preproc plugin default_preproc success
I0100 00:00:00.000000    36 http_service_impl.cpp:63] RAW: create req postproc plugin default_postproc success
I0805 05:12:34.436502    36 server.cpp:975] Server[anyq::HttpServiceImpl] is serving on port=8999.
I0805 05:12:34.437322    36 server.cpp:978] Check out http://9da3a39bb0ef:8999 in web browser.
随后，在浏览器中试了一下：
本地ip:8999/anyq?question=需要使用什么账号登录
得到结果：
![image](https://user-images.githubusercontent.com/16498562/43682875-e05a9d6a-98b2-11e8-9e91-342a3c8abf1f.png)
而后，在docker试了一下（ctrl+p+q退出了容器）：
curl "127.0.0.1:8999/anyq?question=需要使用什么账号登录"
结果还是：curl: (7) Failed to connect to 127.0.0.1 port 8999: Connection refused

**Comment by zhanghan1992** [comment]
外部访问docker容器参考 http://wiki.jikexueyuan.com/project/docker-technology-and-combat/port_mapping.html
