### ISSUE TITLE
请问demo中，你们训练lac词法分析模型使用了多大的数据量？

### ISSUE THREAD

**Issue by iceman1212** [baidu/AnyQ#22]
如题

**Comment by yinweichong** [comment]
使用lac开放的模型，训练数据量约1亿，详询 https://github.com/baidu/lac

**Comment by iceman1212** [comment]
I0806 17:35:23.162390   112 utils.cpp:609] RAW: query:百度分词不是很准，这是为什么？
I0806 17:35:23.162390   112 utils.cpp:611] RAW: tokens_basic size is 6
I0806 17:35:23.162390   112 utils.cpp:614] RAW: tokens_basic	buffer:百度分词	length:12	offset:0	analysis_term_weight:0.166667
I0806 17:35:23.162390   112 utils.cpp:614] RAW: tokens_basic	buffer:不是	length:6	offset:12	analysis_term_weight:0.166667
I0806 17:35:23.162390   112 utils.cpp:614] RAW: tokens_basic	buffer:很准	length:6	offset:18	analysis_term_weight:0.166667
I0806 17:35:23.162390   112 utils.cpp:614] RAW: tokens_basic	buffer:，	length:3	offset:24	analysis_term_weight:0.166667
I0806 17:35:23.162390   112 utils.cpp:614] RAW: tokens_basic	buffer:这是为什么	length:15	offset:27	analysis_term_weight:0.166667
I0806 17:35:23.162390   112 utils.cpp:614] RAW: tokens_basic	buffer:？	length:3	offset:42	analysis_term_weight:0.166667
“百度分词不是很准，这是为什么？” ， “这是为什么”被切在一起了。  1亿的量，效果应该不会这么差。@yinweichong

**Comment by zhanghan1992** [comment]
lac是词法分析，不是单独的分词，相关问题可以在https://github.com/baidu/lac提issue
