### ISSUE TITLE
anyq如何操纵solr 数据接口，实现数据的增删改等操作

### ISSUE THREAD

**Issue by abc668** [baidu/AnyQ#225]
我目前的问答对数据是固定不变的，后期想通过solr实现问答数据的动态加载和更新，请问该如何实现这样的操作。

**Comment by ddocanwol** [comment]
参见博客[AnyQ如何配置solr动态读取数据库——AnyQ系列之二](https://blog.csdn.net/u011818766/article/details/104495543)

**Comment by abc668** [comment]
> 参见博客[AnyQ如何配置solr动态读取数据库——AnyQ系列之二](https://blog.csdn.net/u011818766/article/details/104495543

> 参见博客[AnyQ如何配置solr动态读取数据库——AnyQ系列之二](https://blog.csdn.net/u011818766/article/details/104495543)

**Comment by abc668** [comment]
> 参见博客[AnyQ如何配置solr动态读取数据库——AnyQ系列之二](https://blog.csdn.net/u011818766/article/details/104495543)

非常感谢。
