### ISSUE TITLE
macOS compile error 

### ISSUE THREAD

**Issue by hackerwei** [baidu/AnyQ#27]
[  9%] Built target framework_py_proto_init
paddle/fluid/framework/CMakeFiles/framework_py_proto.dir/build.make:60: *** target pattern contains no `%'.  Stop.
make[4]: *** [paddle/fluid/framework/CMakeFiles/framework_py_proto.dir/all] Error 2
make[4]: *** Waiting for unfinished jobs....
[  9%] Built target profiler_py_proto_init
[ 11%] Built target extern_glog
[ 12%] Built target extern_snappystream
[ 13%] Built target extern_protobuf
make[3]: *** [all] Error 2
make[2]: *** [third_party/paddle/src/extern_paddle-stamp/extern_paddle-build] Error 2
make[1]: *** [CMakeFiles/extern_paddle.dir/all] Error 2

What's wrong ?

Also I can't get "docker run paddlepaddle/paddle:latest-dev" successful, no process is up!

**Comment by zhanghan1992** [comment]
1.报这个错误是因为某些版本cmake编译paddle有问题，建议使用cmake 3.2.2，我们在这个版本上验证过。
2.mac上建议使用docker编译anyq。你的机器上是否安装了docker? 拉镜像的时候报了什么错误？
