### ISSUE TITLE
extern_paddle compile error

### ISSUE THREAD

**Issue by yitian134** [baidu/AnyQ#28]
[编译环境]
Distributor ID:	Debian
Description:	Debian GNU/Linux 8.10 (jessie)
Release:	8.10
Codename:	jessie
[报错信息]
Makefile:105: recipe for target 'all' failed
make[3]: *** [all] Error 2
CMakeFiles/extern_paddle.dir/build.make:111: recipe for target 'third_party/paddle/src/extern_paddle-stamp/extern_paddle-build' failed
make[2]: *** [third_party/paddle/src/extern_paddle-stamp/extern_paddle-build] Error 2
CMakeFiles/Makefile2:590: recipe for target 'CMakeFiles/extern_paddle.dir/all' failed
make[1]: *** [CMakeFiles/extern_paddle.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by zhanghan1992** [comment]
你贴的错误信息不完整。贴一下详细的错误信息。

**Comment by sxjpage** [comment]
我的系统配置：
OS:ubuntu16.04.02.
GPU:GTX1080
Processor:Core i7-5930
Python:Anaconda3-4.2 (3.5.2)
GCC 5.4.0

编译报错：
[  3%] Built target extern_paddle
[  7%] Built target extern_jdk
[  7%] Performing build step for 'extern_bazel'
compile.sh: 35: compile.sh: Syntax error: Bad fd number
CMakeFiles/extern_bazel.dir/build.make:111: recipe for target 'third_party/bazel/src/extern_bazel-stamp/extern_bazel-build' failed
make[2]: *** [third_party/bazel/src/extern_bazel-stamp/extern_bazel-build] Error 2
CMakeFiles/Makefile2:511: recipe for target 'CMakeFiles/extern_bazel.dir/all' failed
make[1]: *** [CMakeFiles/extern_bazel.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by zhanghan1992** [comment]
`
alias sh='bash'
make
`

**Comment by sxjpage** [comment]
谢谢。我通过https://stackoverflow.com/questions/15809060/sh-syntax-error-bad-fd-number这个方法解决问题。不过现在有新的编译错误：
[ 43%] Built target libprotobuf
[ 43%] Building CXX object CMakeFiles/libprotobuf-lite.dir/src/google/protobuf/stubs/status.cc.o
/home/nvidia/PycharmProjects/AnyQ/build/third_party/protobuf/src/extern_protobuf/src/google/protobuf/arena.cc: In member function ‘void google::protobuf::internal::ArenaImpl::Init()’:
/home/nvidia/PycharmProjects/AnyQ/build/third_party/protobuf/src/extern_protobuf/src/google/protobuf/arena.cc:70:48: error: ‘threads_’ was not declared in this scope
   google::protobuf::internal::NoBarrier_Store(&threads_, 0);
                                                ^
/home/nvidia/PycharmProjects/AnyQ/build/third_party/protobuf/src/extern_protobuf/src/google/protobuf/arena.cc:72:7: error: ‘initial_block_’ was not declared in this scope
   if (initial_block_) {
       ^
/home/nvidia/PycharmProjects/AnyQ/build/third_party/protobuf/src/extern_protobuf/src/google/protobuf/arena.cc:76:75: error: ‘InitBlock’ was not declared in this scope
     InitBlock(initial_block_, &thread_cache(), options_.initial_block_size);
                                                                           ^
/home/nvidia/PycharmProjects/AnyQ/build/third_party/protobuf/src/extern_protobuf/src/google/protobuf/arena.cc:77:5: error: ‘ThreadInfo’ was not declared in this scope
     ThreadInfo* info = NewThreadInfo(initial_block_);
     ^
/home/nvidia/PycharmProjects/AnyQ/build/third_party/protobuf/src/extern_protobuf/src/google/protobuf/arena.cc:77:17: error: ‘info’ was not declared in this scope
     ThreadInfo* info = NewThreadInfo(initial_block_);
                 ^
/home/nvidia/PycharmProjects/AnyQ/build/third_party/protobuf/src/extern_protobuf/src/google/protobuf/arena.cc:77:52: error: ‘NewThreadInfo’ was not declared in this scope
     ThreadInfo* info = NewThreadInfo(initial_block_);
                                                    ^
/home/nvidia/PycharmProjects/AnyQ/build/third_party/protobuf/src/extern_protobuf/src/google/protobuf/arena.cc:82:62: error: invalid conversion from ‘google::protobuf::uint64* {aka long unsigned int*}’ to ‘volatile Atomic64* {aka volatile long int*}’ [-fpermissive]
                                   options_.initial_block_size);
                                                              ^
查询后说可能需要打开c++11，但是cmakelist中已经打开了。不知道问题在哪里？
另外我的电脑通过anaconda已经安装了opencv、tensorflow以及配套模块，并能正常使用。
谢谢。

**Comment by smartAndgoodMark** [comment]
我和@sxjpage 有一个相同的错误, 系统是ubuntu16.04.
我参照了你们前面的讨论的方法并没有解决,  直接 make -i
然后./run_server ,  测试了下  127.0.0.1:8999/anyq?question=可以和你唱首歌么 , 返回[]
但其实server报了未知1014错误,具体如下

```

I0823 22:43:43.413375  5685 utils.cpp:590] RAW: in json_to_analysis_item, query:可以和你唱首歌么
I0823 22:43:43.413375  5685 utils.cpp:594] RAW: in json_to_analysis_item, type:(null)
I0823 22:43:43.413375  5685 analysis_strategy.cpp:115] RAW: analysis_analysis size: 1
I0823 22:43:43.413375  5685 analysis_strategy.cpp:130] RAW: before use analysis strategy's analysis_result
I0823 22:43:43.413375  5685 utils.cpp:609] RAW: query:可以和你唱首歌么
I0823 22:43:43.413375  5685 utils.cpp:611] RAW: tokens_basic size is 0
I0823 22:43:43.413375  5685 analysis_strategy.cpp:148] RAW: method_process method_wordseg start
I0823 22:43:43.413375  5685 analysis_strategy.cpp:154] RAW: method_process method_wordseg sucess
I0823 22:43:43.413375  5685 analysis_strategy.cpp:163] RAW: after use analysis strategy's analysis_result
I0823 22:43:43.413375  5685 utils.cpp:609] RAW: query:可以和你唱首歌么
I0823 22:43:43.413375  5685 utils.cpp:611] RAW: tokens_basic size is 6
I0823 22:43:43.413375  5685 utils.cpp:614] RAW: tokens_basic	buffer:可以	length:6	offset:0	analysis_term_weight:0.166667
I0823 22:43:43.413375  5685 utils.cpp:614] RAW: tokens_basic	buffer:和	length:3	offset:6	analysis_term_weight:0.166667
I0823 22:43:43.413375  5685 utils.cpp:614] RAW: tokens_basic	buffer:你	length:3	offset:9	analysis_term_weight:0.166667
I0823 22:43:43.413375  5685 utils.cpp:614] RAW: tokens_basic	buffer:唱	length:3	offset:12	analysis_term_weight:0.166667
I0823 22:43:43.413375  5685 utils.cpp:614] RAW: tokens_basic	buffer:首歌	length:6	offset:15	analysis_term_weight:0.166667
I0823 22:43:43.413375  5685 utils.cpp:614] RAW: tokens_basic	buffer:么	length:3	offset:21	analysis_term_weight:0.166667
I0823 22:43:43.413375  5685 equal_solr_q_builder.cpp:48] RAW: equal solr_fetch_q=question:可以和你唱首歌么
I0823 22:43:43.413375  5685 term_retrieval.cpp:109] RAW: solr_fetch_q=question:可以和你唱首歌么
I0823 22:43:43.413375  5685 term_retrieval.cpp:119] RAW: url = http://127.0.0.1:8900/solr/collection1/select
I0823 22:43:43.413375  5685 http_client.cpp:84] RAW: para_url: fl=id,question,answer&q=question%3A%E5%8F%AF%E4%BB%A5%E5%92%8C%E4%BD%A0%E5%94%B1%E9%A6%96%E6%AD%8C%E4%B9%88&rows=15&wt=json
I0823 22:43:43.413375  5685 term_retrieval.cpp:185] RAW: Term retrieval item id=11, query=我是百度云的老用户，可以使用百度云的AK/SK么？;
I0823 22:43:43.413375  5685 term_retrieval.cpp:185] RAW: Term retrieval item id=9, query=我可以创建多少个应用？;
I0823 22:43:43.413375  5685 term_retrieval.cpp:185] RAW: Term retrieval item id=3, query=AI服务支持推广账号使用么？;
I0823 22:43:43.413375  5685 term_retrieval.cpp:185] RAW: Term retrieval item id=7, query=每个服务的请求配额都是免费的么？;
I0823 22:43:43.413375  5685 term_retrieval.cpp:185] RAW: Term retrieval item id=8, query=每个服务的请求配额有限制么？;
I0823 22:43:43.413375  5685 term_retrieval.cpp:185] RAW: Term retrieval item id=5, query=我以前是百度开发者中心用户，还需要进行开发者认证么？;
I0823 22:43:43.413375  5685 term_retrieval.cpp:187] RAW: keyword retrieval result len=6
I0823 22:43:43.413375  5685 retrieval_strategy.cpp:129] RAW: before rm_dup, retrieval result len=6;
I0823 22:43:43.413375  5685 retrieval_strategy.cpp:132] RAW: after rm_dup retrieval result len=6;
I0823 22:43:43.413375  5685 rank_strategy.cpp:461] RAW: after rough rank, remain 6 cands
I0823 22:43:43.413375  5685 simnet_paddle_sim.cpp:91] RAW: source query:可以和你唱首歌么
I0823 22:43:43.413375  5685 simnet_paddle_sim.cpp:126] RAW: candidate query:我是百度云的老用户，可以使用百度云的AK/SK么？, socre:0.377705
I0823 22:43:43.413375  5685 simnet_paddle_sim.cpp:126] RAW: candidate query:我可以创建多少个应用？, socre:0.336363
I0823 22:43:43.413375  5685 simnet_paddle_sim.cpp:126] RAW: candidate query:AI服务支持推广账号使用么？, socre:0.171606
I0823 22:43:43.413375  5685 simnet_paddle_sim.cpp:126] RAW: candidate query:每个服务的请求配额都是免费的么？, socre:0.129106
I0823 22:43:43.413375  5685 simnet_paddle_sim.cpp:126] RAW: candidate query:每个服务的请求配额有限制么？, socre:0.111133
I0823 22:43:43.413375  5685 simnet_paddle_sim.cpp:126] RAW: candidate query:我以前是百度开发者中心用户，还需要进行开发者认证么？, socre:0.042082
I0823 22:43:43.413375  5685 jaccard_sim.cpp:48] RAW: jaccard = 0.115385
I0823 22:43:43.413375  5685 jaccard_sim.cpp:48] RAW: jaccard = 0.117647
I0823 22:43:43.413375  5685 jaccard_sim.cpp:48] RAW: jaccard = 0.050000
I0823 22:43:43.413375  5685 jaccard_sim.cpp:48] RAW: jaccard = 0.043478
I0823 22:43:43.413375  5685 jaccard_sim.cpp:48] RAW: jaccard = 0.047619
I0823 22:43:43.413375  5685 jaccard_sim.cpp:48] RAW: jaccard = 0.062500
I0823 22:43:43.413375  5685 rank_strategy.cpp:475] RAW: after rank, remain 0 cands
I0823 22:43:43.413375  5685 rank_strategy.cpp:256] RAW: anyq query: 可以和你唱首歌么
I0823 22:43:43.413375  5685 rank_strategy.cpp:257] RAW: output
I0823 22:43:43.413375  5685 anyq_strategy.cpp:77] RAW: input_query=可以和你唱首歌么;analysis_time=3.00ms;retrieval_num=6;retrieval_time=11.00ms;rank_item_num=0;rank_time=24.00ms;
I0823 22:50:48.116031  5685 hotspots_service.cpp:542] 127.0.0.1:51150(no auth) requests for profiling contention for 10 seconds
I0823 22:50:49.951279  5689 hotspots_service.cpp:544] 127.0.0.1:51344(no auth) requests for profiling growth
I0823 22:50:51.129186  5689 hotspots_service.cpp:544] 127.0.0.1:51344(no auth) requests for profiling heap
I0823 22:50:55.248240  5689 hotspots_service.cpp:544] 127.0.0.1:51344(no auth) requests for profiling heap
I0823 22:50:56.797943  5689 hotspots_service.cpp:542] 127.0.0.1:51344(no auth) requests for profiling cpu for 10 seconds
W0823 22:50:58.117848  5685 http_rpc_protocol.cpp:722] Fail to write into fd=8 SocketId=128@127.0.0.1:51150@8999: Unknown error 1014 [1014]
```

**Comment by smartAndgoodMark** [comment]
```
protoc --version
libprotoc 2.6.1
```

**Comment by zhanghan1992** [comment]
@smartAndgoodMark  你已经可以正常运行了。返回结果为空是因为库里没有相关question，检索召回的question得分都低于阈值。你可以改下exmple/conf/rank.cof里的阈值

**Comment by smartAndgoodMark** [comment]
ok

**Comment by ZhangZoffy** [comment]
@smartAndgoodMark 我也用了make -i，但是最后没有生成run_server文件
