### ISSUE TITLE
simnet 有没有训练数据集？

### ISSUE THREAD

**Issue by LongQi** [baidu/AnyQ#29]
simnet 有没有训练数据集？或者其他公开的数据集

**Comment by oyjxer** [comment]
英文数据集可使用quora

**Comment by LongQi** [comment]
中文有数据集吗？

**Comment by LongQi** [comment]
SimNet的训练数据集不是 问答对 吧，而是语义相近的 问题对 吧

**Comment by oyjxer** [comment]
simnet暂不提供中文数据集

**Comment by fanzfeng** [comment]
@oyjxer hello，能否简单描述下demo中提供的训练好的simnet的大概情况：
        ①用于训练的数据集是搜索引擎的query的pair对么，大概的量级是多大啊
        ②训练好之后的测试效果如何，比如p@k多少（希望能得到一个参照标准，谢谢~）

**Comment by oyjxer** [comment]
我们对paddle版本simnet中的bow提供了通用模型，你可以将它作为你的参考标准

**Comment by fanzfeng** [comment]
好的，谢谢~

**Comment by zhangyanbo2007** [comment]
关于anyQ源码细节研读，请加我微信15821444815，一起研究研究！
