### ISSUE TITLE
compile problem

### ISSUE THREAD

**Issue by jc-wang** [baidu/AnyQ#3]
-- Installing: /home/jcwang/AnyQ/build/third_party/install/paddle/third_party/install/protobuf/lib/cmake/protobuf/protobuf-config-version.cmake
-- Installing: /home/jcwang/AnyQ/build/third_party/install/paddle/third_party/install/protobuf/lib/cmake/protobuf/protobuf-module.cmake
-- Installing: /home/jcwang/AnyQ/build/third_party/install/paddle/third_party/install/protobuf/lib/cmake/protobuf/protobuf-config.cmake
[ 15%] Completed 'extern_protobuf'
[ 15%] Built target extern_protobuf
Makefile:105: recipe for target 'all' failed
make[3]: *** [all] Error 2
CMakeFiles/extern_paddle.dir/build.make:111: recipe for target 'third_party/paddle/src/extern_paddle-stamp/extern_paddle-build' failed
make[2]: *** [third_party/paddle/src/extern_paddle-stamp/extern_paddle-build] Error 2
CMakeFiles/Makefile2:511: recipe for target 'CMakeFiles/extern_paddle.dir/all' failed
make[1]: *** [CMakeFiles/extern_paddle.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

I am a newbie in c++, sorry . I can't solve this problem

**Comment by zhanghan1992** [comment]
What are the versions of your gcc and cmake ?  The building log you provided is incomplete. In order for us to see the complete log， you can build with the instrunction 'make 1>stderr.log 2>&1 ',  and send the file 'stderr.log' to zhanghan17@baidu.com. Thank you!
