### ISSUE TITLE
生成语义索引库core dumped

### ISSUE THREAD

**Issue by daiw10** [baidu/AnyQ#30]
生成语义索引库：

./annoy_index_build_tool example/conf/ example/conf/analysis.conf faq/faq_json.index 128 10 semantic.annoy 
跑这句时候出现core dumped 具体信息在下面

./annoy_index_build_tool example/conf/ example/conf/analysis.conf faq/faq_json.index 128 10 semantic.annoy 1>std                                                                       2>err
Segmentation fault (core dumped)
[daiwei@DL2 build]$ ./annoy_index_build_tool example/conf/ example/conf/analysis.conf faq/faq_json.index 128 10 semantic.annoy
I0100 00:00:00.000000 24511 dual_dict_wrapper.cpp:26] RAW: config_name: rank_weights
I0100 00:00:00.000000 24511 dual_dict_wrapper.cpp:27] RAW: config_type: String2FloatAdapter
I0100 00:00:00.000000 24511 dual_dict_wrapper.cpp:28] RAW: config_path: ./rank_weights
I0100 00:00:00.000000 24511 dual_dict_wrapper.cpp:50] RAW: dual dict init: rank_weights, reload:false
I0100 00:00:00.000000 24511 dual_dict_wrapper.cpp:64] RAW: load dict file:example/conf/./rank_weights
I0100 00:00:00.000000 24511 dual_dict_wrapper.cpp:65] RAW: dict file state: Mon Jul  2 16:40:03 2018

I0100 00:00:00.000000 24511 dict_adapter.h:62] RAW: example/conf/./rank_weights
I0100 00:00:00.000000 24511 utils.cpp:67] RAW: hash load example/conf/./rank_weights done
I0100 00:00:00.000000 24511 dual_dict_wrapper.cpp:77] RAW: load dict example/conf/./rank_weights success
I0100 00:00:00.000000 24511 dict_manager.cpp:59] RAW: dict load success: rank_weights
I0100 00:00:00.000000 24511 dual_dict_wrapper.cpp:26] RAW: config_name: lac
I0100 00:00:00.000000 24511 dual_dict_wrapper.cpp:27] RAW: config_type: WordsegAdapter
I0100 00:00:00.000000 24511 dual_dict_wrapper.cpp:28] RAW: config_path: ./wordseg_utf8
I0100 00:00:00.000000 24511 dual_dict_wrapper.cpp:50] RAW: dual dict init: lac, reload:false
I0100 00:00:00.000000 24511 dual_dict_wrapper.cpp:64] RAW: load dict file:example/conf/./wordseg_utf8
I0100 00:00:00.000000 24511 dual_dict_wrapper.cpp:65] RAW: dict file state: Mon Jul  2 15:25:18 2018

Loaded q2b dic -- num = 172
Loaded strong punc -- num = 5
Loaded word dic -- num(with oov) = 20940
Loaded tag dic -- num = 57
WARNING: Logging before InitGoogleLogging() is written to STDERR
W0813 14:28:51.788597 24511 init.cc:85] 'CUDA' is not supported, Please re-compile with WITH_GPU option
W0813 14:28:51.788627 24511 init.cc:101] 'CUDA' is not supported, Please re-compile with WITH_GPU option
Loaded customization dic -- num = 0
I0100 00:00:00.000000 24511 wordseg_adapter.cpp:36] RAW: wordseg dict load success.
I0100 00:00:00.000000 24511 dual_dict_wrapper.cpp:77] RAW: load dict example/conf/./wordseg_utf8 success
I0100 00:00:00.000000 24511 dict_manager.cpp:59] RAW: dict load success: lac
I0100 00:00:00.000000 24511 dual_dict_wrapper.cpp:26] RAW: config_name: fluid_simnet
I0100 00:00:00.000000 24511 dual_dict_wrapper.cpp:27] RAW: config_type: TFModelAdapter
I0100 00:00:00.000000 24511 dual_dict_wrapper.cpp:28] RAW: config_path: ./simnet
E0100 00:00:00.000000 24511 plugin_factory.cpp:28] RAW: create plugin[TFModelAdapter] failed.
E0100 00:00:00.000000 24511 plugin_factory.cpp:28] RAW: create plugin[TFModelAdapter] failed.
E0100 00:00:00.000000 24511 dual_dict_wrapper.cpp:38] RAW: can't find dict_type:TFModelAdapter
I0100 00:00:00.000000 24511 dual_dict_wrapper.cpp:64] RAW: load dict file:example/conf/./simnet
I0100 00:00:00.000000 24511 dual_dict_wrapper.cpp:65] RAW: dict file state: Mon Jul  2 20:32:00 2018

Segmentation fault (core dumped)

请问这个是因为tfmodel failed么，编译选的是ON， 另外这个tool文件是什么呢？  谢谢

**Comment by zhanghan1992** [comment]
(1) 检查下build/third_party/lib/ 下是否有tensorflow的相关lib？如果没有，说明你在cmake的时候tensorflow的编译选项没有写对。
(2)当前AnyQ没有实现基于tensorflow的语义表示插件，如果要用语义检索的话可以编译paddle版本的AnyQ。
(2) tool文件参考 https://github.com/baidu/AnyQ/blob/master/README.md

**Comment by zhdrfirst** [comment]
我也遇到类似的错误，不过我的错误是
 30 I0100 00:00:00.000000 40398 dual_dict_wrapper.cpp:26] RAW: config_name: fluid_simnet                                                                                                  
 31 I0100 00:00:00.000000 40398 dual_dict_wrapper.cpp:27] RAW: config_type: PaddleSimAdapter                                                                                              
 32 I0100 00:00:00.000000 40398 dual_dict_wrapper.cpp:28] RAW: config_path: ./simnet                                                                                                      
 33 E0100 00:00:00.000000 40398 plugin_factory.cpp:28] RAW: create plugin[PaddleSimAdapter] failed.                                                                                       
 34 E0100 00:00:00.000000 40398 plugin_factory.cpp:28] RAW: create plugin[PaddleSimAdapter] failed.                                                                                       
 35 E0100 00:00:00.000000 40398 dual_dict_wrapper.cpp:38] RAW: can't find dict_type:PaddleSimAdapter 

另外build/third_party/lib/ 目录下有libpaddle_fluid.a和libpaddle_fluid.so 两个关于paddle的库

**Comment by zhdrfirst** [comment]
把PaddleSimAdapter换成TFModelAdapter会出现如下错误
I0100 00:00:00.000000 58406 wordseg_adapter.cpp:36] RAW: wordseg dict load success.                                                                                                   
 28 I0100 00:00:00.000000 58406 dual_dict_wrapper.cpp:77] RAW: load dict example/conf/./wordseg_utf8 success                                                                              
 29 I0100 00:00:00.000000 58406 dict_manager.cpp:59] RAW: dict load success: lac                                                                                                          
 30 I0100 00:00:00.000000 58406 dual_dict_wrapper.cpp:26] RAW: config_name: fluid_simnet                                                                                                  
 31 I0100 00:00:00.000000 58406 dual_dict_wrapper.cpp:27] RAW: config_type: TFModelAdapter                                                                                                
 32 I0100 00:00:00.000000 58406 dual_dict_wrapper.cpp:28] RAW: config_path: ./simnet                                                                                                      
 33 I0100 00:00:00.000000 58406 dual_dict_wrapper.cpp:50] RAW: dual dict init: fluid_simnet, reload:false                                                                                 
 34 I0100 00:00:00.000000 58406 dual_dict_wrapper.cpp:64] RAW: load dict file:example/conf/./simnet                                                                                       
 35 I0100 00:00:00.000000 58406 dual_dict_wrapper.cpp:65] RAW: dict file state: Mon Jul  2 20:32:00 2018                                                                                  
 36                                                                                                                                                                                       
 37 E0100 00:00:00.000000 58406 utils.cpp:74] RAW: open dict_file error                                                                                                                   
 38 E0100 00:00:00.000000 58406 tf_model_adapter.cpp:30] RAW: lego term2id dict load error                                                                                                
 39 E0100 00:00:00.000000 58406 dual_dict_wrapper.cpp:74] RAW: load dict example/conf/./simnet error                                                                                      
 40 E0100 00:00:00.000000 58406 dict_manager.cpp:52] RAW: dict load failed: fluid_simnet                                                                                                  
 41 E0100 00:00:00.000000 58406 annoy_index_build.cpp:35] RAW: load dict error                                                                                                            
 42 I0100 00:00:00.000000 58406 dict_manager.cpp:105] RAW: dict release success:lac                                                                                                       
 43 I0100 00:00:00.000000 58406 dict_manager.cpp:105] RAW: dict release success:rank_weights

**Comment by zhanghan1992** [comment]
@zhdrfirst 
create plugin[PaddleSimAdapter] failed原因：
你编译的是tensorflow版本的AnyQ，没有paddle的相关插件。third_party/lib/libpaddle_fluid.so是lac依赖的。如果要用语义检索需要使用paddle版的AnyQ。

**Comment by zhanghan1992** [comment]
@zhdrfirst 
example/conf/simnet下是否放了tensorflow的模型和term2id文件？

**Comment by zhdrfirst** [comment]
目前simnet目录有个term2id.dict文件和model文件夹，按照上面说的，应该是paddle的吧

**Comment by zhdrfirst** [comment]
只能重新编译paddle版本的anyQ，把CMakeLists中的option(USE_TENSORFLOW "use tensorflow rather than paddle" OFF)  么？

**Comment by zhdrfirst** [comment]
annoy_index_build_tool编译源文件是哪个呢

**Comment by zhanghan1992** [comment]
@zhdrfirst 
是的，我们只发布了paddle的simnet模型。
编译paddle版的AnyQ:
```
mkdir build && cmake ../ && make 
```
USE_TENSORFLOW选项的默认值是OFF，不显示指定的话就编译paddle版的AnyQ
