### ISSUE TITLE
训练数据准备问题

### ISSUE THREAD

**Issue by LongQi** [baidu/AnyQ#33]
Pointwise训练及测试数据格式

训练数据格式：训练数据包含三列，依次为Query1的ID序列（ID间使用空格分割），Query2的ID序列（ID间使用空格分割），Label，每列间使用TAB分割，例如；
1 1 1 1 1   2 2 2 2 2   0
1 1 1 1 1   1 1 1 1 1   1
...

**Comment by oyjxer** [comment]
你需要将term序列转化为id序列

**Comment by zide05** [comment]
请问在preprocess中准备数据原始数据是已经分词了的，而这个框架中analysis自带了分词，如何使用这个分词

**Comment by caiyueliang** [comment]
同问
