### ISSUE TITLE
运行run_server报错“error while loading shared libraries: libpaddle_fluid.so: cannot open shared object file: No such file or directory”

### ISSUE THREAD

**Issue by fanzfeng** [baidu/AnyQ#35]
1. 环境： centos+Python 2.7.5
2. ./run_server报错
```
error while loading shared libraries: libpaddle_fluid.so: cannot open shared object file: No such file or directory
```
请教各路大神，如何解决这个问题

**Comment by zhanghan1992** [comment]
ldd run_server
看下run_server指向的libpaddle_fluid.so是否存在

**Comment by fanzfeng** [comment]
果真丢失了很多文件
![image](https://user-images.githubusercontent.com/16243193/44154165-b0cca32c-a0dc-11e8-9bf2-a6666ea36723.png)

**Comment by zhanghan1992** [comment]
试一下 
ls -s anyq代码路径/build/third_party run_server路径
或
cp -r anyq代码路径/build/third_party/lib run_server路径
或export LD_LIBRARY_PATH=anyq代码路径/build/third_party/lib

**Comment by fanzfeng** [comment]
已经可以了，十分谢谢@zhanghan1992
