### ISSUE TITLE
重排序模块增加bm25，计算失败

### ISSUE THREAD

**Issue by fanzfeng** [baidu/AnyQ#37]
为重排序增加bm25相关性计算遇到问题，请教大神们是否操作上有错

### 操作过程
在rank.conf中增加，并修改rank_weignts，启动脚本
```
matching_config {
    name : "bm25_sim"
    type : "BM25Similarity"
    output_num : 1
    rough : false
}
```
### 出错记录
1. 提交查询请求，日志中看到不到bm25的计算结果
2. 运行一段时间后报错，错误如下
```
Segmentation fault
```
![image](https://user-images.githubusercontent.com/16243193/44195572-065b8080-a16c-11e8-97ee-ad619e5d9a23.png)

**Comment by zhanghan1992** [comment]
使用bm25插件需要先在dict.conf中配置String2FloatAdapter类型的term权重字典。
然后在BM25Similarity插件的配置中增加：
`
using_dict_name :  "term权重字典名"
`

**Comment by fanzfeng** [comment]
有些不理解，不是需要一个tf字典和一个idf字典，然后就配置文件而言好像只是制定了数值转换类型（`String2FloatAdapter`），貌似没有指定计算模块/逻辑的参数哦

**Comment by zhanghan1992** [comment]
tf是在输入question/召回question上统计的，不需要配置字典。

**Comment by fanzfeng** [comment]
好的，我直接用灌库全部数据按照配置的lac切词后计算一个idf字典放进去应该OK，多谢及时的解答 @zhanghan1992
