### ISSUE TITLE
./autogen.sh: 11: ./autogen.sh: aclocal: not found

### ISSUE THREAD

**Issue by AIRobotZhang** [baidu/AnyQ#38]
在编译的时候，我遇到了下面的错误：
[  0%] Built target extern_gflags
[  0%] Built target extern_mklml
[  1%] Built target extern_threadpool
[  2%] Performing configure step for 'swig'
[  3%] Built target extern_snappy
[  4%] Built target extern_eigen3
[  4%] Built target extern_zlib
+ test -d Tools/config
+ aclocal -I Tools/config
./autogen.sh: 11: ./autogen.sh: aclocal: not found
[  5%] Built target extern_warpctc
CMakeFiles/swig.dir/build.make:106: recipe for target 'third_party/swig/src/swig-stamp/swig-configure' failed
make[5]: *** [third_party/swig/src/swig-stamp/swig-configure] Error 127
CMakeFiles/Makefile2:370: recipe for target 'CMakeFiles/swig.dir/all' failed
make[4]: *** [CMakeFiles/swig.dir/all] Error 2
make[4]: *** Waiting for unfinished jobs....
[  6%] Built target extern_lib_any
[  7%] Built target extern_boost
[  7%] Built target profiler_py_proto_init
[  7%] Built target framework_py_proto_init
[  8%] Built target extern_glog
[  9%] Built target extern_protobuf
[  9%] Built target extern_snappystream
Makefile:105: recipe for target 'all' failed
make[3]: *** [all] Error 2
CMakeFiles/extern_paddle.dir/build.make:111: recipe for target 'third_party/paddle/src/extern_paddle-stamp/extern_paddle-build' failed
make[2]: *** [third_party/paddle/src/extern_paddle-stamp/extern_paddle-build] Error 2
CMakeFiles/Makefile2:511: recipe for target 'CMakeFiles/extern_paddle.dir/all' failed
make[1]: *** [CMakeFiles/extern_paddle.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by yinweichong** [comment]
参考issue #1

**Comment by AIRobotZhang** [comment]
I have tried that method as follows：
$ pip install automake
Requirement already satisfied: automake in /home/interns/zhangxinghua/y/lib/python3.6/site-packages (0.1.3)
Requirement already satisfied: click in /home/interns/zhangxinghua/y/lib/python3.6/site-packages (from automake) (6.7)
Requirement already satisfied: watchdog in /home/interns/zhangxinghua/y/lib/python3.6/site-packages (from automake) (0.8.3)
Requirement already satisfied: PyYAML>=3.10 in /home/interns/zhangxinghua/y/lib/python3.6/site-packages (from watchdog->automake) (3.12)
Requirement already satisfied: argh>=0.24.1 in /home/interns/zhangxinghua/y/lib/python3.6/site-packages (from watchdog->automake) (0.26.2)
Requirement already satisfied: pathtools>=0.1.1 in /home/interns/zhangxinghua/y/lib/python3.6/site-packages (from watchdog->automake) (0.1.2)

But I got the same errors.

**Comment by zhanghan1992** [comment]
```
#for ubuntu
sudo apt-get install automake
#for centos
sudo yum -y install automake
```

**Comment by AIRobotZhang** [comment]
Thank you!
