### ISSUE TITLE
solr灌库失败

### ISSUE THREAD

**Issue by fanzfeng** [baidu/AnyQ#42]
1. 目标：在不重启solr的情况下，远程更新FAQ set，希望在本地对FAQ set文件做灵活的增删操作。
2. 操作1: delete engine（非SolrCloud模式）：
   - cmd: `curl -X GET -H "Content-Type: application/json" "http://10.11.16.5:8900/solr/admin/cores?wt=json&action=UNLOAD&core=collection1"`
   - return: `{"responseHeader":{"status":0,"QTime":35}}`
3. 操作2：add engine失败后重新把collection1重新load回去
3. clear_doc、upload_doc失败，报错信息如下：
`Traceback (most recent call last):
  File "solr_script/solr_api.py", line 24, in <module>
    solr_tools.set_engine_schema(sys.argv[2], sys.argv[3], sys.argv[4], sys.argv[5])
  File "/data/home/fanzhengfeng/project/AnyQ/demo/solr_script/solr_tools.py", line 117, in set_engine_schema
    _get_error_message(err.read())
  File "/data/home/fanzhengfeng/project/AnyQ/demo/solr_script/solr_tools.py", line 53, in _get_error_message
    respond_dict = json.loads(respond_str.strip())
  File "/data/home/fanzhengfeng/anaconda3/envs/python2/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/data/home/fanzhengfeng/anaconda3/envs/python2/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/data/home/fanzhengfeng/anaconda3/envs/python2/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded`

对solr不熟悉，不知道是哪里出了问题，求帮助

**Comment by yinweichong** [comment]
针对你的目标，不需重启solr，clear_doc 和upload_doc即可

python ${SOLR_API} clear_doc ${ENGINE_HOST} ${ENGINE_NAME} ${SOLR_PORT}

python ${SOLR_API} upload_doc ${ENGINE_HOST} ${ENGINE_NAME} ${SOLR_PORT} ${FAQ_JSON}

参考tools/solr/anyq_solr.sh

**Comment by fanzfeng** [comment]
现在的问题是solr操作不了，不管是clear_doc和upload_doc都会报错，报错结果如上所示，不知道怎么解决

**Comment by yinweichong** [comment]
直接使用anyq的脚本启动会有错误吗，
sh solr_script/anyq_solr.sh solr_script/sample_docs

看报错是在set_engine_schema，有可能是solr启动没有成功，jdk版本是什么，jdk要求1.8+, 可以使用anyq暂存的jdk，[地址](http://anyq.bj.bcebos.com/solr-4.10.3-anyq.tar.gz)

**Comment by fanzfeng** [comment]
直接使用anyq的脚本启动也会有同样的错误，日志上看solr是启动成功的，jdk没问题的（之前一直在用anyq，并非初次使用，只是这次对solr做了正文中的修改发引发的问题），想问下是否可以重置solr的操作呢？
![image](https://user-images.githubusercontent.com/16243193/44667037-511ea780-aa4c-11e8-8693-e906ee42c060.png)

**Comment by yinweichong** [comment]
先把已启动的solr停止再重新运行
```
sh solr_script/anyq_solr.sh solr_script/sample_docs
```
停止solr，通过kill solr的进程号（可以通过ps f -ef | grep solr找到进程号）

如果，依然不行
停止solr，重新下载anyq-solr的package([地址](http://anyq.bj.bcebos.com/solr-4.10.3-anyq.tar.gz))，启动

**Comment by fanzfeng** [comment]
重新下载anyq-solr，问题已解决，谢谢~
