### ISSUE TITLE
测试问题

### ISSUE THREAD

**Issue by beibeili** [baidu/AnyQ#47]
./run_server之后，在浏览器中测试，结果有下面的问题：
I0909 10:45:00.390359    44 method_wordseg.cpp:39] RAW: init wordseg success
I0909 10:45:00.390359    44 analysis_strategy.cpp:74] RAW: create method AnalysisWordseg success
I0909 10:45:00.390359    44 term_retrieval.cpp:77] RAW: create solr q builder equal_solr_q_1 success
I0909 10:45:00.390359    44 retrieval_strategy.cpp:56] RAW: create retrieval plugin term_recall_1 success
I0909 10:45:00.390359    44 wordseg_proc.cpp:33] RAW: init wordseg_feature success
I0909 10:45:00.390359    44 rank_strategy.cpp:100] RAW: create feature wordseg_process success
I0909 10:45:00.390359    44 simnet_paddle_sim.cpp:35] RAW: _output_num:1
I0909 10:45:00.390359    44 rank_strategy.cpp:100] RAW: create feature fluid_simnet_feature success
I0909 10:45:00.390359    44 rank_strategy.cpp:100] RAW: create feature jaccard_sim success
I0909 10:45:00.390359    44 rank_strategy.cpp:63] RAW: create predictor PredictLinearModel success
I0909 10:45:00.390359    44 anyq_strategy.cpp:50] RAW: anyq init success
I0909 10:45:00.390359    44 session_data_factory.cpp:67] RAW: session data init success!!!
I0909 10:45:00.390359    44 utils.cpp:590] RAW: in json_to_analysis_item, query:需要使用什么账号登录
I0909 10:45:00.390359    44 utils.cpp:594] RAW: in json_to_analysis_item, type:(null)
I0909 10:45:00.390359    44 analysis_strategy.cpp:115] RAW: analysis_analysis size: 1
I0909 10:45:00.390359    44 analysis_strategy.cpp:130] RAW: before use analysis strategy's analysis_result
I0909 10:45:00.390359    44 utils.cpp:609] RAW: query:需要使用什么账号登录
I0909 10:45:00.390359    44 utils.cpp:611] RAW: tokens_basic size is 0
I0909 10:45:00.390359    44 analysis_strategy.cpp:148] RAW: method_process method_wordseg start
I0909 10:45:00.390359    44 analysis_strategy.cpp:154] RAW: method_process method_wordseg sucess
I0909 10:45:00.390359    44 analysis_strategy.cpp:163] RAW: after use analysis strategy's analysis_result
I0909 10:45:00.390359    44 utils.cpp:609] RAW: query:需要使用什么账号登录
I0909 10:45:00.390359    44 utils.cpp:611] RAW: tokens_basic size is 5
I0909 10:45:00.390359    44 utils.cpp:614] RAW: tokens_basic    buffer:需要     length:6        offset:0        analysis_term_weight:0.200000
I0909 10:45:00.390359    44 utils.cpp:614] RAW: tokens_basic    buffer:使用     length:6        offset:6        analysis_term_weight:0.200000
I0909 10:45:00.390359    44 utils.cpp:614] RAW: tokens_basic    buffer:什么     length:6        offset:12       analysis_term_weight:0.200000
I0909 10:45:00.390359    44 utils.cpp:614] RAW: tokens_basic    buffer:账号     length:6        offset:18       analysis_term_weight:0.200000
I0909 10:45:00.390359    44 utils.cpp:614] RAW: tokens_basic    buffer:登录     length:6        offset:24       analysis_term_weight:0.200000
I0909 10:45:00.390359    44 equal_solr_q_builder.cpp:48] RAW: equal solr_fetch_q=question:需要使用什么账号登录
I0909 10:45:00.390359    44 term_retrieval.cpp:109] RAW: solr_fetch_q=question:需要使用什么账号登录
I0909 10:45:00.390359    44 term_retrieval.cpp:119] RAW: url = http://127.0.0.1:8900/solr/collection1/select
I0909 10:45:00.390359    44 http_client.cpp:84] RAW: para_url: fl=id,question,answer&q=question%3A%E9%9C%80%E8%A6%81%E4%BD%BF%E7%94%A8%E4%BB%80%E4%B9%88%E8%B4%A6%E5%8F%B7%E7%99%BB%E5%BD%95&rows=15&wt=json
W0909 10:45:00.390359    44 http_client.cpp:94] RAW: curl_easy_perform Failed[Couldn't connect to server];
W0909 10:45:00.390359    44 term_retrieval.cpp:205] RAW: solr_request failed.
E0909 10:45:00.390359    44 retrieval_strategy.cpp:122] RAW: plugin term_recall_1 retrieval error
E0909 10:45:00.390359    44 anyq_strategy.cpp:69] RAW: retrieval module process error
E0909 10:45:00.390359    44 http_service_impl.cpp:133] RAW: anyq run_strategy failed!

这是什么引起的？

**Comment by zhanghan1992** [comment]
是否按照https://github.com/baidu/AnyQ/blob/master/README.md的说明正确运行solr?
'''
# 启动solr, 依赖python-json, jdk>=1.8
cp ../tools/solr -rp solr_script
sh solr_script/anyq_solr.sh solr_script/sample_docs
'''

**Comment by zhanghan1992** [comment]
浏览器问题

**Comment by beibeili** [comment]
需要修改浏览器什么设置吗？edge 和chrome都是这样子。
或者说，什么浏览器可以看到结果？

**Comment by zhanghan1992** [comment]
http://www.cnplugins.com/devtool/jsonview/

**Comment by beibeili** [comment]
好了，十分感谢！
