### ISSUE TITLE
一些问题

### ISSUE THREAD

**Issue by sjm1992st** [baidu/AnyQ#48]
simnet里没看到是否支持从word2vec等初始化向量，另外未登录词的是如何处理的？谢谢

**Comment by yinweichong** [comment]
目前不支持embedding的使用初始化向量，可以参考tf或者paddle的官网教程进行修改添加，我们后续也考虑添加这个功能；
未登录词的处理是数据预处理部分，需要开发者自己处理；

**Comment by sjm1992st** [comment]
我的数据格式如/tools/simnet/preprocess/sample_data格式，用run_preprocess.sh处理了之后，还要运行./tools/tf_record_writer.py 吗？可以直接运行tf_simnet.py了吗？

**Comment by yinweichong** [comment]
```
还要运行./tools/tf_record_writer.py 吗？
```
需要，run_preprocess.sh的结果是id的text形式，使用tf版simnet训练的话，需要转为tf_record的二进制

**Comment by sjm1992st** [comment]
/simnet/preprocess/preprocess.conf/里的partition_ratio = 9:1，这个参数是切分数据集吗？为什么怎么改都是切出10份？

**Comment by oyjxer** [comment]
为了处理大数据，程序会自动将切分得到的trainset和testset分成10个文件，如果需要可以通过运行下述命令将part文件内容合并
cat part-* > all

**Comment by sjm1992st** [comment]
我用preprocess处理的数据运行run_sh.sh是出错，提示tensorflow.python.framework.errors_impl.InvalidArgumentError:indices[0,0]=17 not in [0,3)
我已经把tensorflow的版本弄到1.2.0了

**Comment by snowcement** [comment]
借楼问个和字典相关的问题
1请问example/conf/rank_weights作为字典是如何构建的？第二列权重是如何得出的
2在dict.conf中name==fluid_simnet词典路径为./simnet是指./simnet/term2id.dict词典吗？
3 在dict.conf中name==lac字典路径为./wordseg_utf8是指./wordseg_utf8/word.dict字典吗？

**Comment by zhanghan1992** [comment]
@snowcement 
1. rank_weights可以人工设置也可以通过模型训练得到，开源环境里的是人工设置的。
2. dict_path指的是./simnet/下的模型和字典。
3. 同上
4.  solr/sample_docs是faq库，不是训练预料。模型训练参考https://github.com/baidu/AnyQ/blob/master/tools/simnet/README.md

**Comment by promisejia** [comment]
你好，我想问下，关于pairwise训练simnet时怎么测试？为什么代码给的 “data/test_pairwise_data”中的数据形式和readme中提到的数据形式不一致？readme中提到的数据格式是前面pointwise的测试数据格式

**Comment by sjm1992st** [comment]
我觉得文档里前后的pointwise与pairwise写反了

**Comment by oyjxer** [comment]
test数据格式均为pointwise，readme中有说明 @promisejia

**Comment by promisejia** [comment]
@oyjxer 是的，我看到了readme中大说明是pointwise，但我不解的是 “data/test_pairwise_data”中的数据形式并不是readme中 的pointwise，。我看到用preprocess处理后的数据也是类似 “data/test_pairwise_data”中的加了query_id数据形式，这种形式怎么用？有什么意义吗？

**Comment by sjm1992st** [comment]
examples/pyramid-pointwise.json "train_file": "data/convert_train_point_data" 应该跟示例中一样是data/convert_train_pointwise_data，另外我训练没成功也没报错；提示如下
save model epoch1
INFO:tensorflow:model/pointwise/pyramid.epoch1 is not in all_model_checkpoint_paths. Manually adding it.
INFO:tensorflow:model/pointwise/pyramid.final is not in all_model_checkpoint_paths. Manually adding it.

**Comment by snowcement** [comment]
想问下，在rank/predictor/predict_linear_model.cpp中PredictLinearMoel类初始化时
1 feature_name = ['jaccard_sim']，是从rank.conf中matching_config的name字段获取的，表示相似度计算方法
2 _feature_weight为map，在其中找到feature_name中的特征名就更新_weight[i]
3 _feature_weight通过以DictInterface为基类的子类调用get_dict()方法获得，依据dict.conf中的配置，如果没有使用./rank_weights，比如调用第三方词典，如jieba分词，如何获取以1中以jaccard_sim为键的值，例如jieba分词的默认词典格式为三个字段“词  词频 （可忽略）  词性（可忽略）”或者如果要适配AnyQ，字典格式是什么样的，词典本身为何会包含“相似度计算方法jaccard_sim”这样的关键字？

**Comment by snowcement** [comment]
common_define.h中定义的AnalysisItem结构体中的query_emb定义为vector<float>类型，query针对单词查询语句，tokens_basic为分词详情，想问下query_emb其中保存的是否为词向量，如果为词向量，不是应该每个分词结果均对应一个词向量吗，query_emb类型是否应该为vector<vector<float>>?

**Comment by yinweichong** [comment]
query_emb保存的是整个句子的表示向量（用于语义检索）；
分词结果没有在term2id中，当前的处理逻辑是不保留，可以定制；

**Comment by snowcement** [comment]
@yinweichong 那就是query_emb保存的是整个句子分词后对应的id依次组成的vetor<float>，没有在term2id中的分词跳过，是这样的吧？

**Comment by yinweichong** [comment]
query_emb保存的是整个句子的表示向量，不是token级别的向量；
得到句子表示的过程是，question(输入问题)经过分词之后，利用表示模型(AnalysisSimNetEmb, src/analysis/method_simnet_emb.cpp)进行处理，能够得到整个句子的表示向量，之后可以用于语义检索；

至于你说的，oov(out-of-vocabulary)的问题，当前是跳过，你可以有自己的处理逻辑；

**Comment by yymengmeng** [comment]
您好，solr的FAQ是不是不需要经过训练。直接update_doc就行了？是否需要维护同义词？如何自定义同义词呢？

**Comment by zhanghan1992** [comment]
@yymengmeng 
1. solr是倒排检索，不用训练。
2. 当前没用到同义词的匹配策略。
