### ISSUE TITLE
启动Solr错误，请求示例失败

### ISSUE THREAD

**Issue by snowcement** [baidu/AnyQ#50]
请教两个问题，多谢回答~
错误1 ：
xxx@ubuntu1:~/xx/AnyQ/build$ sh solr_script/anyq_solr.sh solr_script/sample_docs
faq-file trans done
nohup: appending output to 'nohup.out'
solr[8900] start success!
[{'indexed': True, 'name': 'question', 'stored': True, 'type': 'text_multi_lang'}, {'indexed': False, 'name': 'answer', 'stored': True, 'type': 'string'}]
*****[Request Error]: Field 'question' already exists.
b'{"responseHeader":{"status":0,"QTime":11}}\n'
b'{"responseHeader":{"status":0,"QTime":160}}\n'
upload file success

错误2：
浏览器中请求示例输入：http://192.168.1.212:8999/anyq?question=注册百度账户时收不到验证码怎么办？显示结果：
[127.0.1.1:8999]Require ServerOptions.session_local_data_factory to be set!
请问是还需要什么配置吗？

**Comment by zhanghan1992** [comment]
1. solr是否启动了多次？
2. 看下日志里报了什么错？

**Comment by zhanghan1992** [comment]
参考 https://github.com/baidu/AnyQ/blob/master/docs/semantic_retrieval_tutorial.md
