### ISSUE TITLE
./run_server的处理过程

### ISSUE THREAD

**Issue by Sjzwind** [baidu/AnyQ#54]
两个问题：
1. 可以通过什么方式看到run_server的处理过程的源代码吗，这样对于修改会方便些。
例如，用curl返回的是乱码，我想在源代码中修改编码方式，不知道怎么操作

2. 我在sample_doc中增加了几个问答对，然后运行 `sh solr_script/anyq_solr.sh solr_script/sample_docs`来上传数据，这样每次增加了新的问答对都要把所有的数据重新上传一遍吗，还是说可以新建另外的sample_doc，放新的数据来单独上传

感谢解答～～

**Comment by zhanghan1992** [comment]
1. AnyQ内部处理的是utf8编码。如果要用其它编码作为输入、输出，可以在 src/server/anyq_preprocessor.cpp 和 src/server/anyq_postprocessor.cpp中转码。
2. 如果不用语义索引的话，可以直接更新solr:
'''
python solr_script/solr_api.py upload_doc 127.0.0.1 collection1 8900 added_file
'''

**Comment by zhengxusheng** [comment]
上述代码可以只改变IP地址来进行远程访问吗？
