### ISSUE TITLE
Compile Error with analysis_strategy.h include

### ISSUE THREAD

**Issue by yunyin** [baidu/AnyQ#55]
Error is could not find analysis_strategy.h in includes
However, this header file is in includes. Where should I to add this header file.

The error is shown below:
``` /data00/home/labspeech/wupeihao/AnyQ/src/analysis/analysis_strategy.cpp:15:40: fatal error: analysis/analysis_strategy.h: No such file or directory
 #include "analysis/analysis_strategy.h"
                                        ^
compilation terminated.
CMakeFiles/anyq.dir/build.make:62: recipe for target 'CMakeFiles/anyq.dir/src/analysis/analysis_strategy.cpp.o' failed
make[2]: *** [CMakeFiles/anyq.dir/src/analysis/analysis_strategy.cpp.o] Error 1
CMakeFiles/Makefile2:825: recipe for target 'CMakeFiles/anyq.dir/all' failed
make[1]: *** [CMakeFiles/anyq.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by zhanghan1992** [comment]
怎么操作的？

**Comment by jockeyyan** [comment]
貌似是编译到protobuffer出错的，我也出现了类似错误，错误信息如下：
[  9%] Completed 'extern_protobuf'
[  9%] Built target extern_protobuf
Makefile:105: recipe for target 'all' failed
make[3]: *** [all] Error 2

**Comment by jockeyyan** [comment]
cmake version 3.9.1
g++ (Ubuntu 6.4.0-8ubuntu1) 6.4.0 20171010
bison (GNU Bison) 3.0.4

**Comment by jockeyyan** [comment]
确实是不一样的错误，现在的错误主要是：

In file included from /home/jockeyyan/git-repository/QuestionAnsweringBot/AnyQ/build/third_party/paddle/src/extern_paddle/paddle/fluid/framework/channel.h:291:0,
from /home/jockeyyan/git-repository/QuestionAnsweringBot/AnyQ/build/third_party/paddle/src/extern_paddle/paddle/fluid/operators/channel_create_op.cc:15:
/home/jockeyyan/git-repository/QuestionAnsweringBot/AnyQ/build/third_party/paddle/src/extern_paddle/paddle/fluid/framework/channel_impl.h:69:32: error: ‘recursive_mutex’ is not a member of ‘std’
     void Wait(std::unique_lock<std::recursive_mutex> &lock) {
                                ^~~
/home/jockeyyan/git-repository/QuestionAnsweringBot/AnyQ/build/third_party/paddle/src/extern_paddle/paddle/fluid/framework/channel_impl.h:69:32: error: ‘recursive_mutex’ is not a member of ‘std’
/home/jockeyyan/git-repository/QuestionAnsweringBot/AnyQ/build/third_party/paddle/src/extern_paddle/paddle/fluid/framework/channel_impl.h:69:52: error: template argument 1 is invalid
     void Wait(std::unique_lock<std::recursive_mutex> &lock) {
                                                    ^
/home/jockeyyan/git-repository/QuestionAnsweringBot/AnyQ/build/third_party/paddle/src/extern_paddle/paddle/fluid/framework/channel_impl.h:106:8: error: ‘recursive_mutex’ in namespace ‘std’ does not name a type
   std::recursive_mutex mu_;
        ^~~~~~~~~~~~~~~
In file included from /home/jockeyyan/git-repository/QuestionAnsweringBot/AnyQ/build/third_party/paddle/src/extern_paddle/paddle/fluid/framework/channel.h:291:0,
                 from /home/jockeyyan/git-repository/QuestionAnsweringBot/AnyQ/build/third_party/paddle/src/extern_paddle/paddle/fluid/operators/channel_create_op.cc:15:
/home/jockeyyan/git-repository/QuestionAnsweringBot/AnyQ/build/third_party/paddle/src/extern_paddle/paddle/fluid/framework/channel_impl.h: In member function ‘virtual bool paddle::framework::ChannelImpl<T>::CanSend()’:
/home/jockeyyan/git-repository/QuestionAnsweringBot/AnyQ/build/third_party/paddle/src/extern_paddle/paddle/fluid/framework/channel_impl.h:124:19: error: ‘recursive_mutex’ is not a member of ‘std’
   std::lock_guard<std::recursive_mutex> lock{mu_};

**Comment by yunyin** [comment]
@zhanghan1992
好吧= =！那就都用中文了= =！
后面解决了这个问题，虽然是AnyQ的文件，但是如果需要处理的话，每次要重新cmake过

不过现在table_builder.cc:(.text+0x96f): undefined reference to `snappy::MaxCompressedLength(unsigned long)'

我理解是snappy的so包的问题，但是，重新装了，再cmake也没有用。。。

**Comment by jockeyyan** [comment]
在 AnyQ/build/third_party/paddle/src/extern_paddle/paddle/fluid/framework/channel_impl.h 文件里加了一行头文件，编译通过了，不会犯这么低级的错误吧？
> #include \<mutex\>

**Comment by zhanghan1992** [comment]
@jockeyyan paddle在正常情况下可以直接编译通过。可能是gcc版本的问题

**Comment by zhanghan1992** [comment]
@yunyin https://github.com/baidu/AnyQ/issues/10 参考这个issue

**Comment by zhangyanbo2007** [comment]
> @zhanghan1992
> 好吧= =！那就都用中文了= =！
> 后面解决了这个问题，虽然是AnyQ的文件，但是如果需要处理的话，每次要重新cmake过
> 
> 不过现在table_builder.cc:(.text+0x96f): undefined reference to `snappy::MaxCompressedLength(unsigned long)'
> 
> 我理解是snappy的so包的问题，但是，重新装了，再cmake也没有用。。。

你怎么解决的？
