### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by AIRobotZhang** [baidu/AnyQ#56]
![image](https://user-images.githubusercontent.com/20748608/45726580-62de0f80-bbf2-11e8-9942-3e6439bce512.png)

**Comment by AIRobotZhang** [comment]
what's the matter?

**Comment by yinweichong** [comment]
you can try: 
       (1)  update your automake, refer to [issue 1](https://github.com/baidu/AnyQ/issues/1)
       (2)  use python 2.7.*

If it is possible, we strongly recommend using docker to install AnyQ: 
```
docker pull paddlepaddle/paddle:latest-dev
```

**Comment by zhangyanbo2007** [comment]
一起讨论下anyQ,15821444815加我微信吧！
