### ISSUE TITLE
extern_paddle

### ISSUE THREAD

**Issue by AIRobotZhang** [baidu/AnyQ#58]
![image](https://user-images.githubusercontent.com/20748608/45751731-ccd3d480-bc45-11e8-814c-2de73a14aa03.png)
一直卡在这。。。

**Comment by zhanghan1992** [comment]
卡在这里是网络慢的原因

**Comment by AIRobotZhang** [comment]
有什么其他的解决方法吗？

**Comment by darrenwang00** [comment]
同问 extern_paddle 过不去

**Comment by czxie** [comment]
可以用代理先自己git 下载速度慢的包到本地，然后上传到third_party的相应目录下，设置上层的cmake文件的DownLoad command 为空，再重新make就可以了。
网络确实是个大问题，下不来的包我都是这样干的。

**Comment by jllan** [comment]
@czxie 下载extern_paddle卡住了，怎么看extern_paddle的git地址呢？此外如果把extern_paddle 下下来后放到third_party目录下后，设置上层“cmake文件的DownLoad command 为空”是什么意思，怎么操作呢，谢谢

**Comment by czxie** [comment]
@jllan  extern_paddle的cmake文件在 AnyQ-master/cmake/external/paddle.cmake 。
里面有git地址，以及在third_party下面相关设计的具体目录，可以下载放上去就行。
![image](https://user-images.githubusercontent.com/16772869/49350982-45e2b400-f6ec-11e8-9b8c-f4aef7a1288f.png)

DownLoad command是有其他包涉及了，比如tensorflow，如果是自己下载的，得改下DOWNLOAD_COMMAND的参数
![image](https://user-images.githubusercontent.com/16772869/49350959-2fd4f380-f6ec-11e8-8b15-f017ce11344c.png)
