### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by AIRobotZhang** [baidu/AnyQ#59]
![image](https://user-images.githubusercontent.com/20748608/45817207-97e08400-bd10-11e8-97e7-d3d28f66a7fa.png)
What's the matter?

**Comment by zhanghan1992** [comment]
paddle是你自己编译的吗？

**Comment by AIRobotZhang** [comment]
> paddle是你自己编译的吗？

不是啊，按照github上的编译的

**Comment by zhanghan1992** [comment]
看下提示的“framework.pb.h”是什么版本的protobuf生成的？系统里是否安装其它版本的protobuf?

**Comment by AIRobotZhang** [comment]
> 看下提示的“framework.pb.h”是什么版本的protobuf生成的？系统里是否安装其它版本的protobuf?

没有

**Comment by zhanghan1992** [comment]
打开“framework.pb.h”看一下控制版本的宏，截图我看下
