### ISSUE TITLE
recipe for target 'paddle/fluid/operators/math/CMakeFiles/unpooling.dir/unpooling.cc.o' failed

### ISSUE THREAD

**Issue by zhaodongbo** [baidu/AnyQ#61]
Scanning dependencies of target shape_inference
[ 20%] Building CXX object paddle/fluid/framework/CMakeFiles/shape_inference.dir/shape_inference.cc.o
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
paddle/fluid/operators/math/CMakeFiles/unpooling.dir/build.make:62: recipe for target 'paddle/fluid/operators/math/CMakeFiles/unpooling.dir/unpooling.cc.o' failed
make[5]: *** [paddle/fluid/operators/math/CMakeFiles/unpooling.dir/unpooling.cc.o] Error 4
CMakeFiles/Makefile2:20214: recipe for target 'paddle/fluid/operators/math/CMakeFiles/unpooling.dir/all' failed
make[4]: *** [paddle/fluid/operators/math/CMakeFiles/unpooling.dir/all] Error 2
make[4]: *** Waiting for unfinished jobs....
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
paddle/fluid/operators/math/CMakeFiles/blas.dir/build.make:62: recipe for target 'paddle/fluid/operators/math/CMakeFiles/blas.dir/blas.cc.o' failed
make[5]: *** [paddle/fluid/operators/math/CMakeFiles/blas.dir/blas.cc.o] Error 4
CMakeFiles/Makefile2:20318: recipe for target 'paddle/fluid/operators/math/CMakeFiles/blas.dir/all' failed
make[4]: *** [paddle/fluid/operators/math/CMakeFiles/blas.dir/all] Error 2

**Comment by zhanghan1992** [comment]
编译paddle时开了16个线程，可以在cmake/external/paddle.cmake里改下‘make -j16’，减少线程数。

**Comment by zhaodongbo** [comment]
我试试，谢谢
