### ISSUE TITLE
为什么用session_data_factory，而不直接用全局变量呢？

### ISSUE THREAD

**Issue by yitian134** [baidu/AnyQ#62]
文件：include/server/session_data_factory.h
thread-local 共享的这个 SessionDataFactory 应该不会被修改吧？疑问是为什么用thread-local而不直接用全局变量呢，考虑是什么？

**Comment by yinweichong** [comment]
HttpServer中的session_data_factory是进程级的对象，是session_data的工厂，主要目的是通过其CreateData函数创建线程资源；
