### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by husttsq** [baidu/AnyQ#63]
你好，在docker子机中编译报错，可以帮忙看看吗
 /AnyQ/build {master} make
[  4%] Built target extern_leveldb
[  9%] Built target extern_jsoncpp
[ 13%] Built target extern_gtest
[ 13%] Performing install step for 'extern_xgboost'
Makefile:31: MAKE [make] - checked OK
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
Makefile:141: recipe for target 'build/predictor/predictor.o' failed
make[3]: *** [build/predictor/predictor.o] Error 4
make[3]: *** Waiting for unfinished jobs....
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
In file included from src/objective/hinge.cu:9:0,
                 from src/objective/hinge.cc:17:
src/objective/../common/transform.h: In instantiation of ‘xgboost::common::Transform<CompiledWithCuda>::Evaluator<Functor>::Evaluator(Functor, xgboost::common::Range, xgboost::GPUSet, bool) [with Functor = xgboost::obj::HingeObj::GetGradient(const xgboost::HostDeviceVector<float>&, const xgboost::MetaInfo&, int, xgboost::HostDeviceVector<xgboost::detail::GradientPairInternal<float> >*)::<lambda(size_t, xgboost::common::Span<int, -1l>, xgboost::common::Span<xgboost::detail::GradientPairInternal<float>, -1l>, xgboost::common::Span<const float, -1l>, xgboost::common::Span<const float, -1l>, xgboost::common::Span<const float, -1l>)>; bool CompiledWithCuda = false]’:
src/objective/../common/transform.h:191:83:   required from ‘static xgboost::common::Transform<CompiledWithCuda>::Evaluator<Functor> xgboost::common::Transform<CompiledWithCuda>::Init(Functor, xgboost::common::Range, xgboost::GPUSet, bool) [with Functor = xgboost::obj::HingeObj::GetGradient(const xgboost::HostDeviceVector<float>&, const xgboost::MetaInfo&, int, xgboost::HostDeviceVector<xgboost::detail::GradientPairInternal<float> >*)::<lambda(size_t, xgboost::common::Span<int, -1l>, xgboost::common::Span<xgboost::detail::GradientPairInternal<float>, -1l>, xgboost::common::Span<const float, -1l>, xgboost::common::Span<const float, -1l>, xgboost::common::Span<const float, -1l>)>; bool CompiledWithCuda = false]’
src/objective/hinge.cu:78:64:   required from here
src/objective/../common/transform.h:170:21: warning: ‘xgboost::common::Transform<>::Evaluator<xgboost::obj::HingeObj::GetGradient(const xgboost::HostDeviceVector<float>&, const xgboost::MetaInfo&, int, xgboost::HostDeviceVector<xgboost::detail::GradientPairInternal<float> >*)::<lambda(size_t, xgboost::common::Span<int, -1l>, xgboost::common::Span<xgboost::detail::GradientPairInternal<float>, -1l>, xgboost::common::Span<const float, -1l>, xgboost::common::Span<const float, -1l>, xgboost::common::Span<const float, -1l>)> >::distribution_’ will be initialized after [-Wreorder]
     GPUDistribution distribution_;
                     ^
src/objective/../common/transform.h:169:10: warning:   ‘bool xgboost::common::Transform<>::Evaluator<xgboost::obj::HingeObj::GetGradient(const xgboost::HostDeviceVector<float>&, const xgboost::MetaInfo&, int, xgboost::HostDeviceVector<xgboost::detail::GradientPairInternal<float> >*)::<lambda(size_t, xgboost::common::Span<int, -1l>, xgboost::common::Span<xgboost::detail::GradientPairInternal<float>, -1l>, xgboost::common::Span<const float, -1l>, xgboost::common::Span<const float, -1l>, xgboost::common::Span<const float, -1l>)> >::reshard_’ [-Wreorder]
     bool reshard_;
          ^
src/objective/../common/transform.h:59:5: warning:   when initialized here [-Wreorder]
     Evaluator(Functor func, Range range, GPUSet devices, bool reshard) :
     ^
src/objective/../common/transform.h: In instantiation of ‘void xgboost::common::Transform<CompiledWithCuda>::Evaluator<Functor>::LaunchCPU(Functor, HDV* ...) const [with HDV = {xgboost::HostDeviceVector<int>, xgboost::HostDeviceVector<xgboost::detail::GradientPairInternal<float> >, const xgboost::HostDeviceVector<float>, const xgboost::HostDeviceVector<float>, const xgboost::HostDeviceVector<float>}; Functor = xgboost::obj::HingeObj::GetGradient(const xgboost::HostDeviceVector<float>&, const xgboost::MetaInfo&, int, xgboost::HostDeviceVector<xgboost::detail::GradientPairInternal<float> >*)::<lambda(size_t, xgboost::common::Span<int, -1l>, xgboost::common::Span<xgboost::detail::GradientPairInternal<float>, -1l>, xgboost::common::Span<const float, -1l>, xgboost::common::Span<const float, -1l>, xgboost::common::Span<const float, -1l>)>; bool CompiledWithCuda = false]’:
src/objective/../common/transform.h:81:18:   required from ‘void xgboost::common::Transform<CompiledWithCuda>::Evaluator<Functor>::Eval(HDV ...) const [with HDV = {xgboost::HostDeviceVector<int>*, xgboost::HostDeviceVector<xgboost::detail::GradientPairInternal<float> >*, const xgboost::HostDeviceVector<float>*, const xgboost::HostDeviceVector<float>*, const xgboost::HostDeviceVector<float>*}; Functor = xgboost::obj::HingeObj::GetGradient(const xgboost::HostDeviceVector<float>&, const xgboost::MetaInfo&, int, xgboost::HostDeviceVector<xgboost::detail::GradientPairInternal<float> >*)::<lambda(size_t, xgboost::common::Span<int, -1l>, xgboost::common::Span<xgboost::detail::GradientPairInternal<float>, -1l>, xgboost::common::Span<const float, -1l>, xgboost::common::Span<const float,-1l>, xgboost::common::Span<const float, -1l>)>; bool CompiledWithCuda = false]’
src/objective/hinge.cu:79:78:   required from here
src/objective/../common/transform.h:158:7: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       for (omp_ulong idx = 0; idx < end; ++idx) {
       ^
src/objective/../common/transform.h: In instantiation of ‘xgboost::common::Transform<CompiledWithCuda>::Evaluator<Functor>::Evaluator(Functor, xgboost::common::Range, xgboost::GPUSet, bool) [with Functor = xgboost::obj::HingeObj::PredTransform(xgboost::HostDeviceVector<float>*)::<lambda(size_t, xgboost::common::Span<float, -1l>)>; bool CompiledWithCuda = false]’:
src/objective/../common/transform.h:191:83:   required from ‘static xgboost::common::Transform<CompiledWithCuda>::Evaluator<Functor> xgboost::common::Transform<CompiledWithCuda>::Init(Functor, xgboost::common::Range, xgboost::GPUSet, bool) [with Functor = xgboost::obj::HingeObj::PredTransform(xgboost::HostDeviceVector<float>*)::<lambda(size_t, xgboost::common::Span<float, -1l>)>; bool CompiledWithCuda = false]’
src/objective/hinge.cu:87:78:   required from here
src/objective/../common/transform.h:170:21: warning: ‘xgboost::common::Transform<>::Evaluator<xgboost::obj::HingeObj::PredTransform(xgboost::HostDeviceVector<float>*)::<lambda(size_t, xgboost::common::Span<float, -1l>)> >::distribution_’ will be initialized after [-Wreorder]
     GPUDistribution distribution_;
                     ^
src/objective/../common/transform.h:169:10: warning:   ‘bool xgboost::common::Transform<>::Evaluator<xgboost::obj::HingeObj::PredTransform(xgboost::HostDeviceVector<float>*)::<lambda(size_t, xgboost::common::Span<float, -1l>)> >::reshard_’ [-Wreorder]
     bool reshard_;
          ^
src/objective/../common/transform.h:59:5: warning:   when initialized here [-Wreorder]
     Evaluator(Functor func, Range range, GPUSet devices, bool reshard) :
     ^

src/objective/../common/transform.h: In instantiation of ‘void xgboost::common::Transform<CompiledWithCuda>::Evaluator<Functor>::LaunchCPU(Functor, HDV* ...) const [with HDV = {xgboost::HostDeviceVector<float>}; Functor = xgboost::obj::HingeObj::PredTransform(xgboost::HostDeviceVector<float>*)::<lambda(size_t, xgboost::common::Span<float, -1l>)>; bool CompiledWithCuda = false]’:
src/objective/../common/transform.h:81:18:   required from ‘void xgboost::common::Transform<CompiledWithCuda>::Evaluator<Functor>::Eval(HDV ...) const [with HDV = {xgboost::HostDeviceVector<float>*}; Functor = xgboost::obj::HingeObj::PredTransform(xgboost::HostDeviceVector<float>*)::<lambda(size_t, xgboost::common::Span<float, -1l>)>; bool CompiledWithCuda = false]’
src/objective/hinge.cu:88:23:   required from here
src/objective/../common/transform.h:158:7: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       for (omp_ulong idx = 0; idx < end; ++idx) {
       ^
Makefile:141: recipe for target 'build/metric/rank_metric.o' failed
make[3]: *** [build/metric/rank_metric.o] Error 4
CMakeFiles/extern_xgboost.dir/build.make:73: recipe for target 'third_party/xgboost/src/extern_xgboost-stamp/extern_xgboost-install' failed
make[2]: *** [third_party/xgboost/src/extern_xgboost-stamp/extern_xgboost-install] Error 2
CMakeFiles/Makefile2:363: recipe for target 'CMakeFiles/extern_xgboost.dir/all' failed
make[1]: *** [CMakeFiles/extern_xgboost.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by zhanghan1992** [comment]
参考https://github.com/baidu/AnyQ/issues/61，减少paddle和xgboost的编译线程数
