### ISSUE TITLE
关于语义retrieval和语义matching的模型

### ISSUE THREAD

**Issue by tony-j-shao** [baidu/AnyQ#65]
您好，在使用框架的时候有一些问题：

1、关于基于语义构建的检索索引，想问一下是怎样构成关于问题嵌入向量的，因为看见参数设置里有dim的选项；

2、关于基于语义匹配，计算出score的模型是什么，是否能够根据simnet中的模型自己训练以后替换原来的模型吗。

**Comment by zhanghan1992** [comment]
1.  问题的向量表示可以参考AnalysisSimNetEmb插件。
2. 目前放出的匹配模型是bow，可以自己训练模型替换。simnet训练可参考https://github.com/baidu/AnyQ/tree/master/tools/simnet

**Comment by tony-j-shao** [comment]
感谢回答，

1. 不好意思，我去查看了关于该插件cpp源代码不是很明白原理，就是想问一下是如何生成问题向量表示，比如是基于预训练模型的嵌入词向量连接生成还是什么样子的，有一些困惑，因为有个dim的参数可以随意设定整数；
2. 我已经完成了tf训练，生成的variable储存在ckpt，想问一下如何将我的graph和ckpt储存的变量替换进框架，请问框架是用C++代码直接调用预先训练好的模型的吗？

**Comment by tony-j-shao** [comment]
感谢回答，

1. 我通过tf训练模型，freeze生成了tf.grapgh和term2id，存放在/simnet/tensorflow中，dict_配置如下：
        dict_config{
            name: "tf_simnet"
            type: "TFModelAdapter"
            path: "./simnet/tensorflow"
        }
        但是在一开始的配置字典时候就出错了：
        RAW: create plugin[TFModelAdapter] failed.

2.关于在matching中运用tf语义，请问具体在rank.conf配置的格式是怎样的：发现有三个参数：
        left_input_name, right_input_name, output_name
        请问是指tf图中的输入和输出节点对吗，输出节点就是最后二分类的pred的变量名"BiasAdd_4"，但是输         入的话看见代码用的是输入是通过queue不是placeholder，这个要填什么变量名呢？

3.关于solr关键字检索的问题，脚本(contain_solr_q_builder.cpp)里面发现要设置黑白词(include/exclude term字典)，想问一下这个是要怎么配置的，因为现在调用的话初始没有设置该字典，solr_fetch_q得到的是空的。

**Comment by zide05** [comment]
@tony-j-shao 请问怎么freeze生成tf.gragh和term2id？

**Comment by zhangyanbo2007** [comment]
关于anyQ源码细节研读，请加我微信15821444815，一起研究研究！

**Comment by qujinqiang** [comment]
@oyjxer  tf版的simnet， 没有实际的python版的预测代码吗？在线急等
