### ISSUE TITLE
realpath: command not found

### ISSUE THREAD

**Issue by lingdavid** [baidu/AnyQ#66]
config_brpc.sh: line 32: realpath: command not found
config_brpc.sh: line 33: realpath: command not found
config_brpc: --headers=HDRPATHS --libs=LIBPATHS must be specified
make[2]: *** [third_party/brpc/src/extern_brpc-stamp/extern_brpc-install] Error 1
make[1]: *** [CMakeFiles/extern_brpc.dir/all] Error 2
make: *** [all] Error 2
请问这怎么解决呢

**Comment by dengwb1973** [comment]
@lingdavid 请问这个问题解决了吗？我也遇到了。帮忙解答一下
