### ISSUE TITLE
gcc的版本

### ISSUE THREAD

**Issue by lingdavid** [baidu/AnyQ#67]
[ 39%] Built target proto_build
[ 43%] Built target extern_leveldb
[ 47%] Built target extern_glog
[ 52%] Built target extern_gflags
[ 57%] Built target extern_openssl
[ 61%] Built target extern_brpc
[ 65%] Built target extern_eigen
[ 66%] Performing build step for 'extern_lac'
-- CXX compiler: /usr/bin/c++, version: GNU 4.8.4
-- C compiler: /usr/bin/cc, version: GNU 4.8.4
CMake Error at CMakeLists.txt:12 (message):
  A gcc compiler with a version >= 4.8.2 is needed.

-- Configuring incomplete, errors occurred!
See also "/home/ldw/work/Chat_QA/AnyQ-master/build/third_party/lac/src/lac/CMakeFiles/CMakeOutput.log".
make[2]: *** [third_party/lac/src/extern_lac-stamp/extern_lac-build] Error 1
make[1]: *** [CMakeFiles/extern_lac.dir/all] Error 2
make: *** [all] Error 2
请问这里的gcc版本不是4.8.4，大于4.8.2吗，为什么还会报错？

**Comment by caistrong** [comment]
同样的问题

**Comment by caistrong** [comment]
[ubuntu16.04系统gcc下降和升级](https://blog.csdn.net/betty13006159467/article/details/78394974)

将gcc版本升级为5.4.1后解决了问题
