### ISSUE TITLE
请问如何对多个问答文件分别建立一个AnyQ实例？

### ISSUE THREAD

**Issue by meiwhu** [baidu/AnyQ#69]
请问如何对**多个**问答文件**分别**建立一个AnyQ实例？

**Comment by zhanghan1992** [comment]
是要对多个库起一个服务吗？

**Comment by meiwhu** [comment]
是的，就是要开放多个服务，每个服务对应一个问答文件，可以分别请求各个服务获得不同文件的问答结果。

**Comment by meiwhu** [comment]
谢谢。
1. 是`/build/faq/faq_json`这个文件吗？`/build/faq/schema_format`要不要改？
2. 这种做法其实还是只有一个服务，只是用faq_id分开了吗？如果修改某个问答文件，还需要全部重新`upload_doc`对吧？
3. 我想要的是分开的服务，某一个问答文件变更后最好能不影响其他的服务。开始想的是用docker建立多个容器，不过这样有点浪费资源了，想知道有没有什么好办法？

**Comment by zhanghan1992** [comment]
1. /build/faq/schema_format不用改
2.可以参考https://github.com/baidu/AnyQ/tree/master/tools/solr下的python脚本，对solr库进行类似数据库的操作。

**Comment by zhanghan1992** [comment]
https://host:port/solr/collection1/update?stream.body=<delete><query>faq_id:XXX</query></delete>&commit=true

**Comment by zhanghan1992** [comment]
https://host:port/solr/collection1/update?stream.body=<delete><query>faq_id:XXX</query></delete>&commit=true

**Comment by zhanghan1992** [comment]
```
https://host:port/solr/collection1/update?stream.body=<delete><query>faq_id:XXX</query></delete>&commit=true
```

**Comment by meiwhu** [comment]
谢谢😀
