### ISSUE TITLE
simnet训练问题

### ISSUE THREAD

**Issue by DoYHang** [baidu/AnyQ#71]
save model epoch1
INFO:tensorflow:model/pointwise/cnn.epoch1 is not in all_model_checkpoint_paths. Manually adding it.
INFO:tensorflow:model/pointwise/cnn.final is not in all_model_checkpoint_paths. Manually adding it.

**Comment by yinweichong** [comment]
这是TF的INFO，不是error

**Comment by zide05** [comment]
训练好数据之后怎么放到server的model中更新server？训练保存的时tensorflow的checkpoint文件们，但是在build/example/conf/simnet/model中时emb,__model__ , tah.w, tah.b这种的 应该怎么替换？

**Comment by zhangyanbo2007** [comment]
关于anyQ源码细节研读，请加我微信15821444815，一起研究研究！
