### ISSUE TITLE
如何修改端口和输出的格式

### ISSUE THREAD

**Issue by lingdavid** [baidu/AnyQ#72]
端口号和输出格式在哪个文件修改呢

**Comment by zhanghan1992** [comment]
端口号在./example/conf/anyq_brpc.conf中修改，输出格式修改需要自己实现后处理插件,参考https://github.com/baidu/AnyQ/blob/master/src/server/anyq_postprocessor.cpp

**Comment by lingdavid** [comment]
好的，谢谢

**Comment by zhengxusheng** [comment]
请问如何设置web界面IP地址进行远程访问？
