### ISSUE TITLE
faq_json文件

### ISSUE THREAD

**Issue by lingdavid** [baidu/AnyQ#75]
faq_json这个文件里面的json字符串，里面的属性id会在后面的代码里面用到吗？为什么我修改了这个id的值为其他的值（不再是1,2,3,4......），服务启动后，查询出来的结果和没修改前的不一样，不正确了

**Comment by yinweichong** [comment]
这个id是问答id，AnyQ的结果中会返回(即qa_id)；
如果FAQ文件提供了，后续沿用，如果未提供（示例中的sample_docs)，系统会自动编号；
