### ISSUE TITLE
Matching 模块也会输出得分，不能用于排序吗？Re-Ranking模块的意义是什么？

### ISSUE THREAD

**Issue by bifeng** [baidu/AnyQ#77]
不是很明白，希望能够指点一二

**Comment by yinweichong** [comment]
matching模块，可以使用各种相似度策略进行打分，包括基于DNN的SimNet，以及直接字面的相似度；
Re-Rank模块，综合所有这些相似度特征（线性模型、树模型、DNN），给出最终的打分。

**Comment by bifeng** [comment]
👍   谢谢！

**Comment by hongshengxin** [comment]
请问Re-ranking模块是怎么实现的呢?
