### ISSUE TITLE
使用docker环境编译错误

### ISSUE THREAD

**Issue by wang2222qq** [baidu/AnyQ#78]
使用docker pull docker.paddlepaddlehub.com/paddle 镜像。
直接按照教程cmake && make.
然后在make 的时候一直过不去。请问这个是什么原因？如何解决
```
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
paddle/fluid/operators/CMakeFiles/activation_op.dir/build.make:62: recipe for target 'paddle/fluid/operators/CMakeFiles/activation_op.dir/activation_op.cc.o' failed
make[5]: *** [paddle/fluid/operators/CMakeFiles/activation_op.dir/activation_op.cc.o] Error 4
CMakeFiles/Makefile2:7430: recipe for target 'paddle/fluid/operators/CMakeFiles/activation_op.dir/all' failed
make[4]: *** [paddle/fluid/operators/CMakeFiles/activation_op.dir/all] Error 2
make[4]: *** Waiting for unfinished jobs....
[ 44%] Linking CXX static library librow_conv_op.a
[ 44%] Built target row_conv_op
[ 44%] Linking CXX static library libfake_dequantize_op.a
[ 44%] Built target fake_dequantize_op
[ 44%] Linking CXX static library libsgd_op.a
[ 44%] Built target sgd_op
[ 44%] Linking CXX static library libload_op.a
[ 44%] Built target load_op
[ 44%] Linking CXX static library libdelete_var_op.a
[ 44%] Built target delete_var_op
[ 45%] Linking CXX static library libbeam_search_op.a
[ 45%] Built target beam_search_op
[ 45%] Linking CXX static library libconcat_op.a
[ 45%] Built target concat_op
[ 45%] Linking CXX static library libpool_with_index_op.a
[ 45%] Built target pool_with_index_op
[ 45%] Linking CXX static library librandom_crop_op.a
[ 45%] Built target random_crop_op
[ 45%] Linking CXX static library liblayer_norm_op.a
[ 45%] Linking CXX static library libsequence_reshape_op.a
[ 45%] Built target layer_norm_op
[ 45%] Built target sequence_reshape_op
[ 45%] Linking CXX static library libincrement_op.a
[ 45%] Built target increment_op
[ 45%] Linking CXX static library libpool_op.a
[ 45%] Built target pool_op
[ 45%] Linking CXX static library liblstm_op.a
[ 45%] Built target lstm_op
[ 45%] Linking CXX static library libreduce_min_op.a
[ 45%] Built target reduce_min_op
Makefile:105: recipe for target 'all' failed
make[3]: *** [all] Error 2
CMakeFiles/extern_paddle.dir/build.make:111: recipe for target 'third_party/paddle/src/extern_paddle-stamp/extern_paddle-build' failed
make[2]: *** [third_party/paddle/src/extern_paddle-stamp/extern_paddle-build] Error 2
CMakeFiles/Makefile2:511: recipe for target 'CMakeFiles/extern_paddle.dir/all' failed
make[1]: *** [CMakeFiles/extern_paddle.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by zhanghan1992** [comment]
参考 https://github.com/baidu/AnyQ/issues/61
减少paddle和xgboost的编译线程数

**Comment by wang2222qq** [comment]
修改了paddle和xgboost之后，出现了新的错误
`[dpsuser@Jmgo前置机 build]$ make
[  4%] Built target extern_zlib
[  8%] Built target extern_protobuf
[libprotobuf WARNING /home/dpsuser/AnyQ/build/third_party/protobuf/src/extern_protobuf/src/google/protobuf/compiler/parser.cc:546] No syntax specified for the proto file: anyq.proto. Please use 'syntax = "proto2";' or 'syntax = "proto3";' to specify a syntax version. (Defaulted to proto2 syntax.)
[libprotobuf WARNING /home/dpsuser/AnyQ/build/third_party/protobuf/src/extern_protobuf/src/google/protobuf/compiler/parser.cc:546] No syntax specified for the proto file: http_service.proto. Please use 'syntax = "proto2";' or 'syntax = "proto3";' to specify a syntax version. (Defaulted to proto2 syntax.)
[ 12%] Built target proto_build
[ 16%] Built target extern_gtest
[ 20%] Built target extern_eigen
[ 25%] Built target extern_xgboost
[ 30%] Built target extern_curl
[ 34%] Built target extern_boost
[ 38%] Built target extern_leveldb
[ 42%] Built target extern_glog
[ 47%] Built target extern_openssl
[ 52%] Built target extern_gflags
[ 52%] Performing install step for 'extern_brpc'
config_brpc.sh: line 32: realpath: command not found
config_brpc.sh: line 33: realpath: command not found
config_brpc: --headers=HDRPATHS --libs=LIBPATHS must be specified
make[2]: *** [third_party/brpc/src/extern_brpc-stamp/extern_brpc-install] Error 1
make[1]: *** [CMakeFiles/extern_brpc.dir/all] Error 2
make: *** [all] Error 2`

**Comment by wang2222qq** [comment]
已解决问题：处在  realpath的命名不存在。
个人环境: CentOS6.5
解决方式：
 `yum install coreutils
 echo '/usr/bin/readlink -e "$@"' > /usr/local/bin/realpath ;
chmod +x /usr/local/bin/realpath`
