### ISSUE TITLE
请教各位，安装编译报错

### ISSUE THREAD

**Issue by jpgaus** [baidu/AnyQ#79]
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://bugzilla.redhat.com/bugzilla> for instructions.
CMakeFiles/libprotobuf.dir/build.make:758: recipe for target 'CMakeFiles/libprotobuf.dir/src/google/protobuf/descriptor.pb.cc.o' failed
make[5]: *** [CMakeFiles/libprotobuf.dir/src/google/protobuf/descriptor.pb.cc.o] Error 4
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/libprotobuf.dir/all' failed
make[4]: *** [CMakeFiles/libprotobuf.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make[3]: *** [all] Error 2
CMakeFiles/extern_protobuf.dir/build.make:112: recipe for target 'third_party/protobuf/src/extern_protobuf-stamp/extern_protobuf-build' failed
make[2]: *** [third_party/protobuf/src/extern_protobuf-stamp/extern_protobuf-build] Error 2
CMakeFiles/Makefile2:256: recipe for target 'CMakeFiles/extern_protobuf.dir/all' failed
make[1]: *** [CMakeFiles/extern_protobuf.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

====================================================
系统环境：Centos6.8，gcc 6.3.1,  cmake 3.6

**Comment by zhanghan1992** [comment]
参考 https://github.com/baidu/AnyQ/issues/61
减少paddle和xgboost的编译线程数
