### ISSUE TITLE
语义检索：基于SimNet语义表示，使用ANNOY进行ANN检索 // 不懂啊

### ISSUE THREAD

**Issue by guotong1988** [baidu/AnyQ#82]
“基于SimNet语义表示” 即表示成向量
然后怎么Retrieval？挨个计算向量cosine？

**Comment by zhanghan1992** [comment]
anyq里的语义检索使用了annoy(一种快速在向量空间中寻找k紧邻的近似算法)，详情见https://github.com/spotify/annoy

**Comment by guotong1988** [comment]
谢谢！！
