### ISSUE TITLE
编译问题

### ISSUE THREAD

**Issue by MTaoYue** [baidu/AnyQ#85]
CMake Error at /usr/local/share/cmake-3.3/Modules/ExternalProject.cmake:1717 (message):
  error: could not find git for clone of extern_zlib
Call Stack (most recent call fi
[CMakeOutput.log](https://github.com/baidu/AnyQ/files/2622889/CMakeOutput.log)

rst):
  /usr/local/share/cmake-3.3/Modules/ExternalProject.cmake:2356 (_ep_add_download_command)
  cmake/external/zlib.cmake:12 (ExternalProject_Add)
  CMakeLists.txt:35 (include)

**Comment by Xuanfang1121** [comment]
我也遇到这个问题，您是怎么解决的

**Comment by MTaoYue** [comment]
@Xuanfang1121 没有解决，放弃这个了。
