### ISSUE TITLE
语义相似度计算效果为啥那么差

### ISSUE THREAD

**Issue by zhaodp** [baidu/AnyQ#88]
question	answer
怎么没有单	1
赶紧派单啊	2	
给个顺路单	3	
给个回程单	4
可以打出租车	5

上面是我灌入的qa数据，配置了语义所以效果不好，输入“哈哈”，匹配出了：
[
{
answer: "4",
confidence: 0.6898366212844849,
json_info: "{} ",
qa_id: "4",
question: "给个回程单"
}
]

log如下：
I1210 12:05:39.349898 52151 simnet_paddle_sim.cpp:91] RAW: source query:哈哈
I1210 12:05:39.349898 52151 simnet_paddle_sim.cpp:126] RAW: candidate query:给个回程单, socre:0.862296
I1210 12:05:39.349898 52151 simnet_paddle_sim.cpp:126] RAW: candidate query:怎么没有单, socre:0.726798
I1210 12:05:39.349898 52151 simnet_paddle_sim.cpp:126] RAW: candidate query:给个顺路单, socre:0.616571
I1210 12:05:39.349898 52151 simnet_paddle_sim.cpp:126] RAW: candidate query:赶紧派单啊, socre:0.465596
I1210 12:05:39.349898 52151 simnet_paddle_sim.cpp:126] RAW: candidate query:可以打出租车, socre:0.240768
I1210 12:05:39.349898 52151 jaccard_sim.cpp:48] RAW: jaccard = 0.000000
I1210 12:05:39.349898 52151 jaccard_sim.cpp:48] RAW: jaccard = 0.000000
I1210 12:05:39.349898 52151 jaccard_sim.cpp:48] RAW: jaccard = 0.000000
I1210 12:05:39.349898 52151 jaccard_sim.cpp:48] RAW: jaccard = 0.000000
I1210 12:05:39.349898 52151 jaccard_sim.cpp:48] RAW: jaccard = 0.000000
I1210 12:05:39.349898 52151 rank_strategy.cpp:475] RAW: after rank, remain 2 cands
I1210 12:05:39.349898 52151 rank_strategy.cpp:256] RAW: anyq query: 哈哈
I1210 12:05:39.349898 52151 rank_strategy.cpp:257] RAW: output
I1210 12:05:39.349898 52151 rank_strategy.cpp:259] RAW: 	query:给个回程单
I1210 12:05:39.349898 52151 rank_strategy.cpp:260] RAW: 	confidence:0.689837
I1210 12:05:39.349898 52151 anyq_strategy.cpp:77] RAW: input_query=哈哈;analysis_time=3.00ms;retrieval_num=5;retrieval_time=4.00ms;anyq_answer=4;rank_item_num=2;rank_time=12.00ms;

哈哈和给个回程单完全不相似啊，怎么会这样？

**Comment by zhaodp** [comment]
能给回复下吗？是什么原因？

**Comment by yinweichong** [comment]
a) 这些候选其实不应该被召回，是语义索引带来的badcase，你使用的语义索引是直接使用语义匹配模型中的表示向量，可能不太适用召回场景（从海量中找到相关），我们后续考虑构建适用于召回语义表示的模型；
    b) 匹配打分确实不合理，语义匹配模型作用在Rank阶段（从相关的few中找到最相似），假定的是候选都比较相关，完全不相关的case可能存在打分比较高的情况，这可能跟这个模型的训练数据构造有关；
    c) 可以考虑语义特征+字面匹配特征（如编辑距离等）

**Comment by zhaodp** [comment]
> ```
> a) 这些候选其实不应该被召回，是语义索引带来的badcase，你使用的语义索引是直接使用语义匹配模型中的表示向量，可能不太适用召回场景（从海量中找到相关），我们后续考虑构建适用于召回语义表示的模型；
> b) 匹配打分确实不合理，语义匹配模型作用在Rank阶段（从相关的few中找到最相似），假定的是候选都比较相关，完全不相关的case可能存在打分比较高的情况，这可能跟这个模型的训练数据构造有关；
> c) 可以考虑语义特征+字面匹配特征（如编辑距离等）
> ```

“我们后续考虑构建适用于召回语义表示的模型”，这块你们有具体计划吗？感觉现在AnyQ无法正式用到生产环境，效果不好，感觉整体设计是很先进的，但是用于召回的语义索引效果太差了。

**Comment by yinweichong** [comment]
1. 关于语义索引
- 召回阶段有两种召回策略，倒排索引和语义索引；
- 语义索引作为倒排索引的补充；实际项目中未尝试单独使用语义索引进行召回；

**Comment by zhaodp** [comment]
> 1. 关于语义索引
> 
> * 召回阶段有两种召回策略，倒排索引和语义索引；
> * 语义索引作为倒排索引的补充；实际项目中未尝试单独使用语义索引进行召回；

我配置的AnyQ即有倒排索引，也有语义索引，倒排索引没有索引到输入的关键字，语义索引匹配出来了，完全不相关，你说的“语义索引作为倒排索引的补充”是指什么？你是说我的配置有问题吗？
如果把AnyQ用到实际项目，我应该怎么做？能给些建议吗？

**Comment by yinweichong** [comment]
配置没有问题；
可以考虑：
1. 召回阶段只使用倒排索引进行召回；
2. re-rank阶段
- 提高结果阈值(rank.conf threshold)；
- 对字面&语义特征进行调权(rank_weights)；

**Comment by zhaodp** [comment]
好的，谢谢，想问一下AnyQ目前有没有用于百度的实际项目？

**Comment by yinweichong** [comment]
有，针对实际需求和项目研发的AnyQ

**Comment by yitian134** [comment]
> 1. 关于语义索引
> 
> * 召回阶段有两种召回策略，倒排索引和语义索引；
> * 语义索引作为倒排索引的补充；实际项目中未尝试单独使用语义索引进行召回；

hi 咨询下，'作为补充' 是说用两种索引召回，然后加权求和吗？一般生产环境的使用方式是什么样的呢？

**Comment by wangshuohuan** [comment]
使用过程中，会把两个索引过程的结果进行合并，送入排序阶段，根据排序阶段的得分进行返回。生产环境中有两种使用方式：使用倒排索引，或者倒排索引和语义索引一起使用。

**Comment by zhangyanbo2007** [comment]
@zhaodp 兄弟，我也在用anyQ,交流交流，我的微信号是15821444815，大家看到了加我哈，一起研究
