### ISSUE TITLE
编译出错

### ISSUE THREAD

**Issue by wshhja** [baidu/AnyQ#89]
您好，我在docker环境中进行编译，但是在make 的时候一直报这个错误，请问需要怎么解决呢？

[root@90f066c4a231 build]# make
[  5%] Built target extern_jsoncpp
[ 10%] Built target extern_xgboost
[ 11%] Performing build step for 'extern_paddle'
[  1%] Built target extern_snappy
[  2%] Built target extern_threadpool
[  2%] Built target extern_mklml
[  3%] Built target extern_warpctc
[  4%] Built target extern_boost
[  4%] Built target extern_gflags
[  5%] Built target extern_lib_any
[  5%] Built target extern_zlib
[  6%] Built target extern_eigen3
[  6%] Built target profiler_py_proto_init
[  6%] Built target framework_py_proto_init
paddle/fluid/platform/CMakeFiles/profiler_py_proto.dir/build.make:60: *** target pattern contains no `%'.  Stop.
make[4]: *** [paddle/fluid/platform/CMakeFiles/profiler_py_proto.dir/all] Error 2
make[4]: *** Waiting for unfinished jobs....
[  7%] Built target extern_snappystream
[  7%] Built target extern_glog
[  8%] Built target extern_protobuf
make[3]: *** [all] Error 2
make[2]: *** [third_party/paddle/src/extern_paddle-stamp/extern_paddle-build] Error 2
make[1]: *** [CMakeFiles/extern_paddle.dir/all] Error 2
make: *** [all] Error 2
[root@90f066c4a231 build]#

**Comment by zhanghan1992** [comment]
cmake版本的问题，建议使用cmake 3.2.2

**Comment by wshhja** [comment]
cmake问题解决了，编译通过，但是又出现下面的问题
I1212 21:05:15.691386  1630 utils.cpp:590] RAW: in json_to_analysis_item, query:我是谁
I1212 21:05:15.691386  1630 utils.cpp:594] RAW: in json_to_analysis_item, type:(null)
I1212 21:05:15.691386  1630 analysis_strategy.cpp:115] RAW: analysis_analysis size: 1
I1212 21:05:15.691386  1630 analysis_strategy.cpp:130] RAW: before use analysis strategy's analysis_result
I1212 21:05:15.691386  1630 utils.cpp:609] RAW: query:我是谁
I1212 21:05:15.691386  1630 utils.cpp:611] RAW: tokens_basic size is 0
I1212 21:05:15.691386  1630 analysis_strategy.cpp:148] RAW: method_process method_wordseg start
I1212 21:05:15.691386  1630 analysis_strategy.cpp:154] RAW: method_process method_wordseg sucess
I1212 21:05:15.691386  1630 analysis_strategy.cpp:148] RAW: method_process method_simnet_emb start
I1212 21:05:15.691386  1630 analysis_strategy.cpp:154] RAW: method_process method_simnet_emb sucess
I1212 21:05:15.691386  1630 analysis_strategy.cpp:163] RAW: after use analysis strategy's analysis_result
I1212 21:05:15.691386  1630 utils.cpp:609] RAW: query:我是谁
I1212 21:05:15.691386  1630 utils.cpp:611] RAW: tokens_basic size is 3
I1212 21:05:15.691386  1630 utils.cpp:614] RAW: tokens_basic	buffer:我	length:3	offset:0	analysis_term_weight:0.333333
I1212 21:05:15.691386  1630 utils.cpp:614] RAW: tokens_basic	buffer:是	length:3	offset:3	analysis_term_weight:0.333333
I1212 21:05:15.691386  1630 utils.cpp:614] RAW: tokens_basic	buffer:谁	length:3	offset:6	analysis_term_weight:0.333333
I1212 21:05:15.691386  1630 equal_solr_q_builder.cpp:48] RAW: equal solr_fetch_q=question:我是谁
I1212 21:05:15.691386  1630 term_retrieval.cpp:109] RAW: solr_fetch_q=question:我是谁
I1212 21:05:15.691386  1630 term_retrieval.cpp:119] RAW: url = http://127.0.0.1:8900/solr/collection1/select
I1212 21:05:15.691386  1630 http_client.cpp:84] RAW: para_url: fl=id,question,answer&q=question%3A%E6%88%91%E6%98%AF%E8%B0%81&rows=15&wt=json
W1212 21:05:15.691386  1630 http_client.cpp:94] RAW: curl_easy_perform Failed[Couldn't connect to server];
W1212 21:05:15.691386  1630 term_retrieval.cpp:205] RAW: solr_request failed.
E1212 21:05:15.691386  1630 retrieval_strategy.cpp:122] RAW: plugin term_recall_1 retrieval error
E1212 21:05:15.691386  1630 anyq_strategy.cpp:69] RAW: retrieval module process error
E1212 21:05:15.691386  1630 http_service_impl.cpp:133] RAW: anyq run_strategy failed!

**Comment by ZhangZoffy** [comment]
用的就是cmake3.2.2版本报一样的错
