### ISSUE TITLE
请问如何导出pb文件？

### ISSUE THREAD

**Issue by ky941122** [baidu/AnyQ#93]
您好，我用simnet训了一个网络之后，只得到了固定导出的checkpoint，现在我想导出pb文件用于上线部署，但我不知道图的输入输出tensor名以及图的结构，请问simnet有提供直接导出pb的方法么，还是有什么别的方式。万分感谢。

**Comment by ky941122** [comment]
多谢

**Comment by zhangyanbo2007** [comment]
关于anyQ源码细节研读，请加我微信15821444815，一起研究研究！
