### ISSUE TITLE
运行demo，提问没有回答？

### ISSUE THREAD

**Issue by shuangluhuifeng** [baidu/AnyQ#94]
通过http访问“curl 0.0.0.0:8999/anyq?question=需要使用什么账号登录”结果为空，在docker内看到日志solr_request 失败。请教一下，是什么情况？

I0103 09:33:13.228092    56 utils.cpp:609] RAW: query:需要使用什么账号登录
I0103 09:33:13.228092    56 utils.cpp:611] RAW: tokens_basic size is 5
I0103 09:33:13.228092    56 utils.cpp:614] RAW: tokens_basic    buffer:需要     length:6        offset:0        analysis_term_weight:0.200000
I0103 09:33:13.228092    56 utils.cpp:614] RAW: tokens_basic    buffer:使用     length:6        offset:6        analysis_term_weight:0.200000
I0103 09:33:13.228092    56 utils.cpp:614] RAW: tokens_basic    buffer:什么     length:6        offset:12       analysis_term_weight:0.200000
I0103 09:33:13.228092    56 utils.cpp:614] RAW: tokens_basic    buffer:账号     length:6        offset:18       analysis_term_weight:0.200000
I0103 09:33:13.228092    56 utils.cpp:614] RAW: tokens_basic    buffer:登录     length:6        offset:24       analysis_term_weight:0.200000
I0103 09:33:13.228092    56 equal_solr_q_builder.cpp:48] RAW: equal solr_fetch_q=question:需要使用什么账号登录
I0103 09:33:13.228092    56 term_retrieval.cpp:109] RAW: solr_fetch_q=question:需要使用什么账号登录
I0103 09:33:13.228092    56 term_retrieval.cpp:119] RAW: url = http://127.0.0.1:8900/solr/collection1/select
I0103 09:33:13.228092    56 http_client.cpp:84] RAW: para_url: fl=id,question,answer&q=question%3A%E9%9C%80%E8%A6%81%E4%BD%BF%E7%94%A8%E4%BB%80%E4%B9%88%E8%B4%A6%E5%8F%B7%E7%99%BB%E5%BD%95&rows=15&wt=json
W0103 09:33:13.228092    56 http_client.cpp:94] RAW: curl_easy_perform Failed[Couldn't connect to server];
W0103 09:33:13.228092    56 term_retrieval.cpp:205] RAW: solr_request failed.
E0103 09:33:13.228092    56 retrieval_strategy.cpp:122] RAW: plugin term_recall_1 retrieval error
E0103 09:33:13.228092    56 anyq_strategy.cpp:69] RAW: retrieval module process error
E0103 09:33:13.228092    56 http_service_impl.cpp:133] RAW: anyq run_strategy failed!

**Comment by oyjxer** [comment]
请检查一下solr是否启动，solr对应地址与port是否配置正确

**Comment by zhangyanbo2007** [comment]
我也遇到相同的问题，请问楼主已经解决了吗？

**Comment by shuangluhuifeng** [comment]
已解决，多谢oyjxer的建议。
